### ISSUE TITLE
Date validation for comparing a single date to multiple dates

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#1000]
There are a few places in the application where a single date is compared to multiple dates. For example, The date an applicant is married must be `>=` the applicant and partner DOB.

---

- [x] **Date married/civil union/domestic partnership**
src/components/Section/Relationships/RelationshipStatus/CivilUnion.jsx
Provide date when you entered into your civil marriage, civil union, or domestic partnership 
Date must be greater than or equal to both DOB and "Date of birth" (17.2.2) . Date must be less than or equal to NOW. 

- [x] **Date your civil marriage, civil union, or domestic partnership was legally recognized** 
src/components/Section/Relationships/RelationshipStatus/Divorce.jsx
Provide the date your civil marriage, civil union, or domestic partnership was legally recognized 
Date must be greater than or equal to both DOB and "Date of birth" (17.12.2) . Date must be less than or equal to NOW. 

- [x] **Date cohabitation began** 
src/components/Section/Relationships/RelationshipStatus/Cohabitant.jsx
Provide date cohabitation began 
Date must be greater than or equal to both DOB and "Date of birth" (17.17.2) . Date must be less than or equal to NOW. 

- [x] **Approximate date of first contact**
src/components/Section/Relationships/Relatives/Relative.jsx
Provide approximate date of first contact 
Date must be greater than or equal to both DOB and "Your relative's date of birth" (18.2.3) . Date must be less than or equal to 
NOW. 

- [x] **Approximate date of last contact** 
src/components/Section/Relationships/Relatives/Relative.jsx
Provide approximate date of last contact 
Date must be greater than or equal to "Approximate date of first contact" (18.13.1) . Date must be less than or equal to NOW. 

- [x] **Approximate date of first contact** 
src/components/Section/Foreign/Contacts/ForeignNational.jsx
Provide approximate date of first contact 
Response is required. Date must be greater than or equal to DOB and subject DOB and less than or equal to NOW. 

- [x] **Dates of stay in the U.S. for the sponsored foreign national** 
src/components/Section/Foreign/Business/SponsorshipItem.jsx
Provide the dates of stay in the U.S. for the sponsored foreign national 
_From Date_ 
Ensure valid date, no future date allowed. Date must be greater than or equal to DOB and 
/Pooled/ForeignBusinessActivities/SponsoredVisits/SponsoredVisit[@ID]/Birth/Date "Date of birth for the 
sponsored foreign national" (20B.26.2) . 
_To Date_ 
Ensure valid date greater than or equal to From Date. Date must be less than or equal to NOW. "Present" allowed instead of date.

- [x] **Date satisfied** 
src/components/Section/Financial/Taxes/TaxesItem.jsx
Provide date satisfied 
Date must be greater than or equal to "Year you failed to file or pay your Federal, state, or other taxes" (26.10.2) . Date 
must be less than or equal to NOW.

**Comment by line47** [comment]
Using https://github.com/18F/e-QIP-prototype/tree/sw-date-val-complex branch for this work

**Comment by ryanhofdotgov** [comment]
@christopherhuii is going to fix the issue he discovered in the associated PR https://github.com/18F/e-QIP-prototype/pull/1058
