### ISSUE TITLE
Adjust codecov settings

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1009]
Until we get codecov back up to 90%, configure codecov to stop failing PRs because codecov is less than 90%

**Comment by line47** [comment]
Worked with @mgwalker on disabling codecov altogether. 
He mentioned trying to get codecov to stop failing based on a percentage in the past and did not have any luck so we will just disable and I'm going to put a PR in to re-enable as a reminder to do that at some point.
