### ISSUE TITLE
Snyk doesn't like `package.json`

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1012]
Snyk stopped reporting on `package.json`, but continued to work on `specs/package.json` in the past week.

Removing everything and attempting to re-add `package.json` was not fruitful. One approach to try: set up a fork of the repo and try to reproduce, backing out recent changes until it starts working again.

**Comment by el-mapache** [comment]
What was the error we were seeing on github? Locally, running `snyk test` works fine.

**Comment by ryanhofdotgov** [comment]
The error displayed in the GitHub integration on an issue is "Failed to detect issues":
https://support.snyk.io/webhooks/failed-to-detect-issues

But when I deleted and re-added the project in Snyk, it says it doesn't find any supported files. It will only recognize the one under specs.

**Comment by ryanhofdotgov** [comment]
Looks like it was a problem in Snyk – it started processing it again some months ago.
