### ISSUE TITLE
NBIB will not fix "now" issues

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1015]
Review individual defects marked "Will Not Fix"/"Will Not Fix/Being Review" in the referenced spreadsheet. Verify they should in fact be implemented, open up corresponding issues, schedule for a particular sprint.

**Comment by michaelccata** [comment]
@ryanhofdotgov can you share the spreadsheet containing these issues from NBIB

**Comment by ryanhofdotgov** [comment]
@michaelccata _ISSUES_SUMMARY sheet at bottom, with "Will Not Fix" and "Will Not Fix/Being Review" filter on column K:
https://docs.google.com/spreadsheets/d/1BiMN0LKJvpbPbW-pgde34eQi4Cop4BIGMagTKibtE0g/edit#gid=1171836397

**Comment by ryanhofdotgov** [comment]
Outstanding issues are of a lower priority relative to what we use the `high` label for.
