### ISSUE TITLE
Ask about current spouse's APO/FPO

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1029]
This is similar, but not exact, as: #753 and #924 

First collect either a US address or a foreign address. Do not collect a APO address initially.

Regardless of the current address, always ask "Does the person have an APO/FPO address within the United States?". The only options are Yes/No. 

If Yes, display and prompt for APO address and also a physical address.

<img width="400" alt="screen shot 2018-10-18 at 8 28 01 pm" src="https://user-images.githubusercontent.com/37100189/47196236-6dd0b080-d314-11e8-9caa-638d3c8757ac.png">

The scope of this ticket does not include encoding this data correctly into e-QIP XML – thats addressed in https://github.com/18F/e-QIP-prototype/issues/1030

**Comment by el-mapache** [comment]
@ryanhofdotgov The issue says
```
If Yes, display and prompt for APO address and also a physical address.
```

I assume this means just show the APO address block and continue to show the original Domestic/Foreign address block? Just double checking before I get too far with this!

**Comment by ryanhofdotgov** [comment]
@el-mapache Actually, when I wrote that I was referring to the more complicated workflow represented by the SF-86 hard copy form:

1) Collect a domestic or foreign primary address. There is also an option to say "use my current address". Don't allow APO entry.

2) Then it asks does spouse have an APO? --> If Yes, then it collects APO as a secondary address.

3) Then if the spouse has an APO, then it prompts for a tertiary physical address.

However, double-checking what e-QIP does with the validation matrix on page 81 – this actually seems to be one of those rare places where it disagrees with what the hard copy PDF dictates. According to the validation matrix, this instance is just like the ones in #924, #1107, #1108.

I would go with that.
