### ISSUE TITLE
Clicking "I don't know" for verifier email should clear email

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1034]
**What did you do?**

For education verifier for school in past 3 years, specify email (e.g. foo@example.com) Then click "I don't know". Then click on "I don't know" again to clear it.

**What did you expect to see?**

No previously stored email address

**What did you see instead?**

foo@example.com – the field was not cleared.

**Additional Information**

Likely affects other places where email is collected but optionally can be an "I don't know".

**Comment by suzubara** [comment]
Taking this on, can't assign or push yet though
