### ISSUE TITLE
Time period of additional employment activities should not overlap main entry

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1036]
The time periods for additional employment activities are expected to be from a period of time before the current entry. e-QIP will enforce this. Example error:
"To Date [for additional employment activity] must not be later than [this main entry's] Dates of employment From Date, 1/2005"

From the original test case #7:
1) applicant filled out employment entry:

<img width="400" alt="screen shot 2018-10-20 at 9 38 09 am" src="https://user-images.githubusercontent.com/37100189/47258192-8b089a80-d44c-11e8-9163-9821e4dcfe5d.png">

2) applicant filed out 2 additional (bogus) employment periods underneath this main employment entry.

<img width="400" alt="screen shot 2018-10-20 at 9 38 20 am" src="https://user-images.githubusercontent.com/37100189/47258194-952a9900-d44c-11e8-891a-a62aeede3059.png">

<img width="400" alt="screen shot 2018-10-20 at 9 38 25 am" src="https://user-images.githubusercontent.com/37100189/47258198-9cea3d80-d44c-11e8-8395-da485776f831.png">

Both additional entries were rejected by e-QIP.

**Comment by ryanhofdotgov** [comment]
@gidjin checkout page 41, "Additional Periods of Activity with this Employer" in validation matrix PDF for the exact validation rules.

**Comment by joshmfranklin** [comment]
Error message for additional date of employment

**There is a problem with the date**
For the **to** date, the date should be before the main entry's **from** date.
