### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1039]
**What did you do?**

*Including steps for recreating it, if applicable.*

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?
 - What operating system?

**Comment by hursey013** [comment]
Duplicate of https://github.com/18F/e-QIP-prototype/issues/1038
