### ISSUE TITLE
For Drug use purchase: most recent involvement date can't be before 1st involvement

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1046]
Placeholder

**Comment by line47** [comment]
Fixed in PR https://github.com/18F/e-QIP-prototype/pull/929

**Comment by line47** [comment]
The validation is working The error message could use some updating though.
applicant birth date on this is 6/9/1979 (so both dates are after DOB)

![screen shot 2018-11-08 at 1 27 23 pm](https://user-images.githubusercontent.com/1449852/48219277-15f8f880-e35a-11e8-81b3-0e4e9b50614b.png)
