### ISSUE TITLE
Year tax was failed to be filed/paid can not be after the date settled

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1048]
Year tax was failed to be filed/paid can not be after the date settled. Edit: per comments below, logic is there, but error message is not correct.

**Comment by line47** [comment]
I think this is part of https://github.com/18F/e-QIP-prototype/issues/1000

**Comment by line47** [comment]
I think this was fixed in PR https://github.com/18F/e-QIP-prototype/pull/929

**Comment by line47** [comment]
The validation is working The error message could use some updating though.
applicant birth date on this is 6/9/1979 (so both dates are after DOB)

![screen shot 2018-11-08 at 1 16 42 pm](https://user-images.githubusercontent.com/1449852/48218764-9dde0300-e358-11e8-8baf-4475a90edb88.png)
