### ISSUE TITLE
Collect secondary address for employment address

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1050]
Edit:
The employment address does not current implement the secondary/alternate address workflow that has been recently implemented elsewhere in the form. This is similar to the work done in #924, but with an important difference detailed below.

There are 2 sub-workflows associated with the "standard" secondary/alternate address workflow. They are implemented via the AlternateAddress component.

***1) APO sub-workflow:***

**What did you do?**

Enter in an APO address for address for employment. 

**What did you expect to see?**

The form prompt for `physical location data` (note: this is separate concept from the `physical work address`)

**What did you see instead?**

No change to the form, no additional data collected

***2) Foreign address sub-workflow:***

**What did you do?**

Enter in a foreign address for employment

**What did you expect to see?**

The form prompt if I had an APO address at the location, and collect it if the answer is yes.

**What did you see instead?**

No change to the form, no additional data collected

**3) Differences from standard alternate address workflow**

The above 2 work flows show the standard alternate address workflow (experiment/try out with the relative address, verifier address, supervisor address, etc. – they all have this workflow).

Employment is different in a couple of different ways:
* Any employment that is not military, asks if the `physical work address` is different from the employers. If No, then alternate address workflows behave like the standard address workflow implemented elsewhere. If Yes, then the alternate address workflow is keyed off the `physical work address`, not the employer address. Read pp. 42/43 in the validation matrix.

* For military employment, the alternate address flow is always keyed off the employer address (aka `duty station`). 

**Additional Information**

@el-mapache did extensive work in eApp to support the alternate address workflow. Most of those related issues are listed in this roll-up issue here:
https://github.com/18F/e-QIP-prototype/issues/1031

Review the relevant sections in the validation matrix (pp. 36/37,  pp. 42/43, pp. 48/49) several times, the SF-86 form, and the related tickets/PRs on the roll-up issue above before implementing.

**Comment by ryanhofdotgov** [comment]
This was mistakenly closed – it is still outstanding. Would request that either @christopherhuii or @gidjin from the Truss team pick this one up in the next sprint, reviewing the similar work that @el-mapache did in the 2018-11-20 sprint. 

Assigning to myself first, to flesh out the issue description, as this one is particularly complicated with variants for Military Employment. Related specification is around page 37 of validation matrix.

**Comment by ryanhofdotgov** [comment]
After this is implemented, address https://github.com/18F/e-QIP-prototype/issues/1213

**Comment by macrael** [comment]
The FE changes for this are in but there is still BE work to be done.
