### ISSUE TITLE
Instructions and logout link overlap the official government banner

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#1054]
**What did you do?**

Click the "Here's how you know" link in the `An official website of the United States government` banner in full size desktop mode.

**What did you expect to see?**

The instructions and logout link to continue to be anchored to the blue header.

**What did you see instead?**

Barely visible instructions and logout link mixed in with the expanded content.

![screen shot 2018-10-22 at 4 37 03 pm](https://user-images.githubusercontent.com/1178494/47318306-b8ef0a00-d619-11e8-8dce-e22032d74308.png)

**Comment by line47** [comment]
Also note the `<strong>https://</strong>` tag in the description
