### ISSUE TITLE
Implement Single Log Out (SLO)

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1064]
As a user, when I click logout in eApp, I want my identity provider session terminated (as well as my eApp session).

WSO2 implements the SAML Single Log Out standard and should be used to achieve this.

References:
https://www.portalguard.com/blog/2016/06/20/saml-single-logout-need-to-know/
http://daytodayjava.blogspot.com/2015/08/saml2-idp-initiated-single-logout-with.html

**Comment by ryanhofdotgov** [comment]
Related to https://github.com/18F/e-QIP-prototype/issues/524

**Comment by macrael** [comment]
https://github.com/18F/e-QIP-prototype/blob/develop/docs/saml.md

**Comment by ryanhofdotgov** [comment]
Per slack discussion https://gsa-tts.slack.com/team/UD4154S1W, focus on SP-initiated SLO. IdP initiated SLO as a follow-on task or stretch goal.

**Comment by ryanhofdotgov** [comment]
Signing SLO requests split off into follow on issue: https://github.com/18F/e-QIP-prototype/issues/1206
