### ISSUE TITLE
Response: "I don't know" for dates (Legal Section) appears to prevent eApp from generating the XML.

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1088]
This is a high priority because users for T3R often won't know the dates of their investigations and the SF86 won't submit with errors unavailable to the applicant.

Troubleshooting performed:
Connected with individual who experiencing issue
Had individual attempt to submit
Reviewed logs (see below)
Confirmed with user that he has 2 prior investigation records, is putting "I don't know" for the date
Confirmed with the user that changing the date values would not impact an actual investigation
Changed the dates from "I don't know" to actual dates 
Confirmed he was able to submit. 

Errors from the logs:
time="2018-10-31T13:56:56Z" level=warning msg="Unable to generate XML from Form Application Data" account=95 error="template: application.xml:45:14: executing \"application.xml\" at <tmpl \"legal.xml\" .>: error calling tmpl: template: legal.xml:5:2: executing \"legal.xml\" at <tmpl \"legal-investig...>: error calling tmpl: template: legal-investigations.xml:4:4: executing \"legal-investigations.xml\" at <tmpl \"legal-investig...>: error calling tmpl: template: legal-investigations-investigated.xml:12:10: executing \"legal-investigations-investigated.xml\" at <monthYear $Item.Gran...>: error calling monthYear: template: date-month-year.xml:1:25: executing \"date-month-year.xml\" at <.props.month>: invalid value; expected string" ip=192.152.18.167

time="2018-10-31T13:56:56Z" level=info msg="error transmitting" error="Unable to generate XML from Form Application Data" ip=192.152.18.167

(Please check all "I don't know" for dates)

**Comment by ryanhofdotgov** [comment]
This was fixed in https://github.com/18F/e-QIP-prototype/commit/fb311e5a76329ec7c5727406c9fdbcda0aafeffd#diff-9db4cac7b5b4a176d84bbaea49c4a06a on Oct. 22nd for test case 7, which was part of the 1.0.4 release.
