### ISSUE TITLE
Modify `validate()` response and parsing

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1094]
In https://github.com/18F/e-QIP-prototype/pull/1082, backend APIs were modified to return HTTP error status codes when there was an error and limit implementation detail in the response messages. 

However, we overlooked that the `api.validate` call on the frontend expects the response to be of a certain format and the frontend implementation does not handle `400 Bad Request Error` correctly (the whole app just hangs).

Also, the condition where USPS can't find an address probably shouldn't be an HTTP error at our level of abstraction. 

This commit https://github.com/18F/e-QIP-prototype/commit/c68be771bd4a3e7be4b13235bfc79f37968b23eb partially reverted https://github.com/18F/e-QIP-prototype/pull/1082 and is a stand-in fix until this issue can be resolved. 

Goal is to only return error codes at the correct abstraction of the API (no unnecessary implementation detail leaking) and make sure frontend does not hang if the `validate` call does return a 400 code for some valid reason.

cc: @macrael

**Comment by ryanhofdotgov** [comment]
Frontend code that calls `validate` and parses its response is in:
`src/validators/location.js:geocode`

Searching for other places where JSON error responses are parsed doesn't seem to show up anything:
`find src -type f -exec grep \\.Errors {} \; -print`

**Comment by macrael** [comment]
Where in the workflow does the validate endpoint get called?

**Comment by ryanhofdotgov** [comment]
@macrael Can you clarify? Are you looking for something more specific than https://github.com/18F/e-QIP-prototype/issues/1094#issuecomment-435271770 ? That function gets called when users type in an address on the form.

**Comment by macrael** [comment]
That's what I was looking for. This endpoint validates addresses with the USPS? I wasn't sure how much of the form it was validating.
