### ISSUE TITLE
Application Administrator feature to unlock an account in the database

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1099]
Relevant to the "kickback feature" when an eAgency user rejects the SF86 back to eApp.  In the case it doesn't successfully unlock, we need the ability to unlock it from an administrator's console.

"update accounts set locked='f' where username='forbes@mitre.org';  (replacing the username with the email address of the applicant).  

This is a LOW priority because we want to see the downstream impacts and the frequency before determining it needs to be a required feature.

**Comment by ryanhofdotgov** [comment]
@maryjohnston There's an `unlock` command-line tool that is part of eApp that has that functionality. We need to make sure to validate its existing behavior meets all the use cases, make sure it gets deployed in production, and that folks have some documented procedures around it.
