### ISSUE TITLE
Can't download attachments

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1101]
**What did you do?**

Load up test1.json, submit (web service disabled, so a no-op), click on certification PDF on final page.

**What did you expect to see?**

Certification PDF downloads.

**What did you see instead?**

No action take, 400 error in browser console.  This error in server log:
```
time="2018-11-05T10:52:54Z" level=warning msg="No identifier for attachment provided" account=2 error="strconv.Atoi: parsing \"\": invalid syntax" ip="192.168.2.156:42130"
```

**Additional Information**

In attachment GET handler, `mux.Vars()` returns an empty map.  I think this is related to https://github.com/gorilla/mux/issues/191 and the addition of the JWT middleware, which manipulated the context. 

I think solution is to upgrade gorilla mux. However, last time gorilla mux upgrade was attempted shortly before last vendor went off contract it broke the backend (OPTIONS calls were failing) and they reverted. It does not look like they opened up an issue. Here is a comment I had from that team:

"...not sure if something has changed with our HTTP mux (we have been using gorilla/mux) but if i set all the allowed HTTP methods we expect on the root router
```r.Methods("GET", "POST", "PUT", "DELETE", "OPTIONS")```
it starts to reach our handler methods."

For expediency sake, I might consider reverting the JWT handler related code, duplicating the code back in each method, then see performing library upgrade under a different issue.

**Comment by ryanhofdotgov** [comment]
@macrael Just to clarify, this issue isn't test case-specific, just suggested loading up test1.json because it's the fastest way to get a complete data set that allows you to "naturally" pass validation and submit and get to the download links affected.

If you are testing against a debug build, you can also put in some bare minimum info (name, birthdate), then click a "Force submit" link in the lower left corner of the submit page.

**Comment by macrael** [comment]
👍 

We can use this issue to track a better fix, probably upgrading mux.
