### ISSUE TITLE
Current spouse secondary address is not being persisted

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1157]
**What did you do?**

Fill out spouse information, list current address as foreign address. Click Yes to APO address question, fill out APO address. Log out, log back in, navigate back to current spouse section.

**What did you expect to see?**

See APO question answer and APO address.

**What did you see instead?**

APO question shown without an answer. No APO address.

**Comment by ryanhofdotgov** [comment]
@el-mapache Assigning you since you'll likely be able to fix it most easily, but if you don't have time this sprint, just unassign it. Thanks!

**Comment by el-mapache** [comment]
@ryanhofdotgov Looks like civil union data isn't stored as a blob, so I'll have to add the alternate address manually on the api side. Thanks for catching this.
