### ISSUE TITLE
eApp archival PDF doesn't show test case #9 Education

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1164]
**What did you do?**

Load up test case #9, which has no education listed – just "No" answers to the 2 questions. Submit. Save eApp archival PDF using the button on the submit page.

**What did you expect to see?**

Education section printed in the PDF, with "No" to the questions listed.

**What did you see instead?**

No Education questions printed in the PDF.

**Additional Information**

This might be related to the recent work to hide/show certain things in the PDF.  Data is correctly generated in the XML sent to e-QIP.

**Comment by ryanhofdotgov** [comment]
Test case 9 isn't merged into `develop` yet, but can be downloaded here:
https://github.com/18F/e-QIP-prototype/blob/rmh-alternate-address/api/testdata/complete-scenarios/test9.json

**Comment by ryanhofdotgov** [comment]
@line47 I can replicate the issue with test case 1 as well. Like test case 9, it doesn't show these questions:
* Have you attended any schools in the last 10 years?
* Have you received a degree or diploma more than 10 years ago?
(and doesn't show the Where you went to school/List the places you went to school headings at all)

Looking at my archive of test case archival PDFs, it seems to be a regression that slipped in between October 1st and November 1st.

**Comment by line47** [comment]
![screen shot 2018-11-16 at 2 18 56 pm](https://user-images.githubusercontent.com/1449852/48645925-255cef00-e9b5-11e8-9b94-90ab91fdc246.png)

I am seeing this `react-empty: 5776` on the print page maybe there is a property somewhere keeping it from rendering

**Comment by ryanhofdotgov** [comment]
@line47 Actually, I'm thinking this may be a long standing bug. The data I was looking at that pegged it to a regression between Oct-Nov is faulty. 

Because before you had fixed archival PDFs to expand accordions, I was creating archival PDFs by hand by manually going to each review section, printing to PDF, then concatenating them into one PDF.

Also, I think all the Field headings in History.jsx are missing... "Where you have lived", "Where you went to school". This one is noticeable because it is the only? one that has questions outside a specific `<Education` or `<Employment` or `<Federal`, etc. component.

**Comment by ryanhofdotgov** [comment]
@line47 – I've confirmed it has nothing to do with any recent changes and is a long standing issue from the original implementation of the Print function over a year ago. Going to take assignment of this ticket. Thanks for helping me track this down!

Most of the sections are defined 3 separate times: once for initial entry, again for review page, and a third time for the print view. Copy and pasted with slight variations in each. The exception is the Identification section, which was refactored as an exemplar a few months ago to minimize duplication.

**Comment by line47** [comment]
@ryanhofdotgov Thanks and glad I could help track it down. Wouldn't the refactoring work Aidan started with the sections help with this too?

**Comment by ryanhofdotgov** [comment]
Yeah, absolutely. We have https://github.com/18F/e-QIP-prototype/issues/614 scheduled for the next sprint. In the meantime, an expedient fix now saves multiple hours of multi-person meetings and large inter-agency email threads. :)
