### ISSUE TITLE
Suggested auto-populated entry for date gaps is misleading (Your history)

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1174]
**Sections affected**

Your history / Where you have lived
Your history / Employment activities
(perhaps other branching sections where gaps appear?)

**What did you see?**

The date range for a "gap" is automatically imported into a new entry which might be misleading. The gap might include several entries but the application assumes it's one by entering the whole range. 

<img width="828" alt="screen shot 2018-11-17 at 9 23 47 am" src="https://user-images.githubusercontent.com/4422873/48662103-da8db680-ea4a-11e8-8249-af2e6dfe2d39.png">
<img width="787" alt="screen shot 2018-11-17 at 9 23 59 am" src="https://user-images.githubusercontent.com/4422873/48662104-deb9d400-ea4a-11e8-9963-6ecd824f09b3.png">

**What did you expect to see?**

Perhaps only adding the first date would be useful? Or just get rid of the auto-populate in general?

**Additional Information**

**Comment by gidjin** [comment]
Has there been discussion with Mary about what she prefers as the solution to this issue?

**Comment by joshmfranklin** [comment]
I would suggest leaving both dates empty and let the user decide which dates to input. Giving them more freedom to start, and if we have to circle back and give them smarter defaults (i.e. only provide `from date`) we can do that at a later time.

**Comment by michaelccata** [comment]
That sounds good to me!

**Comment by michaelccata** [comment]
Let's clear out the autofill and move forward.
