### ISSUE TITLE
"Previous address autofill" for Supervisor Address

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1178]
**What did you do?**

Entering data for a private sector employment (non-government employment) and had to fill out multiple addresses. The functionality exists for military job postings, but not for private sector or state/local government. See screenshots below.

**What did you expect to see?**

<img width="649" alt="screen shot 2018-11-17 at 10 06 29 am" src="https://user-images.githubusercontent.com/4422873/48662500-c8af1200-ea50-11e8-8b0d-62374698cfab.png">

The functionality exists for military job postings, but not for private sector or state/local government. See screenshots below.

<img width="685" alt="screen shot 2018-11-17 at 10 12 05 am" src="https://user-images.githubusercontent.com/4422873/48662531-4115d300-ea51-11e8-9d6b-9157d68c05af.png">
<img width="633" alt="screen shot 2018-11-17 at 10 11 57 am" src="https://user-images.githubusercontent.com/4422873/48662532-42470000-ea51-11e8-89e5-ad006c3fb8e1.png">

**Comment by christopherhuii** [comment]
I don't think I've ever see the `Choose a previously used address` button ever. I'm trying to get it to show up now, and I'm not sure if I'm trying in the wrong place or If it's broken all around eApp.

Any steps to get it to show up?
