### ISSUE TITLE
"Other names used" has aggressive date validation error

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1180]
**What did you do?**

Entered a relative (also is a problem for spouses in the marital section)

**What did you expect to see?**

Expected to enter the dates of the "other name used" from their birth until their marriage or other life event.

**What did you see instead?**

eApp triggered validation on the dates saying that the name has to be used after their birth date even though that's the day they were born. Perhaps this should only trigger for "other name" start dates that are _**before**_ their birth?

<img width="769" alt="screen shot 2018-11-17 at 10 17 06 am" src="https://user-images.githubusercontent.com/4422873/48662606-5b9c7c00-ea52-11e8-8c95-b393e678480f.png">
<img width="776" alt="screen shot 2018-11-17 at 10 17 18 am" src="https://user-images.githubusercontent.com/4422873/48662607-5d663f80-ea52-11e8-8f61-ff9bda926d36.png">
<img width="773" alt="screen shot 2018-11-17 at 10 17 23 am" src="https://user-images.githubusercontent.com/4422873/48662609-5f300300-ea52-11e8-9561-fb0b8722f751.png">

**Comment by line47** [comment]
This looks to be addressed in https://github.com/18F/e-QIP-prototype/issues/1184

**Comment by michaelccata** [comment]
@line47 sorry, not seeing the relation between #1184 and this issue - were you able to test this?

**Comment by line47** [comment]
Gah sorry https://github.com/18F/e-QIP-prototype/pull/1058 addresses this
Just tested... 👍 

![screen shot 2018-11-30 at 2 30 49 pm](https://user-images.githubusercontent.com/1449852/49310670-e34fa500-f4ac-11e8-8d8a-e4ab61969dbc.png)
![screen shot 2018-11-30 at 2 31 18 pm](https://user-images.githubusercontent.com/1449852/49310682-f06c9400-f4ac-11e8-8180-dc73cb6b7ac9.png)
![screen shot 2018-11-30 at 2 31 34 pm](https://user-images.githubusercontent.com/1449852/49310685-f4001b00-f4ac-11e8-8b69-868ff40794e4.png)

**Comment by michaelccata** [comment]
Great, thanks @line47
