### ISSUE TITLE
Add the Statement of Understanding to the eApp PDF.

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1184]
Add the Statement of Understanding to the eApp PDF.

**Comment by maryjohnston** [comment]
#1015

**Comment by maryjohnston** [comment]
#1015 
Change per Sheldon Soltis

**Comment by ryanhofdotgov** [comment]
It appears in the browser view in eApp here:
<img width="400" alt="screen shot 2018-11-20 at 8 47 34 am" src="https://user-images.githubusercontent.com/37100189/48789083-17eb8180-eca1-11e8-96a9-acd67cb75899.png">

For background, it looks like this in the e-QIP PDF:
<img width="400" alt="screen shot 2018-11-20 at 8 47 51 am" src="https://user-images.githubusercontent.com/37100189/48789093-1f128f80-eca1-11e8-9090-1b62c42e4515.png">

Let's stick it above the "Information about You" section in the eApp print view:
<img width="400" alt="screen shot 2018-11-20 at 8 50 26 am" src="https://user-images.githubusercontent.com/37100189/48789230-70bb1a00-eca1-11e8-8b8c-b1e700060835.png">

**Comment by line47** [comment]
Do we want to have the yes/no radios as well?

**Comment by ryanhofdotgov** [comment]
@line47 Yeah, we want to preserve the Yes/No display, so it is just like the other Yes/No questions that appear in the print view of the form. But we just need to show it in the print view, not in the online display.

You can't access the form without saying Yes to that dialog, so it is accurate reflection of the user response to just indicate "Yes" in the print view.

Would you throw a header saying "Statement of Understanding" above it as well? (similar style/size as "Certification Releases" or "Data hash code". That's not in the original description, but seems in keeping with the sprit of the e-QIP PDF – thanks!
