### ISSUE TITLE
Section: Employment Activity -  eApp shows 'other employment', which not on e-QIP archival

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1188]
Edit:
eApp groups employment options into 2 categories:
* Government employment
* Other employment

NBIB objected to the "Other employment" label. However removal of that label necessitates removing the "Government employment" label/grouping as well. (An aside: federal contractor is incorrectly grouped under government employment in eApp).

<img width="400" alt="screen shot 2018-12-06 at 10 54 40 am" src="https://user-images.githubusercontent.com/37100189/49605491-78d3b480-f945-11e8-86c6-c30aac3c1cec.png">

Action:
Remove all grouping/labels in the employment type radio. 

Rollup-issue: #1015

**Comment by ryanhofdotgov** [comment]
I think this will have a negative effect on usability. Before this issue gets picked up, double-check with partner agency and document decision on issue.

**Comment by joshmfranklin** [comment]
I agree with @ryanhofdotgov I think that creating a larger list without the subdivided labels will be harder for the user to navigate the list of options. Was there a reason for the objection of the label from NBIB?

**Comment by ryanhofdotgov** [comment]
@joshmfranklin Any deviation from the original question form text outside of an explicit NBIB policy exemption raised (will raise) an objection from NBIB.

The clarifying text (i.e., the text that appears in a pop-up when you click the ? icon) may be edited without a policy exemption.
