### ISSUE TITLE
Employment activity pp. 13/15 not included on eQip archive PDF

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1189]
Section: Employment Activity_ eAPP: For this employment have any of the following happened to you in the lase (7) years? Fired, Quit after being told you would be fired, Left by mutual agreement following charges of allegations of misconduct, Left by mutual agreement following notice of unsatisfactory performance. Answer - 'NO' (page 13/15 on eApp pdf). This is not included on the e-QIP archival

**Comment by ryanhofdotgov** [comment]
Resolved back in September via PR https://github.com/18F/e-QIP-prototype/pull/825
