### ISSUE TITLE
Fix response to Foreign financial interest real estate

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1191]
Section: Foreign Financial Interests Real Estate co-owner Summary - Discrepancy: eApp asks -  Provide the date sold, if applicable. Response is 'Not Applicable'. E-QIP asks 'Provide the date sold if applicable. No date provided and 'not applicable' is not a response. 
#1015 

Edit:
Below is the relevant section, where NBIB test team is flagging that "Not applicable" be removed and the month/day/year input field set as a whole  be made optional in order to exactly match the text shown on the SF-86/e-QIP. (Partial input of month, day, or year would imply month/day/year should all be indicated)

<img width="400" alt="screen shot 2018-12-06 at 1 21 54 pm" src="https://user-images.githubusercontent.com/37100189/49612639-2ea8fe00-f95a-11e8-8626-e6894efc6e37.png">

**Comment by ryanhofdotgov** [comment]
I think removing the `Not applicable` button reduces usability. This should be double-checked with the partner before picking up.

There are 3 places in the SF-86 with a similar text ("if applicable") appears directly in the question text. I think for usability purposes, they should all have same behavior/Not applicable button.

SF-86 PDF:
20B (p.82) – Provide the name of the organization through, if applicable. Has `Not applicable` checkbox. 
eApp:
Has `Not applicable` button.

SF-86 PDF:
17 (p. 44) – Provide document expiration date, if applicable. Does not have `Not applicable` checkbox.
eApp:
Says "Provide document expiration date". (Discrepancy in text is a separate issue that should be fixed). Does not have `Not applicable` button.

*This issue:*
SF-86 PDF:
20A (p. 72) – Provide the date sold, if applicable. Does not have `Not applicable` checkbox.
eApp:
Has `Not applicable` button.
