### ISSUE TITLE
Real Estate Co-Owner Summary

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1192]
Foreign Financial Interests Real Estate Co-Owner Summary. eApp asks 'Are there any additional co-owners for this foreign financial interests controlled on your behalf to report? This question is not on e-QIP. However, the question is answered yes on eApp. The details provided are for entry #2 under Foreign Financial Interests Real Estate- Co-owners.
#1015

**Comment by ryanhofdotgov** [comment]
Resolved in October, duplicate of https://github.com/18F/e-QIP-prototype/issues/919
