### ISSUE TITLE
Sponsorship of a Foreign National - check address blocks

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1194]
Section: Sponsorship of a Foreign National - eApp entry #2 Provide Current street address of the sponsored foreign national shows 800 New Street, NY 10005. e-QIP shows 123 Seasame Street, New York Jamaica. 

#1015

**Comment by ryanhofdotgov** [comment]
Fixed in https://github.com/18F/e-QIP-prototype/issues/725, specifically https://github.com/18F/e-QIP-prototype/pull/754/commits/f8b58b6a35480f9b4ecb42ca8342c795793241e1 and https://github.com/18F/e-QIP-prototype/pull/754/commits/2511606c967e5ae49ddba1f4597c2859273cff84
