### ISSUE TITLE
Section 13: Self Employment Verifer has a middle name field in eAPP but not in eQIP.

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1196]
Section 13: Self Employment Verifer has a middle name field in eAPP but not in eQIP. #1015

**Comment by ryanhofdotgov** [comment]
This has a front-end component, as well as a XML generation component.

**Comment by christopherhuii** [comment]
@hursey013 Do you have an idea of how to do this? I'm trying to avoid passing a prop too many levels down.
