### ISSUE TITLE
Last Name field has "Initial Only" option

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1197]
Last Name field has "Initial Only" option

Edit: This change is anywhere last name appears in eApp. You can check on the SF-86 and in the validation matrix/XSD, there isn't a last name initial only attribute like with middle name (e.g, <Middle Type=IO>). So lets just remove the last name initial only option entirely across the entire app.

**Comment by ryanhofdotgov** [comment]
Where the SF-86 says "If you have only initials in your name, provide them and indicate "Initial only"", e-QIP (and the validation matrix page page 4), e-QIP has interpreted that to mean "initials in your [first] name". 

If there's no mention of character length in the validation matrix, then it is generally safe to assume that we shouldn't either (within reasonable limits on maximum). So a one character last name is fine.
