### ISSUE TITLE
Add "(excluding self-employment)'" to employment type text of non Government employment

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1198]
Section: Employment Activity - Discrepancy when applicant chooses employment type: eApp shows 'Non-government employment', e-QIP shows 'Non-government employment (excluding self-employment)'.  #1015

**Comment by christopherhuii** [comment]
![screen shot 2018-11-27 at 11 54 34 am](https://user-images.githubusercontent.com/8367504/49107683-41755180-f23b-11e8-8b3b-f3e60a986cc0.png)
If that's the case, should we also change, `State Government` to `State Government (non-Federal employment)`?
@ryanhofdotgov @michaelccata @maryjohnston

**Comment by christopherhuii** [comment]
![screen shot 2018-11-27 at 12 58 50 pm](https://user-images.githubusercontent.com/8367504/49111179-3d99fd00-f244-11e8-9fed-4afc7527c73d.png)

This is more than likely why the text in parenthesis was omitted. How do we want to style this so it displays correctly? Text smaller? buttons bigger? less padding?

**Comment by ryanhofdotgov** [comment]
Other parts of the form make the buttons taller as required:
<img width="437" alt="screen shot 2018-11-27 at 1 17 59 pm" src="https://user-images.githubusercontent.com/37100189/49112155-e184a800-f246-11e8-92c8-e098e1380baf.png">

@joshmfranklin If you have different guidance, feel free to chime in – thanks!

**Comment by joshmfranklin** [comment]
@ryanhofdotgov @christopherhuii Yeah I'd just make the buttons taller to accommodate the text. The plan for 85 is to make these normal radio buttons so hopefully this issue will be resolved in the future.
