### ISSUE TITLE
Providing Addresses: eAPP shows This address is  In the United States, which is not on e-QIP archival

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1199]
Providing Addresses: eAPP shows This address is  In the United States, which is not on e-QIP archival #1015

**Comment by maryjohnston** [comment]
e-QIP does not support this option, so remove from eApp, please.

**Comment by ryanhofdotgov** [comment]
@maryjohnston I think this is one of those cases where theoretically, this was an approved deviation from the SF-86 form and should not be altered.

It's a fundamental aspect of how eApp allows users to choose between inputing a domestic address vs a foreign one
<img width="400" alt="screen shot 2018-11-19 at 9 58 02 am" src="https://user-images.githubusercontent.com/37100189/48739212-1fab1780-ec08-11e8-9566-8e6509edfed1.png">

**Comment by joshmfranklin** [comment]
The options preceding the address fields are used to provide the proper fields for the user depending on their selection. As @ryanhofdotgov mentioned, this is a fundamental aspect of how eApp streamlines address fields for users depending on address location. Without all of the options there may be a loss of usability.
