### ISSUE TITLE
foreign Activities/Foreign Financial Interests

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1201]
Section: Foreign Activities/Foreign Financial Interests: eApp ask - 'are there any additional co-owners of this foreign financial interests? Response "Yes'. This question is not on the e-QIP archival, but details of the additional co-owner are provided.  

Roll-up #1015

Edit:

Background:
There are 3 places where foreign co-owner data is collected:
* Direct control
* Indirect control
* Real estate

Multiple co-owners are possible, so eApp current asks either at the end of the each co-owner entry:
* Are there any additional co-owners of this foreign financial interest? 
* Are there any additional co-owners for this foreign real estate? 

Unlike other parts of the form, an accordion is not used. Additional co-owner entries are just tacked on to the page, each with their copy of the "Are there any additional co-owners..." Yes/No question. See this example from `test3`:

*Question at end of Co-owner 1:*
<img width="400" alt="screen shot 2018-12-10 at 3 36 36 pm" src="https://user-images.githubusercontent.com/37100189/49768742-3fc37900-fc92-11e8-9ac1-1b62078b4b90.png">

*Question at end of Co-owner 2:*
<img width="400" alt="screen shot 2018-12-10 at 3 56 40 pm" src="https://user-images.githubusercontent.com/37100189/49769249-4c48d100-fc94-11e8-91bf-3e267b8753de.png">

As the eApp archival PDF is just a PDF version of what is displayed on-screen, this results in an archival PDF with `N-1` "Are there any additional co-owners..." questions with `Yes`, plus *1* final "Are there any additional co-owners..." answered `No`, where `N` is the number of co-owners.

This issue arises from NBIB comparing the eApp PDF with the eQIP PDF and flagging that discrepancy. The e-QIP archival PDF only displays the final "Are there any additional co-owners..." answered `No`. There is no incorrect data being sent, it is a presentation difference. 

Action:
As a user, I want a consistent experience for lists of items in eApp. Updating the 3 places co-owner data is collected (direct foreign interest, indirect foreign interest, foreign real estate) to be similar to how residence, relative, employment, etc. is collected (i.e., via an accordion control) improves usability. 

Having a consistent user experience for co-owner entry would also resolves the (very minor) duplicate question text issue, which is the origin of this ticket. It would result in a "Are there any additional co-owners..." question per co-owner list. This would satisfy NBIB's desire to not have any additional question text, unless by explicit policy exception.

**Comment by ryanhofdotgov** [comment]
@maryjohnston I think this should remain a genuine "Will Not Fix". This question is how the user specifies that they need another entry to fill out – it's a pervasive pattern across eQIP and eApp.

**Comment by ryanhofdotgov** [comment]
@joshmfranklin Here's a form edge case for you to be aware of: (accordion) lists in an accordions list. Similar thing in #1202.
