### ISSUE TITLE
Section 22 - Police Record :  The street address is displayed for the questions "Provide the name of the court"  in eAPP

### ISSUE THREAD

**Issue by maryjohnston** [18F/e-QIP-prototype#1205]
Edit:
Section 22 - Police Record :  The street address (and apt./suite/building/floor) is displayed for the questions "Provide the name of the court"  in eAPP, but e-QIP does not support this option. So remove these input fields from eApp.

Note there are 3 police record sub-sections in the form, offenses in past 7 years, offenses from all time, and domestic violence. 1 has been fixed, 2 have not:

1) Investigative and criminal history --> Police record --> Offenses --> Have any of the following happened? Yes. --> Were you arrested... Yes. --> As a result of this offense were you charged... Yes. 

This field set was already corrected in https://github.com/18F/e-QIP-prototype/issues/755

2) Investigative and criminal history --> Police record --> Additional offenses --> Other than those offenses already listed... Yes. 

<img width="400" alt="screen shot 2018-12-06 at 9 51 19 am" src="https://user-images.githubusercontent.com/37100189/49602163-a23c1280-f93c-11e8-989c-82022aceffa5.png">

3) Investigative and criminal history --> Police record --> Domestic violence

<img width="400" alt="screen shot 2018-12-10 at 4 19 59 pm" src="https://user-images.githubusercontent.com/37100189/49770039-849dde80-fc97-11e8-8616-5921795d673e.png">

See p. 168 and p.172 in the validation matrix, the previous work done in #755,  as well as screenshot below from SF-86:

*Additional offenses*
<img width="400" alt="screen shot 2018-12-06 at 9 38 00 am" src="https://user-images.githubusercontent.com/37100189/49602196-baac2d00-f93c-11e8-890d-d42299b848d1.png">

*Domestic violence*
<img width="400" alt="screen shot 2018-12-10 at 4 21 28 pm" src="https://user-images.githubusercontent.com/37100189/49770098-c62e8980-fc97-11e8-98d6-3cc7a0baff2f.png">

Note: I think primary work is to change `layout={Location.OFFENSE}` where appropriate, and update all the unit test files as well as complete-scenario files to reflect the current layout used by eApp.

**Comment by maryjohnston** [comment]
#1015

**Comment by maryjohnston** [comment]
e-QIP does not support this option, so remove from eApp, please.

**Comment by hursey013** [comment]
Fixed with #1255
