### ISSUE TITLE
Update project to use Snyk

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#121]
Gemnasium.com is shutting down, 18F handbook recommends Snyk for Go and Javascript:
https://before-you-ship.18f.gov/security/static-analysis/

Also see example in Forest Service project:
https://github.com/18F/fs-permit-platform/issues/166

**Comment by afeld** [comment]
* [x] Top-level `package.json`
* [x] `specs/package.json`
* [ ] [Golang dependencies](https://snyk.io/docs/snyk-for-golang)
    * This will require setting up [dep](https://golang.github.io/dep/)

**Comment by afeld** [comment]
Couldn't get Snyk to recognize the `Gopkg.lock` file under `api/`, so you might try reaching out to support, or moving it up to the top level of the repository.

**Comment by afeld** [comment]
Moving Golang work to it's own issue: #584
