### ISSUE TITLE
Add tests to load/export api/testdata/complete-scenarios

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1220]
Add integration tests to:
1) load JSON files in complete-scenarios using`load-scenario`
2) verify section review and final review does not detect any validation errors (fail if validation error)
3) export scenario back out using `form`
4) format export and compare it to input (fail if different)

Will catch issues where evolving front-end/back-end data structures do not match this known good data.

**Comment by macrael** [comment]
This seems like a very valuable test. We could even trigger the submit handler and check that the resultant xml is what we expect.

**Comment by ryanhofdotgov** [comment]
The backend units tests have the XML generation covered, as far as the test scenarios go. It regenerates XML from the json (using same code as submit function), then compares against the known-good XML test fixtures.

**Comment by macrael** [comment]
Where are those tests? how do they read in the JSON? Shouldn't they have failed if test1.json is not formatted correctly?

**Comment by ryanhofdotgov** [comment]
There here:
https://github.com/18F/e-QIP-prototype/blob/51d418ea9a1721d3e938d7db00e74c6635a7fae0/api/xml/xml_test.go#L256

I think the subtly is that this part of the test suite tests the XML generation, this particular element is optional, and the way the JSON gets loaded here is not the section-by-section mechanism used by `load-scenario`.
