### ISSUE TITLE
SF-85P Content Crosswalk and Tracker

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1227]
Need a cross-walk of the SF-85P to the SF-86 to understand the overlap, what's reusable, and the material differences between the content.

**Comment by joshmfranklin** [comment]
Link to tracking document: https://docs.google.com/spreadsheets/d/1nHJhOiQFH2k0QzQQ0HkrsllDWh6ED5yi4ytbioiLjNs/edit?usp=sharing

**Comment by joshmfranklin** [comment]
@michaelccata I think I've got the crosswalk for the 85P in a good place. Take a run through it when you have a chance and let me know what you think.

**Comment by michaelccata** [comment]
Looks good to me, thanks for putting that together!
