### ISSUE TITLE
Previous address disappears in all accordion elements

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1236]
**What did you do?**
The "use previous address" functionality resets after logging out of the application. The functionality does not reappear until you complete another "first" entry and then the "use previous address" option appears once you create the "second" entry. 

My layman's guess is that eApp doesn't count the old entries in that accordion toward the address book of "previous addresses" and thus doesn't _know_ any addresses until you complete one in the new session. Then, once it _knows_ an address in the current session it offers that for subsequent entries. 

Related to #1178 and #1173 (with respect to the issue where the "Outside the US" button is pre-selected) but this ticket has more context.

Here are steps to reproduce:

<br>

**Enter the first school**
<br>
<img width="710" alt="screen shot 2018-11-30 at 7 53 54 pm" src="https://user-images.githubusercontent.com/4422873/49322126-74894080-f4da-11e8-99a9-37928f5ceba4.png">
<br>

**Enter the second school**
<br>
<img width="713" alt="screen shot 2018-11-30 at 7 54 20 pm" src="https://user-images.githubusercontent.com/4422873/49322232-c1214b80-f4db-11e8-8d6c-82088308ecd4.png">
<br>

**^^^^ Hey! It asks me if I want to use a previous address!**
<br>
<br>

**Intended functionality observed**
<br>
<img width="647" alt="screen shot 2018-11-30 at 7 54 29 pm" src="https://user-images.githubusercontent.com/4422873/49322235-d1392b00-f4db-11e8-8d79-d471bc7d83be.png">
<br>

**Cool, got two entries that are valid**
<br>
<img width="723" alt="screen shot 2018-11-30 at 7 56 03 pm" src="https://user-images.githubusercontent.com/4422873/49322246-de561a00-f4db-11e8-95ad-379455b1d55f.png">
<br>

**Logs out, logs back in, goes to create a third school and no visible "use previous address" link is available**
<br>
<img width="706" alt="screen shot 2018-11-30 at 7 57 30 pm" src="https://user-images.githubusercontent.com/4422873/49322268-26753c80-f4dc-11e8-8ebc-9901d67a7bcc.png">
<br>

**What did you expect to see?**

The "use previous address" functionality should be presented for each address block in an accordion and persist across sessions. The "use previous address" functionality accessed through a link and pop-out should always appear regardless of when or what order the user is filling out the form. 

>We should explore this further in the future and consider a way of presenting addresses in a "book" or consulting some type of address search for employers or schools. **Referencing previously used addresses within the respective accordion section is an acceptable result in the interim.**

**Comment by christopherhuii** [comment]
This issue is a bit more involved. The Address Book is not being saved anywhere in the database, so there will need to be backend work needed to save validated addresses as well as the frontend work to ensure that data is loaded and displayed.

**Comment by suzubara** [comment]
IMO this issue could be addressed by populating the `AddressBook` state from saved form data on application load, but the tricky part there is knowing where those address objects are located. Since there's no real pattern to the form model right now we'd need to pull them out explicitly for each address object, but it might be a good temporary solution until we are able to make some updates to the model.
