### ISSUE TITLE
Confirm alignment and styling of accordion

### ISSUE THREAD

**Issue by christopherhuii** [18F/e-QIP-prototype#1239]
**What did you do?**

Load Test Case 5

Or

Go to "Your History" and add an employment entry with company name and employment dates.

**What did you expect to see?**

I expect to see the date to be aligned right because that's how it originally looked.

**What did you see instead?**

![screen shot 2018-12-03 at 2 10 48 pm](https://user-images.githubusercontent.com/8367504/49407073-41c68e80-f70c-11e8-8a34-a845b08edf02.png)

**Additional Information**

*Please verify all fixes against IE11*

This issue might not result in any work. #1013 adjusted the styling in the accordion, which made accordion display information a little differently. One of the cases is that the date is not aligned right, but instead displays right after the company name. If the company name overflows, the date moves onto a second line.

If the screenshot above is acceptable, we might be able to close this issue as is.

**Comment by line47** [comment]
Here are some options for the dates 👀 with both really long text and shorter text. I feel the aligned left version looks better when the name is long and needs to wrap to a second line. 

**Aligned right**
![screen shot 2018-12-04 at 8 40 50 am](https://user-images.githubusercontent.com/1449852/49445676-7421cb80-f7a0-11e8-96ea-088718f4d1bd.png)

![screen shot 2018-12-04 at 8 40 11 am](https://user-images.githubusercontent.com/1449852/49445683-7a17ac80-f7a0-11e8-8d79-ee417224459e.png)


---


**Aligned left**
![screen shot 2018-12-04 at 8 40 59 am](https://user-images.githubusercontent.com/1449852/49445718-8dc31300-f7a0-11e8-9bfa-1b8ebfd36814.png)

![screen shot 2018-12-04 at 8 40 25 am](https://user-images.githubusercontent.com/1449852/49445730-99aed500-f7a0-11e8-9dc7-03d3118d35b7.png)

**Comment by line47** [comment]
CC @joshmfranklin ☝️

**Comment by joshmfranklin** [comment]
I think we should be consistent and always align the dates to the right of the accordion header. My suggestion would be to add an ellipsis after a certain character length so that it doesn't interfere with the dates.

**Comment by line47** [comment]
Thanks @joshmfranklin
