### ISSUE TITLE
Define project and code structure for SF-85

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1242]
How will we adjust webpack and structure the codebase for the whole eApp?
How do we ensure there isn't too much disruption for SF-86?

**Comment by ryanhofdotgov** [comment]
Aidan had some notes here: https://github.com/18F/e-QIP-prototype/issues/695

**Comment by michaelccata** [comment]
That sounds like a plan @christopherhuii

**Comment by gidjin** [comment]
Here is a link to the google doc that outlines our recommended plan. @ryanhofdotgov We'd like your input on this proposal for how to handle SF-85 for https://docs.google.com/document/d/1ZWOP-BSg-RYSkyuwSLoZKhM4roDR2IWCh0PPO_LDADc I've shared the document with the rest of the Truss team too in case I've missed anything.
