### ISSUE TITLE
Build full "Dummy" section of SF-85 form for testing new components

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1244]
Build out a full "dummy" section of the SF-85 in order to do some preliminary user testing of the newly designed form fields with users. 

Sections to build:
- [x] Information about you
- [x] Your history
- [x] Citizenship
- [x] Military hisory

Testing:
- [x] Check against tracking document/content guide for language
- [x] IE testing

**Comment by joshmfranklin** [comment]
@michaelccata before I close this one, If you could take a quick spin through it and see if there are any glaring pieces of feedback with a focus on what we need for user testing of the first two sections `information about you` and `your history` that would be great!

**Comment by michaelccata** [comment]
Sounds good.

Some thoughts for focus:

- Save button dynamics 
- Address block
- Your identifying information (would be interested in whether the hair/eye color is easy to pick, the buttons on the last form were big, but I did like how they injected some fun into the form. Users liked that feature last go around.)

And then in general - we don't have validation right now, so we could use that to our advantage and explore what they _expect_ to get validated.
