### ISSUE TITLE
Modals - User can tab behind the instructions/agreement - focus

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#125]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2926  

Users can tab through the content behind the instructions/agreement 

Seen on Chrome, Edge, IE 11

**Comment by bpdesigns** [comment]
validated 9/25/18
