### ISSUE TITLE
Address field set defaults to "Outside of US"

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1266]
## Where are you in the form?

**Section:**
Relationships --> Relatives
**Question:**
Provide your relative's current address,  Provide your relative's place of birth
**Field:**
Was this person born in the United States of America?, This address is
**Component (for example address block):**
Address block

## What did you see?
- [ ] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [X] Other (explain below)

Sign in to new/fresh form. Go to relatives section. Click Mother, Click No to "deceased?". Click Save. Logout, log back in. Go back to Mother entry. 

Address blocks for birth and current address default to "Outside US".

<img width="400" alt="screen shot 2018-12-14 at 9 40 00 am" src="https://user-images.githubusercontent.com/37100189/50018601-bdce9b00-ff84-11e8-911d-ae0d38d57bfc.png">

<img width="400" alt="screen shot 2018-12-14 at 9 40 05 am" src="https://user-images.githubusercontent.com/37100189/50018599-bb6c4100-ff84-11e8-9712-fadfe8ba8709.png">

## What did you expect to see?

Default to "In US", which was displayed on the original form creation/sign-in.

## Is this error limited to just this field or others in the form?

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

Probably cross-form, but I don't know.

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [X] MacOS

**Browser**
- [X] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by joshmfranklin** [comment]
@michaelccata this seems to be coming up quite a bit during user testing sessions. And it is appearing in multiple sections across the form.

**Comment by michaelccata** [comment]
"Sometimes things get stored as an object, sometimes as a string" Notes from @hursey013 

@el-mapache wrote a something that can help parse what value is stored.
