### ISSUE TITLE
Sort residence entries chronologically

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#1281]
We are currently sorting employment entries chronologically and I think doing the same for `Residences` could be beneficial. We've moved to adding the gap warning message to the bottom of the accordion list, so trying to identify where the gap is without the items being sorted chronologically could be extremely difficult.

**Comment by joshmfranklin** [comment]
+1 to this, i just went through that scenario and it is very hard to decipher residence gaps without having them in chronological order.
