### ISSUE TITLE
User testing scripts and research plan

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1283]
- Create scripts for usertesting.com, in-person interviews.
 - Decide which form we will use for testing (dummy or real)

@michaelccata needs to share contacts.

**Comment by joshmfranklin** [comment]
See link below for user testing script for UT sessions scheduled for 01/04/2019 - 01/11/2019
https://docs.google.com/document/d/1RVGhb7Ux8dTwxRrtVoFGj_YQpm-ro4bPKDZ_xmRIX38/edit?usp=sharing

**Comment by joshmfranklin** [comment]
@michaelccata let me know if you have any further feedback on the UT script otherwise I think this should be good to close.
