### ISSUE TITLE
Date ranges are validating too early

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1286]
## Where are you in the form?

**Section:**

Any date range in the application

**Question:**

I've mostly been testing in the `other names used` section, `dates used` question

**Field:**

**Component (for example address block):**

Date range component

## What did you see?

When I input a date into the `from date` field the entire component starts validating when I enter the year. This happens before I enter anything into the `to date`

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

## What did you expect to see?

I expected to see that the date range doesn't get validated until both the `from date` and `to date` are entered.

## Is this error limited to just this field or others in the form?

This seems to be happening in any date range.

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

![screen shot 2018-12-19 at 1 18 16 pm](https://user-images.githubusercontent.com/4196834/50239584-99156180-0390-11e9-9f6e-be757726dc2d.png)

**Comment by ryanhofdotgov** [comment]
@joshmfranklin I think during your demo of this bug, I also saw a placeholder error message (i.e., an error that did not have an associated localized text string?)

**Comment by joshmfranklin** [comment]
@ryanhofdotgov yeah that seems like it could be a different issue. That error is triggered if you enter a day within a month that doesn't exist. 

![screen shot 2018-12-19 at 1 50 49 pm](https://user-images.githubusercontent.com/4196834/50241325-32df0d80-0395-11e9-9838-11768c9c7b8c.png)
