### ISSUE TITLE
Mental health - diagnosis - fields not saving - Data persistence 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#129]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2918  

Fields that are not being saved:
**Health care professional info**
- [ ] Name
- [ ] Phone
- [ ] Address

**Agency**
- [ ] Name
- [ ] Phone
- [ ] Address

![screen shot 2018-04-27 at 11 59 14 am](https://user-images.githubusercontent.com/19935974/39372451-6b0a3370-4a12-11e8-97cb-2bc28830b373.jpg)

**Comment by bpdesigns** [comment]
Persists when I test on Mac in Chrome

**Comment by ryanhofdotgov** [comment]
No evidence of this still being an issue – the test cases that cover these sections wouldn't have been able to be created otherwise.
