### ISSUE TITLE
Phantom error on education items (test case 7)

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#1293]
Steps to reproduce:
- Load test case 7
- Review education section, including final review of History section and see that there are no validation errors
- Run the final review and observe an error flagged in the in `Your history > Where you went to school`

I did some preliminary research on this. It's tied to the ReferenceName component and the `hideMiddleName` prop. `hideMiddleName` successfully hides the middle name field, and works as expected, however because of the way the validator works, the values for `ReferenceName` are pulled in from the Redux store where `hideMiddleName` is not  present. This causes the validator to flag `ReferenceName` as invalid because it appears it is missing a middle name.

**Comment by joshmfranklin** [comment]
This also happens on the Employment activities subsection.
