### ISSUE TITLE
Relationships - marital - location of marriage not saving - Data Persistence

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#130]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2916  

- [ ] Marriage location not saving

![screen shot 2018-04-27 at 10 20 10 am](https://user-images.githubusercontent.com/19935974/39367514-f02c60ea-4a04-11e8-8e43-56598e5f364d.jpg)

**Comment by bpdesigns** [comment]
The location of Marriage seems to be persisting now, but "Provide this person's country(ies) of citizenship" is not persisting

**Comment by ryanhofdotgov** [comment]
When I've read about these types of issues in the project's history it is usually because of a variable typo somewhere; e.g., part of the form calls it 'foobar' and some other layer calls it 'foo'

**Comment by ryanhofdotgov** [comment]
What you've been doing so far has been great – reviewing issues of all kinds and verifying they are still reproducible. Persistence errors in particular are important (if there are still others), since they could prevent successful completion of form.

**Comment by afeld** [comment]
We can/should also make automated tests for this: fill out a section, refresh, and check that the data displayed is the same. Shouldn't be _tooo_ hard.

**Comment by ryanhofdotgov** [comment]
Yup, totally agree – here's an outstanding related ticket https://github.com/18F/e-QIP-prototype/issues/144 I asked TrueTandem to work on this before they got off contract, but they ran out of time. Once we finish the current iteration of getting the spec tests working, we should revisit.

**Comment by hursey013** [comment]
It appears that `Provide the location` of the marriage and `Provide this person's country(ies) of citizenship` are persisting when testing the app locally - can anyone else reproduce this persistence issue?

**Comment by ryanhofdotgov** [comment]
Yup, still happens for me unfortunately. Steps to reproduce, using Chrome's incognito window:

1) Sign in, expand Relationships, expand Marital & relationship status, click on Marital.
2) Click on "Currently in a civil marriage"
3) Scroll to Provide location. Click on Yes, in United States. Fill out City, State, County. 
4) Scroll down to bottom of page, click on Save, even if it says it was already just Saved.
5) Log out, close window.
6) In new incognito window, sign in again, go to "Provide location" – no data appears in fields.
