### ISSUE TITLE
Save button - animation and timer

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#131]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2915  

- [ ] The saving animation is not working on the save button
- [ ] Looks like the timer is off, after a save it jumped back to 14 min ago

![screen shot 2018-04-27 at 10 21 05 am](https://user-images.githubusercontent.com/19935974/39367430-b3acc36c-4a04-11e8-9755-f06042f5ca54.jpg)

**Comment by bpdesigns** [comment]
working fine now
