### ISSUE TITLE
Choosing "present" on date counseling/treatment ended shows incorrect error message

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1310]
## Where are you in the form?

**Section:**
Substance abuse > Use of alcohol > additional instances

**Question:**
Provide the date counseling or treatment ended

**Field:**

**Component (for example address block):**
Single date block month/day/year or present

## What did you see?

Choosing "present" and then continuing to the review section shows an error for the field though it should be a valid response. The error message it shows is also not human readable.

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

Steps to reproduce: 
- Select yes on the additional instances subsection
- Fill out the form and choose "present" for the question "Provide the date counseling or treatment ended"
- Continue to the review section
- See that an validation error is shown for that field even though "present" is selected

## What did you expect to see?

I expected to be able to select present without a validation error.

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

![screen shot 2018-12-28 at 1 31 24 pm](https://user-images.githubusercontent.com/4196834/50524661-fe5e0680-0aa4-11e9-8940-f835e2a5bca1.png)

**Comment by gidjin** [comment]
This issue appears fixed with #1316 by pull request #1333
