### ISSUE TITLE
Existing conditions subsection does not show on Psychological and emotional health review section

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1312]
## Where are you in the form?

**Section:**
Psychological and emotional health > Reveiw

**Question:**

**Field:**

**Component (for example address block):**

## What did you see?

Existing conditions subsection is now shown at all on the Review page.

- [ ] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [x] Other (explain below)

Steps to reproduce: 
- Navigate to the review page under Psychological and emotional health
- See that the "Existing conditions" subsection is now shown on the page

## What did you expect to see?

I expected to see the "Existing conditions" section on the review page.

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by hursey013** [comment]
Fixed with https://github.com/18F/e-QIP-prototype/pull/1334
