### ISSUE TITLE
Error messages for all dates are broken

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1316]
## Where are you in the form?

**Section:**  All Sections

**Question:** All date questions

**Field:** Date

**Component (for example address block):** Date Fields (Both single date and date range)

## What did you see?

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

1. Enter a date that is incorrect - outside of date range (for example before birth or before the end date).
2. eApp provides the following error messages:

<img width="587" alt="screen shot 2019-01-02 at 4 59 14 pm" src="https://user-images.githubusercontent.com/4422873/50614813-145a3580-0eb0-11e9-8536-02585fa35f91.png">
<img width="620" alt="screen shot 2019-01-02 at 4 55 58 pm" src="https://user-images.githubusercontent.com/4422873/50614814-145a3580-0eb0-11e9-92d1-ecc7cc2673ea.png">
<img width="649" alt="screen shot 2019-01-02 at 4 55 28 pm" src="https://user-images.githubusercontent.com/4422873/50614815-145a3580-0eb0-11e9-85db-9da849644e50.png">
<img width="652" alt="screen shot 2019-01-02 at 4 55 21 pm" src="https://user-images.githubusercontent.com/4422873/50614816-145a3580-0eb0-11e9-8157-ae2c69b623fa.png">
<img width="616" alt="screen shot 2019-01-02 at 4 54 27 pm" src="https://user-images.githubusercontent.com/4422873/50614817-145a3580-0eb0-11e9-90fc-f04923a9468a.png">

## What did you expect to see?

Expected to see the error language that we have currently.

## Is this error limited to just this field or others in the form?

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by gidjin** [comment]
In the review of information about you under _Place of birth_ a similar issue happens.
<img width="463" alt="screen shot 2019-01-02 at 5 01 05 pm" src="https://user-images.githubusercontent.com/940173/50619792-3f448980-0eb0-11e9-8fb1-ed27e8b6010a.png">
