### ISSUE TITLE
Move U.S. Passport subsection information to Citizenship section

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1327]
As an applicant
I want to be able to fill out my U.S. Passport Information when I am in the Citizenship section
Because it makes the most amount of sense while answering questions about my citizenship

Given I am in the Citizenship section of any form (85, 85P, 86)
When I complete the introduction subsection and click next
I should be taken to the U.S. Passport Information subsection

Note: This helps keep things consistent between form. Currently the U.S. Passport Information subsection is within the Foreign associates section, in the SF85 no other Foreign association subsections are present to U.S. Passport Information would be the only one. Moving it to Citizenship in all forms makes sense given the other subsections and keeps things consistent between forms. 

The new order of the Citizenship section would be:
- Introduction
- U.S. Passport information
- Citizenship status
- Dual/multiple citizenship
- Foreign passports
- Review

**Comment by christopherhuii** [comment]
@joshmfranklin 

> Given I am in the Citizenship section of any form (85, 85P, 86)
> When I complete the Dual/multiple citizenship subsection and click next
> I should be taken to the U.S. Passport Information subsection

> The new order of the Citizenship section would be:
>
> - Introduction
> - U.S. Passport information
> - Citizenship status
> - Dual/multiple citizenship
> - Foreign passports
> - Review

I'm getting confused by those two statements. Which is the correct order?

**Comment by joshmfranklin** [comment]
@christopherhuii Whoops sorry, I updated the bullet points but not the paragraph above
The order should be same as bullet points:
Introduction
U.S. Passport information
Citizenship status
Dual/multiple citizenship
Foreign passports
Review

**Comment by ryanhofdotgov** [comment]
Some notes from our standup today:

Moving this question to a different section in the most direct manner has quite a long tail of activities:
* update backend JSON structures
* update backend complete test scenarios
* update XML code generation
* re-submit/revalidate against e-QIP
* address issue when old data from previous eApp is loaded into revised eApp frontend/backend

Suz/Chris/and I decided a couple of things:
1. It was preferable to move the question in the UI, but in a way that does not alter backend/JSON format. This in and of itself, would be treading new ground, as historically the UI and JSON serialization format are very tightly coupled.
1. Regardless of approach, this work has too much risk to incorporate into the 1.0.14 sprint/release, as we want that to be a very stable release, resolving most/all the major issues discovered in pre-prod testing rounds.
