### ISSUE TITLE
Applicant should not have to choose day, night, both of phone numbers for person who knows you at an address

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1331]
As an applicant
I don't want to have to choose the best time to call for a persons phone number who knows me at an address
Because it causes confusion with the Evening, Daytime, and Cell/mobile phone sections

Given I am filling out an address for a place that I've lived
When I enter an address within the last 3 years
Then I should see a section to fill out a person who knows me at that address
And I should have to choose `day only`, `night only` or `both` for their phone numbers

Note: this came up as part of user testing. users are confused why they have to choose a time to use the phone number when the phone number is already designated as an evening, daytime, mobile number. It is also not part of the SF85,86 PDF to ask for day or night phone for these numbers.

![screen_shot_2019-01-08_at_2_54_58_pm](https://user-images.githubusercontent.com/4196834/50855518-0c8a0d80-1356-11e9-86f8-c208b055e398.png)

**Comment by ryanhofdotgov** [comment]
As this work gets picked up, need to audit the app and identify the specific questions that have the redundant time of day radio.
