### ISSUE TITLE
Substance Abuse Counseling Date Field Validation Bugs

### ISSUE THREAD

**Issue by gidjin** [18F/e-QIP-prototype#1338]
## Where are you in the form?

**Section:**
Substance abuse > Use of alcohol > additional instances

**Question:**
Provide the date counseling or treatment began

**Field:**

**Component (for example address block):**
Date Control block

## What did you see?

- [X] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

<img width="564" alt="screen shot 2019-01-09 at 5 00 08 pm" src="https://user-images.githubusercontent.com/940173/50992232-68c26e00-14cb-11e9-96e7-e794217e10fe.png">

<img width="469" alt="screen shot 2019-01-10 at 11 37 10 am" src="https://user-images.githubusercontent.com/940173/50992489-3107f600-14cc-11e9-95b0-31f9cdb2d0ba.png">

## What did you expect to see?

The birthday entered is before the date entered
The date entered is not in the future

- 1/1/1999 I expected there to be no error but a green valid check mark
- 1/1/1922 I did not expect the error "The date can't be in the future"

## Is this error limited to just this field or others in the form?

I haven't checked the entire form but this seems limited to this one.

- [X] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [X] MacOS

**Browser**
- [X] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**
Latest Development git hash 532416ad969fa0ae4ab9fd873a4ef17c588da6d4

**Comment by michaelccata** [comment]
@gidjin did you finish this by the end of last sprint? 

If not, I thought you were going to move it into this coming sprint. Or is this related to #1339?

**Comment by gidjin** [comment]
Sorry @michaelccata, this was merged into develop on 1/17 and should have been closed. I'll go ahead and close it now.
