### ISSUE TITLE
Substance abuse counseling date present not functioning

### ISSUE THREAD

**Issue by gidjin** [18F/e-QIP-prototype#1339]
## Where are you in the form?

**Section:**
Substance abuse > Use of alcohol > additional instances

**Question:**
Provide the date counseling or treatment **ended**

**Field:**

**Component (for example address block):**
Date Control block

## What did you see?

- [X] Validation error
- [X] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

Select present when filling out the section and observe the accordion header
<img width="833" alt="screen shot 2019-01-09 at 5 00 39 pm" src="https://user-images.githubusercontent.com/940173/50993011-7b3da700-14cd-11e9-8fe5-679b3d64f5db.png">

If you reload the page login again and find the field you will see that present is no longer selected and month is off by 1
<img width="538" alt="screen shot 2019-01-09 at 5 00 21 pm" src="https://user-images.githubusercontent.com/940173/50993095-a45e3780-14cd-11e9-92c3-61e33a23c07c.png">

## What did you expect to see?

I expected the current month to be shown in the header (in my case January) and I expected present to still be selected when returning to the form.

## Is this error limited to just this field or others in the form?

I haven't tested the entire form but I believe it is localized too

- [X] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [X] MacOS

**Browser**
- [X] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**
Latest Development git hash 532416ad969fa0ae4ab9fd873a4ef17c588da6d4

**Comment by hursey013** [comment]
Based on previous discussion, this issue should also encompass updating the component to use `DateRange` vs two `DateControls`: https://github.com/18F/e-QIP-prototype/pull/1351#issuecomment-455245682

**Comment by michaelccata** [comment]
"We should just just use the date range component instead of two separate dates." - notes from backlog review. 

May need to update how we sent to API as well. @hursey013 can help with that.
