### ISSUE TITLE
substance use - counseling - missing error message

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#134]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2908  

- [ ] when present is selected on the date there is an error

![screen shot 2018-04-26 at 3 39 11 pm](https://user-images.githubusercontent.com/19935974/39328078-18655d8e-4968-11e8-86d0-a0433b16acce.jpg)

**Comment by bpdesigns** [comment]
no seeing this
