### ISSUE TITLE
[SF-85] Update Substance Use section components to match SF-85

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1348]
- [x] Update Locales
- [x] Confirm/Update form fields within each section (see [tracking document](https://docs.google.com/spreadsheets/d/1nHJhOiQFH2k0QzQQ0HkrsllDWh6ED5yi4ytbioiLjNs/edit?usp=sharing))
- [x] Update left navigation to match the correct subsections
- [x] Ensure the "back" and "next" buttons navigate to the correct sections

Note: 
Subsections **NOT** part of SF-85: `Security clearance position`, `Public safety position`
Sections **NOT** part of SF-85: `Use of alcohol`

**Comment by joshmfranklin** [comment]
@christopherhuii I just realized that we are going to have to make the `introduction` titles dynamic as well. `Substance use` in the 86 is section 8 but in the 85 is section 7.
