### ISSUE TITLE
Taxes - provide amount - placeholder text missing

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#135]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2907  

- [ ] placeholder text missing

![screen shot 2018-04-26 at 3 18 21 pm](https://user-images.githubusercontent.com/19935974/39327145-258e5856-4965-11e8-8b12-d7c0b825a585.jpg)

**Comment by bpdesigns** [comment]
not seeing this
