### ISSUE TITLE
Style issue with checkboxes and radios on Relatives

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#1354]
## Where are you in the form?

**Section:**
Relatives

## What did you see?

- [ ] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [x] Other (explain below)

Styling issue:
![screen shot 2019-01-16 at 3 57 49 pm](https://user-images.githubusercontent.com/1178494/51330867-6b324400-1a46-11e9-9f81-768ebdd83f79.png)

## What did you expect to see?
Properly aligned checkboxes/radios, non-overlapping text

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

Appears to only apply to this particular section.

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by joshmfranklin** [comment]
@hursey013 whoops must have missed a set of checkboxes. Ill fix this one up quick.
