### ISSUE TITLE
Cohabitant - accordion item showing error

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#136]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2906  

- [ ] Cohabitant accordion item is showing an error on review screen when there are no errors

![screen shot 2018-04-26 at 2 07 40 pm](https://user-images.githubusercontent.com/19935974/39323690-49109fb4-495b-11e8-9127-49c6dce5972b.jpg)

**Comment by bpdesigns** [comment]
not seeing this
