### ISSUE TITLE
[SF-85] Update introduction/instructions component to match SF-85

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1360]
- [ ] Review copy for any necessary changes in the instructions preceding the form

**Comment by christopherhuii** [comment]
@joshmfranklin @michaelccata Do we have the SF85 text for the disclaimer and/or instructions before the actual form? I'm probably going to get to this before the end of the sprint.

**Comment by joshmfranklin** [comment]
@christopherhuii the disclaimer/instructions are included in the content guide. If I have some time earlier this week I can rip it out and put it in a google doc for easier reference. 

https://drive.google.com/file/d/1V2UB64Q0Cj_uRBkNqUiRX4XUOSInX_ie/view?usp=sharing
