### ISSUE TITLE
Marital -  date of separation bug

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#137]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2905  

Error being thrown in marital section when there is no DOB error

![screen shot 2018-04-26 at 11 59 33 am](https://user-images.githubusercontent.com/19935974/39317383-77250564-4949-11e8-9a9f-b98573f38ec8.jpg)
![screen shot 2018-04-26 at 11 59 27 am](https://user-images.githubusercontent.com/19935974/39317387-7814fa24-4949-11e8-88a8-dadbdd3ef905.jpg)

**Comment by bpdesigns** [comment]
not seeing this
