### ISSUE TITLE
OPM Text updates

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1375]
Text changes to make to both 86 and 85 based on OPM feedback:

## Your History
- [x] **Section 11, Where You Have Lived:**  Move instructions prior to date entries to initial instructions.  Imperative information for address entries:  You are not required to list temporary locations of less than 90 days that did not serve as your permanent or mailing address.

- [x] **Section 12, Where You Went to School:**  ADD:  For assistance determining the school address, refer tohttp://ope.ed.gov/accreditation/search.aspx

- [x] **Section 12, Where You Went to School:**  CHANGE FROM:  Select the most appropriate code to describe your school  Select the most appropriate code to describe your school  CHANGE TO:  Select the most appropriate box to describe your school

- [x] **Section 12, Where You Went to School:**  CHANGE FROM:  Add a person that knows you  CHANGE TO:  List a person who can verify that you attended this school

- [x] **Section 12, Where You Went to School:**  CHANGE FROM:  For any school in the last 3 years, provide a person who knew you at the address, and who preferably still lives in that area. Do not list people who knew you well for education completely outside this 3-year period, and do not list your spouse, cohabitant or other relatives.  CHANGE TO:  For schools you attended in the last 3 years, list a person who knew you at the school (instructor, student, etc.).  Do not list people for education periods completed more than 3 years ago.  For correspondence/distance/extension/online schools, list someone who knew you while you received this education.

- [x] **Section 13, Employment Activities, Employment & Unemployment Record:**  Self Employment—CHANGE FROM:  Provide this person's street address.  CHANGE TO:  Provide the address of this verifier.  CHANGE FROM:  The address of your contact during this time period.  CHANGE TO:  The address of your verifier.

- [x] **Section 13, Employment Activities, Employment & Unemployment Record:**   UnEmployment—CHANGE FROM:  Provide this person's street address.  CHANGE TO:  Provide the address of this verifier.  CHANGE FROM:  The address of your contact during this time period.  CHANGE TO:  The address of your verifier.

## Citizenship
- [x] **Section 9, Citizenship, Naturalized:**  CHANGE FROM:  Provide your U.S. alien registration number on Certificate of Naturalization USCIS, CIS, or INS registration, I-551, I-766  CHANGE TO:  Provide your U.S. alien registration number on Certificate of **Naturalization-utilize** USCIS, CIS, or INS registration, I-551, I-766

- [x] **Section 9, Citizenship, Not a U.S. Citizen:**  CHANGE FROM:  Provide your countr(ies) of citizenship  CHANGE TO:  Provide your **country(ies)** of citizenship  LIKE:  The country multiple entries feature

## Military History
- [x] **Section 14, Selective Service Record:**  CHANGE FROM:  https://www.sss.gov/Registration/Check-a-Registration/Verification-Form  CHANGE TO:  www.sss.gov. **Note:** only change link text but leave actual link URL the same.

- [x] **Section 15, Military History: Description of final outcome:**  CHANGE FROM:  Such as found guilty, found not guilty, reduction in rank, imprisonment, etc   CHANGE TO:  Such as found guilty, found not guilty, **fine**, reduction in rank, imprisonment, etc

**Comment by joshmfranklin** [comment]
This is a link to the document where OPM copy change requests are being tracked: https://docs.google.com/document/d/1fEBaf5L9S5DrZcgIL4WgDA_Hv_lykFYdooSkoAXgeJ4/edit#heading=h.r5x7w9gflddg

**Comment by joshmfranklin** [comment]
The text changes for the reference persons address are more complicated than it seems. These locales are shared across all three places that references are asked for, `residence`, `employment`, and `education`. Changing it will change the language for all three locations. 

It makes sense on the `employment` page to say "Provide the address of this verifier" but it does not make sense on the `residence` or `education` page because that person is never referred to as a verifier on those sections.

**Comment by ryanhofdotgov** [comment]
@joshmfranklin I haven't looked at this particular code set, but in general you can alter the locale text used by an instance by using the `prefix` property, which then tells the component to look at a different, customized set of locale strings.
