### ISSUE TITLE
Support previous data schemas in new version of code

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#1380]
Occasionally, a bug fix will require changes to the JSON serialization format.  Sometimes a change to the format for version X.Y.N of eApp will not be backwards compatible with X.Y.N-1. This causes problems when a user signs back into a partial application using eApp X.Y.N that was started under X.Y.N-1.

For example, see this Slack thread:
https://gsa-tts.slack.com/archives/CD1HQH1EY/p1548346053388600?thread_ts=1548345558.388200&cid=CD1HQH1EY

Symptoms of this issue include:
* browser freezing on a sub-section page load
* mutually exclusive options being selected
* otherwise bad data being shown or unusual exceptions in JavaScript console.

Develop strategies, policies, processes, etc. to prevent this from happening in the future.

**Comment by michaelccata** [comment]
> Develop strategies, policies, processes, etc. to prevent this from happening in the future.

^ including new forms

**Comment by michaelccata** [comment]
NBIS1TEST-9
