### ISSUE TITLE
Accessibility - required fields

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#139]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2892  

- [ ] Need to announce all required fields (asterisks) throughout form - alt text stating "Required"

Context from Audit:
![screen shot 2018-04-23 at 1 45 52 pm](https://user-images.githubusercontent.com/19935974/39143694-a5cf8f78-46fc-11e8-931e-715e00bab2a0.jpg)

**Comment by bpdesigns** [comment]
Closing this issue Re: #543 - We're going with removing all asterisks
