### ISSUE TITLE
Your history accordion item numbers

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#140]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2889  

Accordion item numbers are missing for:

- [x] Where you have lived
- [x] Employment activites
- [x] Where you went to school

![screen shot 2018-04-23 at 10 58 03 am](https://user-images.githubusercontent.com/19935974/39134758-5c1100fe-46e5-11e8-984c-5b92416a1615.jpg)
![screen shot 2018-04-23 at 10 58 07 am](https://user-images.githubusercontent.com/19935974/39134760-5c480f5e-46e5-11e8-9e19-dfce2ab5bd79.jpg)
![screen shot 2018-04-23 at 10 58 11 am](https://user-images.githubusercontent.com/19935974/39134761-5c555f88-46e5-11e8-9715-306985adcba6.jpg)

**Comment by afeld** [comment]
Is there an example/mockup of what these should look like? cc @bpdesigns

**Comment by afeld** [comment]
Nevermind, found a screenshot: https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2747#issuecomment-381144335
