### ISSUE TITLE
Update styles for Print PDF

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#141]
From e-QIP-prototype-truetandem created by [floresj](https://github.com/floresj) : ryanhofdotgov/e-QIP-prototype-truetandem#2886  

Styles look shifted.

![image](https://user-images.githubusercontent.com/5938731/39007619-1b040d7c-43bb-11e8-9eb7-e52544f663d9.png)

**Comment by line47** [comment]
Is this for printing the page during any part of the application process or a specific print function?

**Comment by ryanhofdotgov** [comment]
Just the specific "Save/Print" function that is on the last page after you submit your application. It relies on the host operating system/browser to be able to generate a PDF from a print job. 

I would look somewhere around the Package component for the related CSS. The button creates a stylized HTML view where all the sections of the web app are printed in order one after the other. 

While this issue is to just see if we can get the style fixed in the resulting print job/view, this larger feature will need to get revisited because while Windows 10 and macOS and Chrome (I believe) have print to PDF built in, it is not a standard ability across all the platforms/browsers we want to support.
