### ISSUE TITLE
Social Security Number section does not validate in nav until leaving and coming back

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#1417]
## Where are you in the form?

**Section:**
Information about you > Social Security number

**Question:**
Social Security Number

**Field:**
Sidenav validation

**Component (for example address block):**
Sidenav

## What did you see?

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

Steps to reproduce: 
1. fill out all of the SSN details
2. see that no green dot appears 
3. navigate to another section and then navigate back to the SSN section
4. See that the green validation dot now appears

## What did you expect to see?

I expected that one the SSN and confirmation of SSN were properly filled out that the section could show a green dot in the sidenav.

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by gidjin** [comment]
This may be the same or related to #1442
