### ISSUE TITLE
Scrolling quickly causes page to bounce/vibrate

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#142]
From e-QIP-prototype-truetandem created by [ryanhofdotgov](https://github.com/ryanhofdotgov) : ryanhofdotgov/e-QIP-prototype-truetandem#2884  

Under 0.5.1 (Sprint 35), latest Chrome, macOS. See attached quicktime video.

On one page, used the scroll wheel on my mouse to quickly get to bottom of page to click next. Once I got to the bottom, the browser would continuously show the bouncing/vibration effect depicted in the video. Scrolling up stopped it, scrolling down quickly again triggered it.

[scrolling.mov.zip](https://github.com/truetandem/e-QIP-prototype/files/1928968/scrolling.mov.zip)

**Comment by bpdesigns** [comment]
since we no longer have the independent scroll bars this isn't an issue
