### ISSUE TITLE
Make use of react nested routes instead of SectionViews component

### ISSUE THREAD

**Issue by gidjin** [18F/e-QIP-prototype#1422]
SectionViews component handles common rendering and routing features, the scope of this story is to replace the routing portion only with react nested routes. Basically SectionViews component loops through the section components and then returns the specific component, but this can easily be handled by react nested routes.

This task should be time boxed to 2 days for exploration, and if possible we can continue the refactor, but if not we can close the time box and regroup.

Note this work will befit the SF-85 work as it will be easier to make our navigation more declarative after this refactor.

**Comment by suzubara** [comment]
https://github.com/18F/e-QIP-prototype/pull/1431 handles this for the Identification section. Now that the work is known, I recommend making followup stories for rolling out the changes to the rest of the sections.
