### ISSUE TITLE
Create form data structure constants

### ISSUE THREAD

**Issue by suzubara** [18F/e-QIP-prototype#1423]
Add constants and/or config files that can act as a single source of truth for form data structure and any requirements that differ between form types.

**Comment by christopherhuii** [comment]
Sorry in advance. I have a _mega_ [PR](https://github.com/18F/e-QIP-prototype/pull/1435) that might include what's described in this issue. 

Please see:
`src/config/form/sf85.js`
`src/config/form/sf86.js`

These config files aren't perfect, but it's probably something we can continue to shape.
