### ISSUE TITLE
Name unknown - suffix confusion

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1433]
## Where are you in the form?

**Section:** Foreign Associations

**Question:** Provide the full name of the foreign national, if known

**Field:** Full name

**Component (for example address block):** Full name + suffix

## What did you see?

- [ ] Validation error
- [ ] Data not saving
- [x] Language or content issue
- [ ] Other (explain below)

<img width="733" alt="screen shot 2019-02-12 at 4 17 10 pm" src="https://user-images.githubusercontent.com/4422873/52668621-07365a80-2ee2-11e9-8ee7-d4bec3e73990.png">

It's not clear that the "I don't know" is in regard to the contact's full or real name -- not just the suffix.

## What did you expect to see?

Maybe we should think about where we're putting the "I don't know" button for cases where you don't need to provide a full name.

## Is this error limited to just this field or others in the form?

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by joshmfranklin** [comment]
## Option 1 - move the `I don't know` away from the suffix dropdown
This will hopefully make it less associated with just the suffix dropdown and more related to the entire name block
![option 1 - full name i don t know](https://user-images.githubusercontent.com/4196834/52725899-166be580-2f80-11e9-84e1-088c32103b4e.png)

## Option 2 - move `I don't know` away from the suffix dropdown and adjust text
Adding some clarifying text to the checkbox would give more clarity to what it is intended for. This does stray away from the `I don't know` checkboxes all having the same text but it would make it very clear.
![option 2 - full name i don t know](https://user-images.githubusercontent.com/4196834/52726057-664aac80-2f80-11e9-98c6-cb7774b49c16.png)

**Comment by michaelccata** [comment]
Let's go with option 2
