### ISSUE TITLE
Data persistence additional test automation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#144]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#2879  

There should be automated integration tests that exercise the API calls for persisting and reading back form data (`Save`, `AllSections`, `Section`). Data can be verified by db introspection directly, or via an API call. Test data should cover 90% (ideally all) sections/fields of the SF-86 (via one large/complete application or smaller test snippets, as appropriate). There is likely test data overlap between these tests and the one John is putting together for eQIP API submission.

The automated test priority is to execution pathways that are likely to lead to cause of errors seen by Paul, or were problems historically.

**Comment by afeld** [comment]
This could also be done from the specs, checking persistence at the UI level.

**Comment by ryanhofdotgov** [comment]
Yup, when this issue was opened it wasn't with the context that almost all the persistency issues we saw in the wild were do to mis-typed variable names. Aside from testing, that common issue might also be mitigated through some kind of type check (Flow, TypeScript) or static analysis.

**Comment by afeld** [comment]
Yeah, I've been tempted to try out type checking on this project, but the prospect of adding yet another layer of compilation is daunting. I think the tests would be useful regardless.

**Comment by afeld** [comment]
--> #658
