### ISSUE TITLE
Employment activities - phone number text

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#146]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2872  

Other federal employment branch - outside US address
Stray text in phone number label

![screen shot 2018-04-18 at 2 45 36 pm](https://user-images.githubusercontent.com/19935974/38951635-50d4e970-4317-11e8-924c-a77a46af2015.jpg)

**Comment by bpdesigns** [comment]
resolved
