### ISSUE TITLE
Foreign born document number requirements

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1505]
## Where are you in the form?

**Section:** Citizenship

**Question:** Provide your current citizenship status

**Field:** [Selected] I am a U.S. citizen or national by birth, born to U.S. parent(s), in a foreign country

**Component (for example address block):** Radio select

## What did you see?

Document number is required.

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

## What did you expect to see?

*Branching needs to exist.*

If applicant selects `Other`:
1) We require a written response (this works as expected) 
2) Document number should not be required (we could also add an "I don't know" button)
3) The next four fields (DocumentNumber/Date/Place/Name) of document should be eliminated.

</br>

If applicant selects `FS-240, DS-1350, or FS-545`:
1) Document number should ~not~ be required (This is required by e-QiP when one of these three forms are selected)
2) The next three fields (Date/Place/Name) should appear (this works as expected)

*Citizenship number*
If applicant provides citizenship number (not required) then Date and Name on the certificate are required. 

 

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**

**Comment by gidjin** [comment]
Just to clarify for posterity, this story if Document or Certificate information is provided all information for the respective portion is required. As a citizen who is born to us parents in a foreign country without a US Passport then either Certificate of Citizen ship or one of the Documents must be provided. Not both. This story covers fixing the requirement for only having a Certificate or a Document. Supporting the override of US Passport will be a later story.
