### ISSUE TITLE
Phone number not validating

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1554]
## Where are you in the form?

**Section:** Your History /  Employment

**Question:** Provide your employment telephone number + Provide this person's phone number

**Field:** Phone block

**Component (for example address block):** Phone block

## What did you see?

Omit to enter phone numbers for either of the above. 
The section does not flag when clicking review or omitting the numbers.  
At review the whole accordion entry is flagged, but the error message does not provide any information like "phone number missing" and the block itself is not highlighted red. 

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

## What did you expect to see?

Error at review should say which field needs correcting and/or highlight the field in red.

## Is this error limited to just this field or others in the form?
Applies to all phone numbers in the employment accordion.

- [ ] Only relevant to just this question
- [x] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**
eApp 1.0.13

**Comment by joshmfranklin** [comment]
@michaelccata I think this one is related to #1326
