### ISSUE TITLE
Maiden name validation late trigger

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#1557]
## Where are you in the form?

**Section:** Relationships / Relatives

**Question:** Mother's maiden name

**Field:** First name

**Component (for example address block):** Text block

## What did you see?

You can move to the next section without a warning on not entering the first name of your mother's maiden name.

- [x] Validation error
- [ ] Data not saving
- [ ] Language or content issue
- [ ] Other (explain below)

<img width="785" alt="Screen Shot 2019-03-13 at 10 37 07 PM" src="https://user-images.githubusercontent.com/4422873/54327496-bd27be00-45e0-11e9-85e2-6a5ccc483c3c.png">

## What did you expect to see?

Should update the validation to `touch` and that should be it.

## Is this error limited to just this field or others in the form?

- [x] Only relevant to just this question
- [ ] Cross-form issue
- [ ] I don't know

## What operating system and browser/version are you using?

**Operating system**
- [ ] Windows
- [x] MacOS

**Browser**
- [x] Chrome
- [ ] Firefox
- [ ] IE
- [ ] Edge
- [ ] Other

**Version:**
1.0.13

**Comment by joshmfranklin** [comment]
@michaelccata I think this is happening with all `Name` blocks. It doesn't validate that any of the fields (first, middle, last) are entirely empty until you get to the review section. If we wanted to validate that those fields are empty before we hit the review page I think we'd need to see if the user has ever entered that field and trigger the validation on `blur` after they left the field for the first time and it was blank. This seems like a bit of a departure from how we handle validating empty fields in the rest of the form.

**Comment by michaelccata** [comment]
Yeah, I know that if you don't enter anything at all it won't trigger. 

But I entered something, cleared it out, and then it didn't remember that I tried to put something in there. 

It's not a life and death major issue.
