### ISSUE TITLE
Accessibility - submit screen

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#159]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2852  

On the submit screen - 

tab order is broken - tabbing out of the first signature takes the user the top of the page (to the skip to main content link)

Note: made this one a high because it would prevent a user from submitting the form

**Comment by line47** [comment]
When I `simulate valid form` then go to the submit screen I don't see a place to type my name. Is this a different bug than what s described here? I expected a textbox after clicking the `click to sign` button.

<img width="760" alt="screen shot 2018-06-06 at 4 41 14 pm" src="https://user-images.githubusercontent.com/1449852/41064037-629e6570-69a8-11e8-88e5-29c713744a5d.png">

**Comment by ryanhofdotgov** [comment]
I don't know if it is a bug per se. I saw that earlier this week and decided not to open an issue. 

The e-sign page currently assumes that you have valid data before letting you click-to-sign – which under normal circumstances is a safe bet. But `simulate valid form` lets you circumvent the usual validation. If you go back to the first section and fill out your name, eApp will use that to populate the name field on these forms automatically.

**Comment by line47** [comment]
I was able to easily tab through the submit page and was not taken back up to the `Skip to form questions` link at the very top of the page.

**Comment by line47** [comment]
@afeld or @ryanhofdotgov can you try and see if you get the behavior described in the original issue?

**Comment by afeld** [comment]
Not able to reproduce (using "simulate valid form").

**Comment by line47** [comment]
@ryanhofdotgov Can you give it a go too?

**Comment by ryanhofdotgov** [comment]
Not able to replicate – closing.
