### ISSUE TITLE
Accessibility - Employment activities- tab order

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#160]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2849  

"Additional periods of activity with this employer"
Yes/No

- [ ] Tab order is broken here, next tab after this question goes to "Skip to main content"

**Comment by bpdesigns** [comment]
No longer an issue.
