### ISSUE TITLE
Map out plan to move U.S. Passport from Foreign to Citizenship

### ISSUE THREAD

**Issue by christopherhuii** [18F/e-QIP-prototype#1608]
Reference:  EN-3442

As of creating this issue, the U.S. Passport subsection lives in the Foreign section.

In #1327 (accompanied by this [PR](https://github.com/18F/e-QIP-prototype/pull/1584)), the U.S. Passport subsection will **APPEAR** to be moved to the `Citizenship` section.

This was a decision made to give applicants a better user experience when filling out the application. This is purely a cosmetic change. ALL the data in Redux is still stored in `Foreign` and the backend/database has everything in `Foreign`.

This issue is intended to convert **EVERYTHING** to be in `Citizenship`. This includes, but is not limited to:
1. Move `Foreign.Passport` over to `Citizenship.UsPassport` (note: renaming it for clarity since Citizenship.Passports` exists)
2. Ensuring that `Foreign` has no mention of `Passport` and all references are .
3. Backend should store `UsPassport` info in `Citizenship`
4. XML data need to be updated
5. Test cases need to be updated
6. **NEED A BACKWARDS COMPATIBLE WAY TO MIGRATE EXISTING PASSPORT DATA IN FOREIGN OVER TO CITIZENSHIP**

**Comment by suzubara** [comment]
👍 If we add a data mapping layer in between Redux and the API, we should be able to complete moving the section on the F/E before having to touch the B/E and XML.
