### ISSUE TITLE
Accessibility - Address block - not reading button text

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#162]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2847  

This address is links:
- [ ] In the US
- [ ] APO/FPO/DPO
- [ ] Outside the US

All 3 buttons are not reading the text, instead are reading brackets and other code

- [ ] Apt line is also doing the same thing

**Comment by bpdesigns** [comment]
still an issue
