### ISSUE TITLE
IE 11 and Edge nav scrolling issue

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#163]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2837  

- [ ] On shorter screens (with less content) the nav isn't responsive when trying to scroll down. It jumps up and down slightly but doesn't scroll down. Sometimes eventually it unlocks and scrolls

**Comment by bpdesigns** [comment]
removed the double scroll from app
