### ISSUE TITLE
SSN on review screen

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#164]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2836  

On review screen when tabbing through SSN inputs:

- [ ] Tabbing through inputs without changing any numbers required the user to re-confirm their SSN. Can we remove this?

It requires extra work for the user and may be confusing screen reader users

**Comment by bpdesigns** [comment]
no longer seems to be an issue
