### ISSUE TITLE
Add asterisks to individual fields

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#166]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#2832  

As an eApp application I want to see asterisks for each data entry component that is required so that if I have a composite group of fields like an address or phone numbers, I see an asterisk for each component field of the group of fields.  

Acceptance Criteria
- [ ] Add asterisks to all required fields in a composite field group.

**Comment by bpdesigns** [comment]
@ryanhofdotgov @line47 @afeld  hold any issues related to adding asterisks. The purpose of the asterisk is to denote required field. I think we should remove them globally and just add "optional" next to the items that are not required. It should make sense that we are asking you questions that are required and if there are questions that are not required, we should make that clear. This removes visual clutter from every page. 

See "Suffix" example below:
<img width="641" alt="screen shot 2018-06-20 at 5 45 59 pm" src="https://user-images.githubusercontent.com/15329140/41686427-0302503a-74b2-11e8-860f-3edd68033f46.png">

I will say when we add "optional" its not necessary to add"(" ")" around it. the text is italic and gray that separates the text. We could add a "-" or visual space to give it more distance if needed.

**Comment by bpdesigns** [comment]
Closing this issue Re: #543 - We're going with removing all asterisks
