### ISSUE TITLE
Relatives - Cohabitant section showing error but all sections are complete

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#176]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2806  

On staging - data is under my log in test04:

- [ ] Cohabitant section is complete but showing an error
![screen shot 2018-03-29 at 2 04 42 pm](https://user-images.githubusercontent.com/19935974/38105535-4b3bb57e-335a-11e8-9142-61a0e32c52ee.png)

**Comment by afeld** [comment]
Hmm, not able to reproduce the issue, but hard to tell if there was a certain field causing the problem based on the screenshot alone. @ryanhofdotgov Any idea if that data is still live under the test04 account, which deployment it's referring to, and how to log into it?

**Comment by ryanhofdotgov** [comment]
Just checked the staging server (https://eqip-prototype-staging.fr.cloud.gov), which is still up but not connected to any repo/branch. It looks like this data no longer exists under the test04 account there.

I'll close since it isn't reproducible.
