### ISSUE TITLE
Data persistence - logging back in messaging

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#177]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2804  

When logging back in with saved data there is a bit of lag while data is being loaded.

I'd suggest some sort of loading message here "We are loading your saved data" . With the loading time users may be confused or worried their saved data is gone.

**Comment by bpdesigns** [comment]
@ryanhofdotgov doesn't this happen today?

**Comment by ryanhofdotgov** [comment]
Yup, thanks – closing. For expediency, many of our current issues were just bulk imported from the open issues in the previous repo without any review.
