### ISSUE TITLE
Info about you error list - SSN

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#180]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2772  

After fixing a SSN error the nav dot and error list didn't update:

 
![screen shot 2018-03-23 at 4 36 05 pm](https://user-images.githubusercontent.com/19935974/37852276-5ff58f18-2eb8-11e8-8a6b-d451c0125d1e.jpg)
![screen shot 2018-03-23 at 4 36 10 pm](https://user-images.githubusercontent.com/19935974/37852277-6108da54-2eb8-11e8-9756-31ab233e14b3.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2772#issuecomment-379778050

**Comment by bpdesigns** [comment]
lgtm
