### ISSUE TITLE
Info about you - empty email bug

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#181]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2768  

- [ ] When email is left empty there is an error on review screen. email is not required so should not throw error

![screen shot 2018-03-23 at 4 28 55 pm](https://user-images.githubusercontent.com/19935974/37852019-6629fd66-2eb7-11e8-9d79-e7bb0ea8269c.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2768#issuecomment-375791301

**Comment by line47** [comment]
Email address no longer throws a validation, i think this is good to close. 

![screen shot 2018-10-16 at 2 46 15 pm](https://user-images.githubusercontent.com/1449852/47039596-4af69e80-d152-11e8-9742-68ac15a55420.png)
