### ISSUE TITLE
Error list - links not landing on proper location - input focus

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#182]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2767  

- [ ] Page is scrolling past error

In this example error is in phone number, this is where page landed:
![screen shot 2018-03-23 at 4 26 34 pm](https://user-images.githubusercontent.com/19935974/37851926-10e7b6cc-2eb7-11e8-99cc-d9a9adc8a956.jpg)

Error is here:
![screen shot 2018-03-23 at 4 27 32 pm](https://user-images.githubusercontent.com/19935974/37851939-196144ee-2eb7-11e8-8a5d-81648e8a30f7.jpg)

- [ ] Can the focus be placed in the input with the error for screen reader users?

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2767#issuecomment-381729989

**Comment by bpdesigns** [comment]
still an issue. 

Would be a good thing to usability test to see how screenreader users would navigate a sections review page
