### ISSUE TITLE
Relative type options - accessibility - JAWS reading code

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#183]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2752  

- [ ] Sounds like JAWS is reading parts of code on these buttons (provide relative type" - "left bracket object object right bracket"

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2752#issuecomment-377533340

**Comment by bpdesigns** [comment]
this happens on a lot of content. Pretty annoying it seems I'm gonna label thins med/high
