### ISSUE TITLE
Form wide - Change all links to the underline style 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#185]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2715  

Currently we are using 3 different dashed style for links. Let's use the typical underlined style for all of them to be consistent.

![screen shot 2018-03-08 at 10 14 44 am](https://user-images.githubusercontent.com/19935974/37158562-a802b886-22b9-11e8-95f4-6e98bb3455ca.jpg)

**Comment by christopherhuii** [comment]
@ryanhofdotgov @line47 
> Let's use the typical underlined style for all of them to be consistent.

Is the standard underlined style a 1px solid underline?

**Comment by line47** [comment]
it is `text-decoration: underline;` which is the default from the USWDS
