### ISSUE TITLE
Missing label in employment record

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#189]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2686  

- [ ] Looks like a label is missing:

![screen shot 2018-02-28 at 2 05 57 pm](https://user-images.githubusercontent.com/19935974/36807292-8eea46a4-1c90-11e8-9b1a-580626695152.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2686#issuecomment-370435558

**Comment by bpdesigns** [comment]
lgtm
