### ISSUE TITLE
Homepage is skipping H1 for screen readers

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#191]
From e-QIP-prototype-truetandem created by [lauraponce](https://github.com/lauraponce) : ryanhofdotgov/e-QIP-prototype-truetandem#2669  

- [ ] Homepage should read the h1 when using a screen reader

**Comment by bpdesigns** [comment]
- I seems like the main content section does not include the initial H1 on the page. 
- Note this is for the main page content and not the the header.  
- This also occurs for section title between form field questions
