### ISSUE TITLE
Help icons and text - screen reader focus

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#195]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2629  

- [x] Help icons are reading as "link graphic" - change to "show help"
- [x] Move focus to help info box on reveal after clicking "?"
- [x] After user closes help bring focus back to input that help is related to (currently after using the close link the next tab goes to the "Skip to main content link)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2629#issuecomment-368041791

**Comment by bpdesigns** [comment]
looks good to me
