### ISSUE TITLE
Foreign military - organization asterisks new line

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#200]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2528  

- [ ] Bring asterisks up to label

![screen shot 2018-01-29 at 9 57 11 am](https://user-images.githubusercontent.com/19935974/35516885-eb1820cc-04da-11e8-9356-74b40d14d28a.png)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2528#issuecomment-367079476

**Comment by bpdesigns** [comment]
Closing this issue Re: #543 - We're going with removing all asterisks
