### ISSUE TITLE
Form wide - "Other" options

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#202]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2520  

Form wide on "Other" options that require an explanation:

- [ ] Can all of these inputs that appear after selecting "other" have a consistent label for the explanation box? "Provide explanation"

![screen shot 2018-01-26 at 2 43 21 pm](https://user-images.githubusercontent.com/19935974/35457636-930f9bba-02a7-11e8-8d1f-c332551c469d.jpg)
![screen shot 2018-01-26 at 2 43 33 pm](https://user-images.githubusercontent.com/19935974/35457637-931f992a-02a7-11e8-989a-590ba11b32d9.jpg)

**Comment by bpdesigns** [comment]
Lets match all to the design that has the "explanation for other" because the person filing the form should have to explain when the put other.
