### ISSUE TITLE
Relatives - Method of contact - Other block

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#203]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2519  

- [ ] Use a separate comment block for the "Other" answer

![screen shot 2018-01-26 at 2 38 59 pm](https://user-images.githubusercontent.com/19935974/35457508-2caa1daa-02a7-11e8-967d-ad31cd3553f8.jpg)
![screen shot 2018-01-26 at 2 39 06 pm](https://user-images.githubusercontent.com/19935974/35457510-2cb45cb6-02a7-11e8-96ee-67fe10b49301.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2519#issuecomment-372396237

**Comment by bpdesigns** [comment]
reference #202
