### ISSUE TITLE
Receive Error message when No Error Exists 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#206]
From e-QIP-prototype-truetandem created by [gshannon00](https://github.com/gshannon00) : ryanhofdotgov/e-QIP-prototype-truetandem#2501  

**What did you do?**
Got kicked out of the application and logged back in
*Including steps for recreating it, if applicable.*

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**
 An error stating there is a problem with a field.
*Include a high-level description of the feature or error here*
The error states If the middle name is an Initial then check the "Initial only' checkbox.  The middle name IS an intitial and the "Initial Only" checkbox IS checked. 
**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35400206-228ae766-01c4-11e8-94b3-a91072e15f42.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2501#issuecomment-360792488

**Comment by afeld** [comment]
Here's the error I'm seeing when trying to change my middle name to an initial:

```
web_1   | 172.21.0.1 - - [13/Jun/2018:15:27:42 +0000] "POST /api/me/save HTTP/1.1" 200 16 "http://localhost:8080/form/identification/name" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.62 Safari/537.36"
db_1    | ERROR:  duplicate key value violates unique constraint "identification_contacts_pkey"
db_1    | DETAIL:  Key (id)=(2) already exists.
db_1    | STATEMENT:  INSERT INTO "identification_contacts" ("id", "emails_id", "phone_numbers_id") VALUES (2, 1, 2)
db_1    | ERROR:  duplicate key value violates unique constraint "identification_other_names_pkey"
db_1    | DETAIL:  Key (id)=(2) already exists.
db_1    | STATEMENT:  INSERT INTO "identification_other_names" ("id", "has_other_names_id", "list_id") VALUES (2, 1, 3)
```

Can't tell if that's a local database corruption issue, or the cause here...?

**Comment by afeld** [comment]
Answer: no, those are expected, if not ideal.

**Comment by afeld** [comment]
Not able to reproduce, sorry!
