### ISSUE TITLE
DPO

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#208]
From e-QIP-prototype-truetandem created by [gshannon00](https://github.com/gshannon00) : ryanhofdotgov/e-QIP-prototype-truetandem#2495  

**What did you do?**
Chose DPO for an address
*Including steps for recreating it, if applicable.*

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
There is not 'DPO' choice in the current e-QIP; this field will not transition over if an applicant chooses it. 
**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35353964-c5a5cd70-0116-11e8-8e7c-bcd6c6ee3918.png)

 - What browser and version are you using?
 - What operating system?

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2495#issuecomment-368546808

**Comment by bpdesigns** [comment]
um. @ryanhofdotgov this is weird. confirming that there is no DPO address option in the 2016 version of SF86

**Comment by ryanhofdotgov** [comment]
Spent some time looking at this. Background:
https://mailcallblog.wordpress.com/dpo-is-for-shipments-of-personal-mail/dpo-faqs/

Also: Wikipedia says DPO addresses became valid in 2009 and there are 16 embassy locations with DPO addresses. 

I've confirmed that the existing eQIP API schema does not permit DPO to be  expressed. 

Further tests are required to see if there are better alternatives to simply dropping the DPO option in the UI – ones that allow the user to input and validate the correct address, and handle it on the backend transparently. For example, leaving the APO/FPO elements off in the XML submitted to the API if it is a DPO address.
