### ISSUE TITLE
Saved Button 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#209]
From e-QIP-prototype-truetandem created by [gshannon00](https://github.com/gshannon00) : ryanhofdotgov/e-QIP-prototype-truetandem#2484  

**What did you do?**
Clicked on Next Relationships Into button. The Saved button showed Saved Just Now, but within 5 seconds the Saved button showed Saved 18 minutes ago. So, was the data Saved Just Now, or was it saved 18 Minutes ago. 
*Including steps for recreating it, if applicable.*

**What did you expect to see?**
The Saved clock to start over if the data was Saved Just Now
*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*
![image](https://user-images.githubusercontent.com/31284016/35346677-de5566a2-0100-11e8-84e1-edc7a24a3b36.png)
![image](https://user-images.githubusercontent.com/31284016/35346707-eb9493c4-0100-11e8-8481-8ffb9540d13b.png)

 - What browser and version are you using?
Google Chrome
 - What operating system?
Windows 7

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2484#issuecomment-365987640

**Comment by bpdesigns** [comment]
is this is still an issue adding a "pilot tag"
