### ISSUE TITLE
Submit screen - final submission

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#210]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2481  

Suggest using a loading icon on this screen why submission is happening.

Users may think the form has crashed if there is no feedback to let them know it is thinking.

**Comment by bpdesigns** [comment]
I'd like to review this. @ryanhofdotgov can you provide a preview of this?
