### ISSUE TITLE
Content cut off and hidden

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#214]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2474  

Chrome with bookmark bar shown and hidden

- [ ] Content either has too much space above or is cropped and off screen

- [ ] Other names used landing there is too much space above. When answering yes for another name the accordion is off the screen and user can't scroll up to it.

![screen shot 2018-01-24 at 11 01 50 am](https://user-images.githubusercontent.com/19935974/35342608-7d046f10-00f6-11e8-87cc-32054bda8abc.jpg)
![screen shot 2018-01-24 at 11 02 01 am](https://user-images.githubusercontent.com/19935974/35342609-7d125602-00f6-11e8-9152-ee0861c806c4.jpg)
![screen shot 2018-01-24 at 11 02 17 am](https://user-images.githubusercontent.com/19935974/35342610-7d3a45fe-00f6-11e8-8b93-680abbc92325.jpg)
![screen shot 2018-01-24 at 11 02 23 am](https://user-images.githubusercontent.com/19935974/35342611-7d5010be-00f6-11e8-85b6-d9f5b92b1850.jpg)
![screen shot 2018-01-24 at 11 03 03 am](https://user-images.githubusercontent.com/19935974/35342612-7d591a24-00f6-11e8-836b-b7b566b93f0f.jpg)

**Comment by bpdesigns** [comment]
lgtm
