### ISSUE TITLE
Marital - Other names used branch - asterisks not aligned

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#220]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2450  

- [ ] Asterisks is breaking onto a new line on the second other names question

![screen shot 2018-01-19 at 11 40 05 am](https://user-images.githubusercontent.com/19935974/35161276-af35eadc-fd0d-11e7-973e-20c829ed4058.jpg)

**Comment by bpdesigns** [comment]
Closing this issue Re: #543 - We're going with removing all asterisks
