### ISSUE TITLE
Firefox - Foreign activities - event participitation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#226]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2411  

- [ ] Event participation text starts too low when landing on this screen

![screen shot 2018-01-15 at 3 22 01 pm](https://user-images.githubusercontent.com/19935974/34960233-01980d04-fa08-11e7-99c2-65e834b267ec.jpg)

**Comment by bpdesigns** [comment]
lgtm
