### ISSUE TITLE
Firefox - All sections - review - too much empty space

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#227]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2408  

- [ ] Too much empty space below the review screen on all sections

![screen shot 2018-01-15 at 2 46 18 pm](https://user-images.githubusercontent.com/19935974/34959142-1187a026-fa03-11e7-87a7-5602216eb77e.jpg)
![screen shot 2018-01-15 at 2 47 30 pm](https://user-images.githubusercontent.com/19935974/34959143-11912146-fa03-11e7-89f2-a05824607f66.jpg)

**Comment by bpdesigns** [comment]
not sure I understand this one @ryanhofdotgov

**Comment by bpdesigns** [comment]
still an issue. The problem is that you can keep scrolling for several page lengths beyond any content on the page. These blank pages can cause confusion
