### ISSUE TITLE
Firefox - previously used address - state error

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#228]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2404  

- [ ] After using a previously used address the state has a red error:

![screen shot 2018-01-15 at 10 32 17 am](https://user-images.githubusercontent.com/19935974/34949899-830f2b0c-f9df-11e7-8465-d0e250813966.jpg)

**Comment by bpdesigns** [comment]
no longer an issue
