### ISSUE TITLE
Firefox - Accordions

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#229]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2403  

- [ ] Adding a new accordion item - new item doesn't start at the top of the screen, starts part way down

![screen shot 2018-01-15 at 10 06 51 am](https://user-images.githubusercontent.com/19935974/34948752-0ea250d0-f9dc-11e7-82f4-952a0f8bf772.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2403#issuecomment-357959265

**Comment by bpdesigns** [comment]
still an issue, but only on accordion tables that span longer than the window size. Eg, not a problem adding applicants additional phone number's in an acordion
