### ISSUE TITLE
Firefox - Extension input on phone numbers misaligned 

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#230]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2401  

- [ ] Extension input on phone numbers box is misaligned 

![screen shot 2018-01-12 at 4 05 50 pm](https://user-images.githubusercontent.com/19935974/34895196-95a9427c-f7b2-11e7-9703-1bf4ae19c7d4.jpg)

**Comment by bpdesigns** [comment]
United States phone number looks fine, but DSN extension is off, 
<img width="1171" alt="screen shot 2018-09-28 at 9 40 15 am" src="https://user-images.githubusercontent.com/15329140/46212112-323d5a80-c303-11e8-9e6e-911ce29b5c89.png">
