### ISSUE TITLE
Safari - US military buttons - can't select

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#235]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2395  

- [ ] Can't select the military branch or enlisted buttons:

![screen shot 2018-01-12 at 11 48 57 am](https://user-images.githubusercontent.com/19935974/34885692-d113007e-f78e-11e7-9afc-eeca659dfcec.jpg)

Also happening in other sections. looks like the selection is being made but not showing to the user:
![screen shot 2018-01-12 at 11 57 45 am](https://user-images.githubusercontent.com/19935974/34886042-df9301f2-f78f-11e7-90a8-b00fbf1be04c.jpg)

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2395#issuecomment-357773051

**Comment by bpdesigns** [comment]
@ryanhofdotgov is this issue closed? Your comment seems to indicate that it is but it came up when I was searching open issues. Any ideas why?

**Comment by bpdesigns** [comment]
lgtm
