### ISSUE TITLE
Individual asterisks on inputs

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#240]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2361  

Few locations that still need individual asterisks:

- [ ] Place of birth & all location blocks like this:
![screen shot 2018-01-04 at 3 42 40 pm](https://user-images.githubusercontent.com/19935974/34583493-edd0241e-f165-11e7-91ae-504ad74fee16.png)
![screen shot 2018-01-04 at 3 45 26 pm](https://user-images.githubusercontent.com/19935974/34583591-4ec8f944-f166-11e7-88a3-9fd42c54372d.png)
![screen shot 2018-01-04 at 3 49 22 pm](https://user-images.githubusercontent.com/19935974/34583746-dfaabe48-f166-11e7-93a9-06d76f17cc62.png)

- [ ] Height and weight:
![screen shot 2018-01-04 at 3 43 42 pm](https://user-images.githubusercontent.com/19935974/34583558-3040725e-f166-11e7-8b7f-745074d6c2fa.png)

@bmallred @floresj Thoughts on switching the asterisks to the label when it is there across the form?

**Comment by bpdesigns** [comment]
Closing this issue Re: #543 - We're going with removing all asterisks
