### ISSUE TITLE
Phone - margin on right and horizontal scrolling

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#255]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#2100  

- [ ] Close margin on right of screen
- [ ] Remove horizontal scrolling

<img width="385" alt="screen shot 2017-10-20 at 2 40 17 pm" src="https://user-images.githubusercontent.com/19935974/31836932-00028854-b5a5-11e7-881f-730882e56cf2.png">
<img width="389" alt="screen shot 2017-10-20 at 2 40 10 pm" src="https://user-images.githubusercontent.com/19935974/31836933-000bdae4-b5a5-11e7-8e2d-9fce4e9acda0.png">

**Comment by bpdesigns** [comment]
Is this still happening? For which browser?
