### ISSUE TITLE
Employment record - validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#266]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1980  

Provide dates of employment:
From date:
- [x] Date must be greater than or equal to DOB

.
Date range for additional period of activity:
From date:
- [x] Date must be greater than or equal to DOB.
To date:
- [ ] Date must be less than or equal to "Dates of employment" (13A.2.3) From Date

.
Provide the date you were fired:
- [x] Date must be greater than or equal to DOB

.
Provide the date you quit after being told you would be fired:
- [x] Date must be greater than or equal to DOB

.
Provide the date you left following charges or allegations of misconduct
- [x] Date must be greater than or equal to DOB

.
Provide the date you left by mutual agreement following a notice of unsatisfactory performance
- [x] Date must be greater than or equal to DOB

.
Provide the month and year you were warned, reprimanded, suspended or disciplined
- [x] Date must be greater than or equal to DOB

.

**Comment by bpdesigns** [comment]
only issue left on this item is 

Date range for additional period of activity:
From date:

- [ ]  Date must be less than or equal to "Dates of employment" (13A.2.3) From Date
