### ISSUE TITLE
Where you went to school - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#268]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1909  

Provide the dates of attendance:
From Date:
- [x] Date must be greater than or equal to DOB

Provide current address for this person (including apartment number:
- [ ] Load "I don't know" button if empty on review screen

Provide telephone number for this person:
- [ ] Load "I don't know" button if empty on review screen

Provide type of degrees(s)/diploma(s) received and date(s) awarded - Date awarded:
- [x] Date must be greater than or equal to DOB
- [ ] Date awarded must be greater than or equal to Date graduated.

**Comment by bpdesigns** [comment]
"Date must be greater than or equal to DOB" is complete
