### ISSUE TITLE
Former federal service - validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#269]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1892  

Do you have former federal civilian employment, excluding military service, NOT indicated previously, to report?:
- [ ] Load an "I don't know" button if not answered on review screen

Provide dates of federal civilian employment:
From Date:
- [x] Date must be greater than or equal to DOB

**Comment by bpdesigns** [comment]
"Date must be greater than or equal to DOB" is complete
