### ISSUE TITLE
Getting submission error after completing form and selecting submit

### ISSUE THREAD

**Issue by jglosx3** [18F/e-QIP-prototype#270]
I completed sample entry for SF86 , signed all releases but get the following error

'There was a problem submitting your SF-86. Please contact support for additional information.'

how do i determine what cause this error.  all of the field level checks seem to pass.

**Comment by jglosx3** [comment]
Ryan,

My names is Jonathan Gloster from G2, Inc. We are working with USCC to
develop a prototype analytic framework that ingest SF86 data to perform
automated verification of information.  I an going to had you over to one
of my tech leads Rich Merritts for follow-up. his github profile name
is:  richmerritts.
his hemail is rich.merritts@g2-inc.com


Jonathan A. Gloster, CISSP
Sr. System Architect
G2, Inc.
302 Sentinel Drive, Suite 300
Annapolis, Junction, MD 20701
301.575.5161
Mobile: 301.467.4368
jonathan.gloster@g2-inc.com

**Comment by ryanhofdotgov** [comment]
Followed up via email.
