### ISSUE TITLE
Remove `Simulate valid form` option on `Review`page

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#273]
At the very bottom of the `Review` page in the `Review and submit` section, there is a hyperlink `Simulate valid form` that gives the user access to a debugging/testing feature. This feature allows the submit process to be exercised with invalid form data. 

Remove the hyperlink and disable the associated functionality unless the system is in `debug` mode.

**Comment by richmerritts** [comment]
Please provide instructions on how to build/run the system in debug mode.
