### ISSUE TITLE
Logout link in upper right corner does not logout for SAML-based sign-ons

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#275]
Steps to reproduce:
- Sign-in via SAML (i.e., WSO2)
- Click Logout in upper right corner

Expected behavior:
Return to eApp login screen

Actual behavior:
Application data gets re-loaded, user stays logged in

Replicated  in `nbis-test.com` environment.

**Comment by afeld** [comment]
Is there a good way to test this locally?

**Comment by ryanhofdotgov** [comment]
I can replicate the issue with local WSO2 and eApp instances. I'll forward the instructions for set up that were passed to me, in case you'd like to work on this issue and get WSO2 incorporated into our project infrastructure.

**Comment by afeld** [comment]
Wasn't able to reproduce using a local WSO2 5.5.0 (see #458), but will take a look at the logic in there and see if there's anything that looks flaky.
