### ISSUE TITLE
Association record - Advocating - validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#281]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1852  

Provide the dates of advocating acts of terrorism:
From date:
- [x] Date must be greater than or equal to DOB

**Comment by bpdesigns** [comment]
LGTM
