### ISSUE TITLE
Investigations and clearance record - Denied - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#284]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1811  

Date security clearance eligibility/access authorization was denied, suspended or revoked:
- [x] Date must be greater than or equal to DOB

**Comment by bpdesigns** [comment]
LGTM
