### ISSUE TITLE
Investigations and clearance record - Ever been investigated - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#285]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1801  

Date the investigation was completed:
- [x] Date must be greater than or equal to DOB

Date clearance eligibility/access was granted:
- [x] Date must be greater than or equal to both DOB and "Date the investigation was completed

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1801#issuecomment-324326698

**Comment by bpdesigns** [comment]
LGTM
