### ISSUE TITLE
Signatures

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#288]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#1763  

As an eApp applicant I want to sign my SF86 application so that NBIB knows it’s me.

Related User Stories:
#655 
#1521

**Comment by bpdesigns** [comment]
@ryanhofdotgov I don't know if this is still a problem
