### ISSUE TITLE
Section 1 - SSN

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#299]
From e-QIP-prototype-truetandem created by [TravisAJackson](https://github.com/TravisAJackson) : ryanhofdotgov/e-QIP-prototype-truetandem#1742  

Invalid use of SSN.
123 45 6789 is not allowed.

![image](https://user-images.githubusercontent.com/30842622/29281320-93d9d02a-80ec-11e7-9541-27ff9bf815fd.png)

**Comment by bpdesigns** [comment]
SSA.gov states that there are NO ssn numbers starting with 000, 666 and 900-999 https://www.ssa.gov/employer/randomization.html

It sounds like the idea to run each ssn against SSA's SSN validator didn't get any traction right? https://www.ssa.gov/employer/ssnv.htm

**Comment by bpdesigns** [comment]
LGTM
