### ISSUE TITLE
Section 1 - Contact Information - International Number

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#302]
From e-QIP-prototype-truetandem created by [TravisAJackson](https://github.com/TravisAJackson) : ryanhofdotgov/e-QIP-prototype-truetandem#1732  

Invalid numbers accepted. See ISO standards.

![image](https://user-images.githubusercontent.com/30842622/29278503-ee5f018c-80e2-11e7-982d-6f2c3d7f7aa8.png)

**Comment by bpdesigns** [comment]
Still an issue but not sure how to solve this except to say that the first field should probably not allow "000"
