### ISSUE TITLE
Section 1 - Contact Information

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#303]
From e-QIP-prototype-truetandem created by [TravisAJackson](https://github.com/TravisAJackson) : ryanhofdotgov/e-QIP-prototype-truetandem#1722  

Area Code 000 is invalid but no error given.
![image](https://user-images.githubusercontent.com/30842622/29173172-7125c500-7db0-11e7-8384-0c6f73532276.png)

**Comment by bpdesigns** [comment]
still an issue. similar to #302
