### ISSUE TITLE
Use of alcohol - Mandatory counseling or treatment - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#306]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1696  

Dates of counseling or treatment:
From date:
- [x] Date must be greater than or equal to DOB

To date:
- [ ] Ensure valid date greater than or equal to From Date

**Comment by bpdesigns** [comment]
LGTM
