### ISSUE TITLE
Use of alcohol - Negative impact - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#307]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1694  

Dates of involvement or use:
From date:
- [x] Date must be greater than or equal to DOB

To date:
- [ ] Ensure valid date greater than or equal to From Date

Month/year when this negative impact occurred:
- [ ] Date must be greater than or equal to "Dates of involvement or use"  From Date

**Comment by bpdesigns** [comment]
Still an issue 

this date should be before the bottom two dates 
<img width="534" alt="screen shot 2018-08-02 at 2 49 27 pm" src="https://user-images.githubusercontent.com/15329140/43604257-557ba622-9663-11e8-888c-6d2de76077e1.png">

These two dates should show errors as they are before the start date 
<img width="569" alt="screen shot 2018-08-02 at 2 49 32 pm" src="https://user-images.githubusercontent.com/15329140/43604285-6413a18a-9663-11e8-9234-41453287ef86.png">
