### ISSUE TITLE
Substance use - Purchase - validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#308]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1683  

Estimate for the month and year of first involvement:
- [x] Date must be greater than or equal to DOB

Estimate for the month and year of most recent involvement:
- [ ] Date must be greater than or equal to "Estimate for the month and year of first involvement

**Comment by bpdesigns** [comment]
Also does not flag that first date is after last date 

<img width="583" alt="screen shot 2018-05-25 at 6 27 21 pm" src="https://user-images.githubusercontent.com/15329140/40568556-3e620986-6049-11e8-9287-a5c49477d8cb.png">
