### ISSUE TITLE
Substance use - Usage - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#309]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1678  

Estimate of the month and year of first use:
- [x] Date must be greater than or equal to DOB

Estimate of the month and year of most recent use:
- [ ] Date must be greater than or equal to "Estimate of the month and year of first use

**Comment by bpdesigns** [comment]
see #308 for same issue
