### ISSUE TITLE
Mobile - elements not adjusting to screen width

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#310]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1676  

- [ ] Throughout form certain element widths are not adjusting to the smaller width:

<img width="401" alt="screen shot 2017-08-02 at 2 00 17 pm" src="https://user-images.githubusercontent.com/19935974/28887596-c33f4b48-778b-11e7-8df1-b1f64e590e4b.png">
<img width="401" alt="screen shot 2017-08-02 at 2 05 12 pm" src="https://user-images.githubusercontent.com/19935974/28887599-c3461f36-778b-11e7-8e89-c744d64947ea.png">
<img width="401" alt="screen shot 2017-08-02 at 2 05 19 pm" src="https://user-images.githubusercontent.com/19935974/28887597-c340bcf8-778b-11e7-9223-60c4cbca5895.png">
<img width="401" alt="screen shot 2017-08-02 at 2 05 39 pm" src="https://user-images.githubusercontent.com/19935974/28887598-c34411dc-778b-11e7-936d-6528bca15ade.png">

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1676#issuecomment-348233029

**Comment by bpdesigns** [comment]
LGTM

**Comment by bpdesigns** [comment]
actually the header content is still getting cut off
