### ISSUE TITLE
Don't warn users when fields are empty and switch from Yes to No

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#314]
From e-QIP-prototype-truetandem created by [billygriffin](https://github.com/billygriffin) : ryanhofdotgov/e-QIP-prototype-truetandem#1605  

As a user who has selected "Yes" and not entered any data into a Yes/No question, I want to be able to switch my answer to "No" without a pop-up message appearing so that I'm not confused and shown confirmation messages that aren't applicable to me.

**Comment by bpdesigns** [comment]
not a blocker to complete, but could be really annoying and slow people down
