### ISSUE TITLE
Remove pa11y from CI

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#322]
From e-QIP-prototype-truetandem created by [bmallred](https://github.com/bmallred) : ryanhofdotgov/e-QIP-prototype-truetandem#1428  

Try to find something to replace the functionality used with pa11y.

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1428#issuecomment-314804862

**Comment by afeld** [comment]
cc #608

**Comment by afeld** [comment]
...but no, doesn't seem to be set up anymore.
