### ISSUE TITLE
Consider changing navigation toggle UI from a link to a button

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#326]
From e-QIP-prototype-truetandem created by [toolness](https://github.com/toolness) : ryanhofdotgov/e-QIP-prototype-truetandem#1393  

The navigation toggle UI is currently implemented as a `<a href="javascript:;;">`.

As I mentioned in https://github.com/truetandem/e-QIP-prototype/pull/1387#discussion_r120868552, I think this might be better as a `<button>`.  From Marcy Sutton's [Links vs. Buttons in Modern Web Applications](https://marcysutton.com/links-vs-buttons-in-modern-web-applications/):

> The starkest difference between a link and a button to me is that a link navigates the user to a new resource, taking them away from the current context (internal links are the only wrinkle here). A button toggles something in the interface, like a video player; or triggers new content in that same context, like a popup menu using `aria-haspopup`.

It might sound pedantic (I always thought it was) but it has UX implications for users of assistive technologies (ATs):

> If a screen reader user calls tech support and gets instructions to “click the button” in your UI that’s really coded as a link, they may have trouble finding it. Also, consider voice interfaces: if you say a command to click a button but it’s really coded as a link, you might have problems, no?

**Comment by afeld** [comment]
Using [`role="button"`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role) as a next-best-thing.
