### ISSUE TITLE
Fields with radio buttons aren't grouped for screen readers

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#329]
From e-QIP-prototype-truetandem created by [toolness](https://github.com/toolness) : ryanhofdotgov/e-QIP-prototype-truetandem#1338  

e-QIP has lots of fields with radio buttons, e.g.:

> ![2017-05-30_18-14-12](https://cloud.githubusercontent.com/assets/124687/26607316/e9a0e3b4-4563-11e7-8812-e7055ae00524.png)

For sighted users, it's easy to see what the question is, but this isn't always the case for screen-reader users, who often use <kbd>Tab</kbd> to navigate from one form control to another. When this happens, the screen reader has no way to associate the radio buttons with the question they're answering (in the above example's case, that question is "Were you born in the United States of America?"). Because it has no understanding of these semantics, screen reader users will just hear the answers without knowing what the question is, which can be very confusing.

However, there's some markup that can be added to let screen readers know what's going on!  One typical solution is to wrap the whole area in a `<fieldset>` and wrap the question in a `<legend>`.  Another is to use the ARIA `role="radiogroup"` or `role="group"` roles.

You can learn more about this on Deque University's [Radio inputs with the same name attribute value must be part of a group](https://dequeuniversity.com/rules/axe/2.1/radiogroup?application=axeAPI) page.

I've always gone the `<fieldset>`/`<legend>` route, but one caveat about this is that `<legend>` elements are notoriously hard to style. Because of this, I've always made the `<legend>` hidden to sighted users, and provided a separate `aria-hidden="true"` element that presents the same question to sighted users and is nicely styled. (I didn't learn about the `role`-based solutions until very recently, so they may actually be easier to implement and style!)

**Comment by bpdesigns** [comment]
@line47 will updating to the radio buttons in #822 fix this accessibility issue in the way you are thinking of implementing -  Assuming it would be a modification of the USWDS?

**Comment by bpdesigns** [comment]
validated this issue 9/25/18

Radio buttons throughout the app are not grouped together (e.g., 1 of 2) each button is written as its own group as in “radio button 1 of 1” written twice for a list of two buttons
