### ISSUE TITLE
Help buttons next to fields are not keyboard-accessible

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#330]
From e-QIP-prototype-truetandem created by [toolness](https://github.com/toolness) : ryanhofdotgov/e-QIP-prototype-truetandem#1336  

This is similar to #1334, but for the "?" buttons that provide help for individual fields on the forms:

> ![2017-05-30_17-43-43](https://cloud.githubusercontent.com/assets/124687/26606341/8cf8340e-455f-11e7-8ea3-98395b317a57.png)

Note also that for screen reader users, it might help to think of the content revealed by these buttons as [accessible tooltips](http://heydonworks.com/practical_aria_examples/#input-tooltip) or [accessible collapsibles](http://heydonworks.com/practical_aria_examples/#progressive-collapsibles).

**Comment by bpdesigns** [comment]
looks good
