### ISSUE TITLE
docker-compose instructions in README are a bit confusing

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#333]
From e-QIP-prototype-truetandem created by [toolness](https://github.com/toolness) : ryanhofdotgov/e-QIP-prototype-truetandem#1332  

Hi!  I recently set up the project and overall I found the README quite helpful.

However, one area I found confusing was with respect to the `docker-compose` instructions.

The README says to run `docker-compose up` after creating an `.env` file, but it then says to run `yarn install` and `glide install`. I found this confusing because `docker-compose up` seemed to set everything up for me and I was able to access my local instance using the URL and username and password explained later in the README's "Running a local server" section.

I guess my question is: is `docker-compose` optional, or required for developing on this project?

If it's required, it seems like there should be something early in the README that establishes this expectation, and that there's enough context for developers to figure out how to get commands to work. For instance, one thought I had when reading the instructions to run `yarn` was, "should I be running `docker-compose run <some-container> yarn`?  And if so, which container should I be running the command in?".

If it's *not* required, I think this should be made explicit too, and alternatives to non-docker CLI commands should be provided. For instance, in CALC we have a [using Docker guide](https://calc.gsa.gov/docs/docker.html) that advises developers to run `docker-compose run app bash` to shell-in to the app container so that all the CLI commands elsewhere in the docs work.

I wanted to submit a PR to clear this up myself but I wasn't sure what your preference would be, so I decided to file this issue instead.

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1332#issuecomment-305605714

**Comment by afeld** [comment]
No longer relevant.
