### ISSUE TITLE
Foreign activities - Direct control - Yes/No buttons within accordions

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#337]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1314  

Yes/No buttons that create branches inside accordion are not functioning properly.

When Yes is selected and user clicks No:
Yes is deselected but No isn't selected, user has to click No again to select it.

<img width="713" alt="screen shot 2017-05-26 at 9 44 52 am" src="https://cloud.githubusercontent.com/assets/19935974/26497182/7920c2bc-41f8-11e7-900a-da865a5978bf.png">
<img width="774" alt="screen shot 2017-05-26 at 9 45 01 am" src="https://cloud.githubusercontent.com/assets/19935974/26497183/7a27a860-41f8-11e7-8b23-f122a40c5bc8.png">

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1314#issuecomment-304909521

**Comment by bpdesigns** [comment]
LGTM
