### ISSUE TITLE
Relatives - Foreign relative's employer, Foreign military affiliation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#341]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1281  

Name of current employer, or provide the name of their most recent employer:
- [x] Response or "I don't know" is required

Address of current employer:
- [x] Response or "I don't know" is required
<img width="888" alt="screen shot 2017-05-22 at 3 46 03 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325652/c6a81292-3f05-11e7-8639-15847afa7ebc.png">

-
Foreign Military Affiliation:
- [x] Response is required

Foreign Military Affiliation - Detail:
- [ ] Response is required

Do you have an additional relative to enter?:
- [x] Response is required

<img width="884" alt="screen shot 2017-05-22 at 3 48 13 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325727/134ded7e-3f06-11e7-9a93-742b46e78435.png">

**Comment by bpdesigns** [comment]
unsure if this is okay. The "I don't know" comes after the comment field. 

<img width="649" alt="screen shot 2018-08-02 at 6 57 05 pm" src="https://user-images.githubusercontent.com/15329140/43615503-ed3158dc-9685-11e8-90c4-854eac80a4b7.png">
<img width="668" alt="screen shot 2018-08-02 at 6 55 22 pm" src="https://user-images.githubusercontent.com/15329140/43615506-f0c3a9b4-9685-11e8-8bf9-86fd4416a7a4.png">
