### ISSUE TITLE
Relatives - Foreign Citizenship and contact - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#342]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1280  

 Type of documentation he or she possesses to support U.S. residence:
- [ ] Response is required
<img width="887" alt="screen shot 2017-05-22 at 3 23 25 pm" src="https://cloud.githubusercontent.com/assets/19935974/26324878/9de12734-3f02-11e7-8071-a4aa482b257f.png">

-
Document number:
- [ ] Response is required
- [ ] Show an "I don't know" button and comment box on review screen if blank
<img width="882" alt="screen shot 2017-05-22 at 3 23 36 pm" src="https://cloud.githubusercontent.com/assets/19935974/26324885/a3eebe8e-3f02-11e7-9cef-4ce03d05167a.png">

-
Approximate date of first contact:
- [ ] Response is required
- [ ] Show an "Not applicable" button and comment box on review screen if blank
- [ ] Date must be greater than or equal to both DOB and "Your relative's date of birth". Date must be less than or equal to NOW.

Approximate date of last contact:
- [ ] Response is required if "Approximate date of first contact" has a response
- [ ] Date must be greater than or equal to "Approximate date of first contact" . Date must be less than or equal to NOW.
<img width="864" alt="screen shot 2017-05-22 at 3 33 17 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325209/fd25b600-3f03-11e7-9e39-00aeff2830e7.png">

-
Methods of contact
- [ ] Response is required if "Approximate date of first contact" has a response

Approximate frequency of contact
- [ ] Response is required if "Approximate date of first contact" has a response

<img width="855" alt="screen shot 2017-05-22 at 3 37 12 pm" src="https://cloud.githubusercontent.com/assets/19935974/26325353/8ad91b9a-3f04-11e7-83c8-64dabf5b2685.png">

**Comment by bpdesigns** [comment]
I'm not seeing this question in eApp. 
<img width="622" alt="screen shot 2018-08-02 at 7 01 44 pm" src="https://user-images.githubusercontent.com/15329140/43615644-a7d78a9e-9686-11e8-82c3-93dceabe5d1d.png">

**Comment by bpdesigns** [comment]
@ryanhofdotgov can you doublecheck this? I can't find the question in eApp in the relatives section
