### ISSUE TITLE
Relatives - Other names used - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#347]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1270  

- [ ] Response is required if relative type is:
Father
or
Child
or
Stepchild
or
Brother
or
Sister
or
HalfBrother
or
HalfSister
or
Stepbrother
or
Stepsister
or
Stepmother
or
Stepfather

-
Other names used details validation: 
Full name block:
- [x] Response is required

Maiden name:
- [x] Response is required

Dates used:
- [x] Response is required
- [ ] Format: MM/YYYY

From date:
- [x] Ensure valid date, no future date allowed. 
- [ ] Date must be greater than or equal to "Your relative's date of birth

To date:
- [ ] Ensure valid date greater than or equal to From Date. 
- [x] Date must be less than or equal to NOW. "Present" allowed instead of date

Has this relative used any additional names?:
- [x] Response is required

- [ ] Add additional comment to this section at bottom

-
<img width="919" alt="screen shot 2017-05-22 at 1 12 32 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320288/5aa5bcbc-3ef0-11e7-9e92-a9b02099a789.png">
<img width="890" alt="screen shot 2017-05-22 at 1 12 26 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320289/5aaae44e-3ef0-11e7-9429-a936a3a458d4.png">
<img width="903" alt="screen shot 2017-05-22 at 1 29 15 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320902/ad1a5226-3ef2-11e7-923f-74e865451907.png">
<img width="900" alt="screen shot 2017-05-22 at 1 29 21 pm" src="https://cloud.githubusercontent.com/assets/19935974/26320903/ae7e3114-3ef2-11e7-97f4-3adf5626f4fa.png">

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/1270#issuecomment-356662318

**Comment by bpdesigns** [comment]
The logic of this error is tying the to the birthdate of the applicant and not to the birthdate of the person the date is addressing 

<img width="661" alt="screen shot 2018-08-02 at 7 08 48 pm" src="https://user-images.githubusercontent.com/15329140/43615885-c98e1ad0-9687-11e8-9114-cd5ab0188e0f.png">

**Comment by ryanhofdotgov** [comment]
I think all of this is happening already, leaving open to validate.
