### ISSUE TITLE
Relatives - Countries of citizenship - Validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#349]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1267  

- [ ] Response is required

-
<img width="974" alt="screen shot 2017-05-22 at 1 00 35 pm" src="https://cloud.githubusercontent.com/assets/19935974/26319863/ad80152e-3eee-11e7-8b88-a0dcf70a358f.png">

**Comment by bpdesigns** [comment]
lgtm
