### ISSUE TITLE
Relatives section - overall validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#351]
From e-QIP-prototype-truetandem created by [Jay-Neighbours-I72](https://github.com/Jay-Neighbours-I72) : ryanhofdotgov/e-QIP-prototype-truetandem#1263  

Criteria for overall section validation - these would appear on the review screen:

- [ ] Mother and Father must be checked, or else DNK and a Comment on 2nd pass. 
- [ ] Mother-in-law and Father-in-law must be checked if marital status is "Married" or "Separated", or else DNK and a Comment on 2nd pass. 
- [ ] Mother-in-law and Father-in-law not allowed if marital status is "Never Married".

**Comment by ryanhofdotgov** [comment]
I think maybe we should have a rough system of categorizing the severity of validation errors? For example, validation error that prevents someone from entering their valid data would be a high, but maybe one that allows ambiguous data entry, or forces an annoying step be a medium? 

I'd flag this as a medium, for example.

**Comment by bpdesigns** [comment]
Thanks @ryanhofdotgov I like that system. I can go through these early next week and tag them.
