### ISSUE TITLE
Add unit test outside of the given timeline

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#358]
From e-QIP-prototype-truetandem created by [bmallred](https://github.com/bmallred) : ryanhofdotgov/e-QIP-prototype-truetandem#527  

Reference: PR [#462](https://github.com/truetandem/e-QIP-prototype/pull/462#discussion_r102563351) by @mgwalker

> Can you add one more test case here that is outside the summary range (10 years?) to verify that there are still only two displayed?

**Comment by bpdesigns** [comment]
@ryanhofdotgov okay to close this?

**Comment by ryanhofdotgov** [comment]
No, I think the original issue is still outstanding.
