### ISSUE TITLE
Integration of Previous Federal Service

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#361]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#465  

Need to discuss how to integrate this form section into the greater SF-86.  It is slightly different from employment history since it is requesting ALL federal employment history (not just past 10 years)

**Comment by bpdesigns** [comment]
I'm not seeing an ask for all federal employment on the form, just 10 years.
 
<img width="937" alt="screen shot 2018-08-03 at 9 19 07 am" src="https://user-images.githubusercontent.com/15329140/43644994-962be114-96fe-11e8-9911-6b1f70ea4663.png">

**Comment by bpdesigns** [comment]
@ryanhofdotgov or @michaelccata can you verify?

**Comment by michaelccata** [comment]
Yeah we should only ask for the past 10 years.
