### ISSUE TITLE
Add Military Ranks

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#362]
From e-QIP-prototype-truetandem created by [pjsumm](https://github.com/pjsumm) : ryanhofdotgov/e-QIP-prototype-truetandem#450  

For text fields requiring the user to enter a military rank, provide a listing of ranks from which to choose.

**Comment by bpdesigns** [comment]
Seems like a good idea to reduce the error rate. Its a pretty big [list](https://www.factmonster.com/world/war/us-military-ranks) though. I would recommend an autocomplete instead.
