### ISSUE TITLE
Prevent accidental clicking of "estimated" checkbox on leaving date fields

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#363]
From e-QIP-prototype-truetandem created by [bmallred](https://github.com/bmallred) : ryanhofdotgov/e-QIP-prototype-truetandem#374  

Brought over from #294

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/374#issuecomment-315417762

**Comment by bpdesigns** [comment]
Don't see this as a problem
