### ISSUE TITLE
How do we handle validation/translation of accented characters

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#364]
From e-QIP-prototype-truetandem created by [bmallred](https://github.com/bmallred) : ryanhofdotgov/e-QIP-prototype-truetandem#371  

Brought over from #294

**Comment by ryanhofdotgov** [comment]
See https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/371#issuecomment-315381259

**Comment by bpdesigns** [comment]
@ryanhofdotgov I believe the current state is limiting us to a narrow ascii set. Did we ever determine what values for this field that eqip receives?

**Comment by ryanhofdotgov** [comment]
It's a outstanding question to partner agency, and in absence of response the decided course of action we need to take is to limit all input to ASCII to be prudent.

**Comment by bpdesigns** [comment]
gotcha. thanks
