### ISSUE TITLE
Clicked button cannot be unclicked

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#369]
BUG with the button for  "I have not been ordered, advised, or asked to seek counseling or treatment by any of the above." in section - "Substance use > Illegal use of drugs and drug activity >
Mandatory counseling or treatment"

Once you click the button you cannot unclick it. 

<img width="499" alt="screen shot 2018-05-25 at 6 30 56 pm" src="https://user-images.githubusercontent.com/15329140/40568629-c9fc64b4-6049-11e8-9c62-66d673c5791a.png">

**Comment by bpdesigns** [comment]
Label: Bug

**Comment by line47** [comment]
Could this be a radio button list instead of these buttons?

**Comment by bpdesigns** [comment]
Hi Scott. We've got other buttons styled in same way so I'd like to maintain this visual element

**Comment by line47** [comment]
Hey @bpdesigns after looking at this pattern across the application I think it's a bit confusing. The help text above the buttons says _check all that apply_ but yr not checking anything. I think showing the checkbox or radio button in addition to the big clickable box would be a great way to make this clearer to the user.

**Something like this**
![screen shot 2018-06-14 at 10 49 23 am](https://user-images.githubusercontent.com/1449852/41419755-d2dc5414-6fc0-11e8-9de7-9bfc6fcdf389.png)

**Comment by bpdesigns** [comment]
Hi Scott. I agree that this needs more design review. I won’t be able to
look into it until next week.

Sent from my iPhone

On Jun 14, 2018, at 7:51 AM, Scott Weber <notifications@github.com> wrote:

Hey @bpdesigns <https://github.com/bpdesigns> after looking at this pattern
across the application I think it's a bit confusing. The help text above
the buttons says *check all that apply* but yr not checking anything. I
think showing the checkbox or radio button in addition to the big clickable
box would be a great way to make this clearer to the user.

*Something like this*
[image: screen shot 2018-06-14 at 10 49 23 am]
<https://user-images.githubusercontent.com/1449852/41419755-d2dc5414-6fc0-11e8-9de7-9bfc6fcdf389.png>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/18F/e-QIP-prototype/issues/369#issuecomment-397323762>,
or mute the thread

**Comment by ryanhofdotgov** [comment]
I'll add my 2 cents and say that the paradigm of clicking a button again to unselect it was not intuitive when I first started using eApp. I'm not in favor of making sweeping UI changes through the app just quite yet, but I am surprised this UI aspect lasted through all the user testing rounds.

**Comment by ryanhofdotgov** [comment]
For this issue, let's fix the bug using the existing design paradigm – if there is a switch to a different design, that would be a separate issue affecting the app as a whole.
