### ISSUE TITLE
Remove text in Foreign Associations > Immediate Family Contact

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#371]
Remove text in Foreign Associations > Immediate Family Contact

"For Section 7" (highlighted in the text block) should be removed or changed to Section 6 which is the section number for Foreign Associations

<img width="517" alt="screen shot 2018-05-25 at 7 04 50 pm" src="https://user-images.githubusercontent.com/15329140/40569330-a6d6ad82-604e-11e8-8539-ef1db012ea6c.png">

**Comment by bpdesigns** [comment]
Incorrect content

**Comment by ryanhofdotgov** [comment]
Run by Drew
