### ISSUE TITLE
Generate and store application data archival PDF on backend

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#373]
As a user, I want to be able to download my application data in archival format (i.e., PDF) even if my browser or OS does not support save to PDF.

As system owner, I want an application data archival PDF to be persisted like our other archival PDFs (certifications, medical releases, etc) as an official record.

**Comment by ryanhofdotgov** [comment]
Cryptographic hash of application data was stored in database in #372. Deferring remaining functionality.

**Comment by ryanhofdotgov** [comment]
Long term plan is for this to be delegated to a system external to eApp, but we need a short term solution.

One idea I had was something like this:
https://medium.com/compass-true-north/go-service-to-convert-web-pages-to-pdf-using-headless-chrome-5fd9ffbae1af

Any requirements beyond the Go runtime need to be coordinated with NBIS infrastructure team.

**Comment by macrael** [comment]
Is it desirable for the data to be in the same format as the original form? We are using some go based pdf generation code in another project where we have a pdf of a paper form and insert images of text into the appropriate boxes and then render the whole thing to a pdf in the end.

**Comment by ryanhofdotgov** [comment]
The NBIS product owner wanted to do the least amount of effort to get something functional, since it is probably all going to get thrown away in 2-4 months, so that probably drives the technology/design choice more than anything. They were hoping to skip the effort around reviewing a new PDF design at this time as well as minimize development time.

Historically, the archival PDF in e-QIP served at least a couple of different purposes:
* Allow applicant to store their data themselves, offline
* Allow them to easily re-enter it in e-QIP if e-QIP for some reason didn't preserve their data on a subsequent background check

What Go PDF library were you thinking of? Rendering text as images is likely a non-starter anyways as these PDFs really need their form values searchable and copy/paste-able. 

When I implemented the signature PDFs in eApp at what I thought was at "the last hour", I couldn't find anything appropriate other than https://unidoc.io, which would require a commercial license for this project. At that time we couldn't stray from Go-based solutions, due to constraints imposed by our interim authority to test (IATT).
