### ISSUE TITLE
Wrong question content for Psychological and Emotional Health - Consultations

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#374]
Section
10/ Psychological and Emotional Health > Consultations 

Question says
"Has a court or administrative agency EVER ordered you to consult with a mental health professional?" 

(If answered YES a new question is prompted) _Provide the name of the court or administrative agency that declared you mentally incompetent_That second question is incorrect as is the rest of that drop down. I wonder if the correct questions are there but not being fed when "yes" is hit. 

@ryanhofdotgov If no replacement questions are found these are what I was able to put together from reviewing the [sf86 pdf](https://www.opm.gov/forms/pdf_fill/sf86-non508.pdf) 

The second question should read
 _Provide the name of the mental health professional you consulted with_ . 
[name field]

The third question should read
__Provide the name of the mental health professional's agency, organization, or facility_
[name field]

The last question in this section should read
_Provide the address of the mental health professional you consulted with_
[address field]

NOTE
The incorrect question is a duplicate from "10/ Psychological and Emotional Health > Consultations" 

That Question says "Has a court or administrative agency ever issued an order declaring you mentally incompetent? (If answered YES a new question is prompted) _Provide the name of the court or administrative agency that declared you mentally incompetent_"

<img width="723" alt="screen shot 2018-05-29 at 3 31 58 pm" src="https://user-images.githubusercontent.com/15329140/40681743-ffbe1d70-6357-11e8-8d29-d9decfa1b7f1.png">

**Comment by bpdesigns** [comment]
I think this issue should be labeled high priority

**Comment by line47** [comment]
When selecting `yes` I see the following questions in this order

- Provide the date this occurred
- Provide the name of the court or administrative agency that declared you mentally incompetent
- Provide the address of the court or administrative agency
- Was this matter appealed to a higher court or administrative agency?

What questions in what order should I be seeing when answer is `yes`, I'm a little confused on what the expectation is

**Comment by ryanhofdotgov** [comment]
Just went investigated this with Scott. The version of the SF-86 linked above is the December 2010 version. It is the first one that comes up when you do a Google search, but the latest one is from [November 2016 ](https://www.opm.gov/forms/pdf_fill/sf86.pdf)and is on this page: https://www.opm.gov/forms/standard-forms/

It looks like for this section there have been a lot of changes – eApp looks to correctly implement the questions in the November 2016 revision.

**Comment by bpdesigns** [comment]
After "yes" these are the questions that should occur:

Provide the date this occurred
[Month] [Year] [Estimated]

Provide the name of the mental health professional you consulted with.
[name field]

Provide the name of the mental health professional's agency, organization, or facility
[name field]

Provide the address of the mental health professional you consulted with
[address field]

Was this matter appealed to a higher court or administrative agency?
[y/n]
(if yes - it asks more questions which are okay as is)

See page number 87 of the SF86 pdf
<img width="1064" alt="screen shot 2018-06-11 at 10 48 34 am" src="https://user-images.githubusercontent.com/15329140/41248371-b4452970-6d65-11e8-9ef6-c1a086d650c3.png">

@ryanhofdotgov @line47 I have a hunch that these questions are already captured in the code BUT the wrong questions (from the competency section) are being loaded. 

I'm happy to chat more about this if more clarity is needed

**Comment by bpdesigns** [comment]
Hey @line47 @ryanhofdotgov sorry for the confusion! The only edit that needs to happen is when the user selects "yes" 

replace the question
"Provide the name of the court or administrative agency that **declared you mentally incompetent**." 

with
"Provide the name of the court or administrative agency that **ordered you to consult with a mental health professional**."

**Comment by line47** [comment]
Thanks @bpdesigns !
