### ISSUE TITLE
Verify uploaded attachments are not malware, active code, etc.

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#397]
Applicants can upload attachments as part of their applicant submission. To help ensure eApp does not permit malware, viruses, or active code to be uploaded and re-distributed to other systems, implement server-side mechanisms to perform the following checks:

- Use file content sniffing to limit uploads to PNGs, JPGs, and PDFs
- Run anti-malware software against attachments on upload, rejecting any malware positives
- Detect and reject PDFs with JavaScript

Any policy violations should result in the attachment upload API returning an error with no attachment persisted to the eApp database. 

Attachments must not be forwarded to other systems or permitted to be downloaded from eApp before all checks have passed.

**Comment by bpdesigns** [comment]
a good idea to implement before going live.

**Comment by bpdesigns** [comment]
@ryanhofdotgov can you verify if this is being done?

**Comment by ryanhofdotgov** [comment]
We don't support attachments yet, so it is still outstanding. The infrastructure team wants to use an external service deployed separately from eApp, we will probably need to have something in place ahead of that.

**Comment by ryanhofdotgov** [comment]
It appears as if the infrastructure team may have something in place for us to call within the time frame of the upcoming sprint.

**Comment by ryanhofdotgov** [comment]
Attachments are still not supported, with no immediate plans to implement.
