### ISSUE TITLE
bg color on loading screen should be white not gray

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#400]
**What did you do?**

signed in to eApp 

**What did you expect to see?**

I expected the bg of the loading screen to be white

**What did you see instead?**

the background color on the loading page is dark gray. 

<img width="1280" alt="screen shot 2018-06-11 at 10 57 16 am" src="https://user-images.githubusercontent.com/15329140/41252310-9eb6343a-6d71-11e8-9a61-305c928a8e18.png">

**Comment by ryanhofdotgov** [comment]
Not really an urgent issue, but since related to the change you made last week, appropriate to look at it  this week.
