### ISSUE TITLE
Clicking "No" to "I have read the instructions..." on login should sign you out

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#403]
**What did you do?**

Sign-in to eApp. Click "No" on the initial "I have read the instructions..." question.

**What did you expect to see?**

Application logged out, with some explanatory message.

**What did you see instead?**

Loading data screen, then the question asked again.

**Additional Information**

 If you wait long enough, and click "No" several times after waiting for loading screen again, you will eventually be directed to login screen on 3rd attempt.

Using latest Chrome on macOS. eApp running in SAML authentication mode.

**Comment by bpdesigns** [comment]
lgtm
