### ISSUE TITLE
Content - Error text - Common Middle Name Field

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#408]
Error text - Middle Name Field
Current text:
**There is a problem with the middle name** 
If the middle name is an initial then check the "Initial only" checkbox. 
and/or 
You are only allowed 100 characters.

Replace with:
**Oops, there’s a problem.** 
If your middle name is a single letter, please select the “\Initial only” checkbox and type the letter. 
100 character limit.

**Comment by line47** [comment]
There are 3 sets of errors for "**There is a problem with the middle name**"

-   title: 'There is a problem with the middle name',
        message: 'If there is no middle name then check the "No middle name" checkbox.',

- title: 'There is a problem with the middle name',
        message: 'If the middle name is an initial then check the "Initial only" checkbox.',
          '*and/or*', 'You are only allowed 100 characters.'

- title: 'There is a problem with the middle name',
        message: 'Some of these characters aren\'t allowed.',
        note: 'Only use letters, hyphens (-), periods (.), apostrophes (\'), and spaces.'

Which one of these gets that update @bpdesigns

**Comment by line47** [comment]
The third is for if you use some characters in the middle name like `#`, `$`,`+` etc...

**Comment by bpdesigns** [comment]
Okay. If its still a middle name field, we can replace that one with the new error text as well.

**Comment by bpdesigns** [comment]
Hi @line47 there are two related issues for first and last name # 453 and #454

**Comment by line47** [comment]
Awesome, thanks @bpdesigns

**Comment by line47** [comment]
@afeld If all of these errors are the same is there a way to consolidate the messages?

```
  middle: {
      required: {
        title: 'Oops, there’s a problem.',
        message: 'If your middle name is a single letter, please select the "Initial only" checkbox and type the letter. 100 character limit.',
        note: ''
      },
      length: {
        title: 'Oops, there’s a problem.',
        message: 'If your middle name is a single letter, please select the "Initial only" checkbox and type the letter. 100 character limit.',
        note: ''
      },
      pattern: {
        title: 'Oops, there’s a problem.',
        message: 'If your middle name is a single letter, please select the "Initial only" checkbox and type the letter. 100 character limit.',
        note: ''
      }
    },
```

**Comment by afeld** [comment]
@line47 The trick is tracking down where/how/if they're all used. See all the calls to `i18n.t()` in [the `Name` component](https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/Name/Name.jsx), for starters.
