### ISSUE TITLE
Proposal: Move save button into header for better UI/UX

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#432]
Currently the save button floats to the right on larger screens and floats to the bottom on smaller screens. Wondering about moving the save button into the header along with the logout and instructions link? 

This would keep the save button in a consistent location across all devices and would also address https://github.com/18F/e-QIP-prototype/issues/249 

Screenshots of idea
![screen shot 2018-06-18 at 1 15 33 pm](https://user-images.githubusercontent.com/1449852/41551921-43c7e160-72fb-11e8-8eea-5415d4cd4e62.png)
![screen shot 2018-06-18 at 1 15 44 pm](https://user-images.githubusercontent.com/1449852/41551922-43d93b9a-72fb-11e8-8220-5b62228a991b.png)

**Comment by afeld** [comment]
@bpdesigns ^

**Comment by bpdesigns** [comment]
Interesting idea. We may be able to change how it looks on smaller screens, but people have responded well in testing to the save button when it's on the side so I think we should keep it there. Its big and reassuring.
