### ISSUE TITLE
fix specs

### ISSUE THREAD

**Issue by afeld** [18F/e-QIP-prototype#441]
**What did you do?**

Ran `make specs`.

**What did you expect to see?**

Something...?

**What did you see instead?**

No output, and the process ended almost immediately, seemingly without running the specs.

**Additional Information**

Integration with CircleCI or NBIS self-hosted CI is out of scope for this ticket and will be a follow-on.

**Comment by ryanhofdotgov** [comment]
I've not dived into this area on the project yet, but essentially:
* there is a very small number of Selenium tests, no other integration testing
* these get kicked off via the process described [here](https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/blob/master/SPECTEST.MD) on very slim chance you didn't see it already
* the previous team did not feel they were appropriate to run in conjunction with the other automated tests that run CircleCI (primarily due to length of time)
* right before the previous team went off contract, we tried to re-focus efforts on getting a good integration test suite in place, but had to [downscope that effort quite a bit](https://github.com/ryanhofdotgov/e-QIP-prototype-truetandem/issues/2877) due to other end-of-contract concerns.

**Comment by afeld** [comment]
> the process described here

Heh, remembered that doc right after creating this issue. Thanks!

> the previous team did not feel they were appropriate to run in conjunction with the other automated tests that run CircleCI

What if we parallelized them, or ran nightly or something?

**Comment by ryanhofdotgov** [comment]
Right - running nightly seemed appropriate when the team discussed it last.

**Comment by afeld** [comment]
Repurposing this issue for getting the specs passing, not just running.

**Comment by line47** [comment]
Have all the PRs in for getting the specs working as they were written.
There is still more spec work to be done as a few of the specs had commented out sections.

In addition, there is some redundant code that can be refactored for example navigating to sections.

**Comment by ryanhofdotgov** [comment]
@line47 Just looking at it now... I get this error when I try to run `make specs`:
```
[e-QIP-prototype]# make specs
Running integration test suite
Starting eqipprototype_web_1 ... 
Starting eqipprototype_hub_1 ... done
Starting eqipprototype_chrome_1 ... done
Building nightwatch
ERROR: Forbidden path outside the build context: ../conf/docker/Dockerfile.frontend ()
make: *** [specs] Error 1
```
Does that work on your machine?

**Comment by ryanhofdotgov** [comment]
Ran into a different error after quickly trying to resolve above. As Scott's is focusing on design tasks for time being, moving this back to backlog. The underlying spec tests issues are resolved, it's just this top-level docker/build issue.

**Comment by ryanhofdotgov** [comment]
@line47 Is this something you think you pick up again and carry over the finish line?

**Comment by line47** [comment]
@ryanhofdotgov Yep - that sounds good!

**Comment by line47** [comment]
@apburnes I'd love your help getting Selenium/nightwatch working locally so I can begin to dive into these specs/tests

**Comment by apburnes** [comment]
@line47 sounds good! Should we look at it this afternoon?

**Comment by line47** [comment]
I'd love that ❤️

**Comment by ryanhofdotgov** [comment]
Originally thought that current state had the spec tests working and this was just a docker/Makefile issue (i.e, a light lift). 

Let's revisit in October. Scott and I believe it may have to do with using SAML authentication vs the simple authentication. As SAML authentication is the production configuration, I think it makes sense for the specs tests to be using that approach.

**Comment by ryanhofdotgov** [comment]
@gidjin For the scope of this ticket, it's just to have a documented process that runs whatever tests are there, not necessarily to make sure all the tests are passing; e.g., `make specs` should run the tests. If there are pre-reqs/environment conditions (e.g, BASIC_AUTH, etc.) for that to work, then those should be documented.
