### ISSUE TITLE
"Back to login" button label not displayed when session times out

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#450]
**What did you do?**

Sign-in, let eApp timeout due to lack of activity (10? minutes)

**What did you expect to see?**

Session timeout text, with blue button displaying "Back to login"

**What did you see instead?**

Session timeout text, with blue button without a visible label. Button label only renders (in white) when button is rolled over. See attached.

![screen shot 2018-06-19 at 11 56 27 pm](https://user-images.githubusercontent.com/37100189/41642316-cd9c4774-741c-11e8-838c-9d20e19a8ba5.png)
![screen shot 2018-06-19 at 11 59 28 pm](https://user-images.githubusercontent.com/37100189/41642320-cf36d43c-741c-11e8-9e55-d3b73d62b421.png)

**Additional Information**

Chrome 67.0.3396.87 on macOS 10.12

**Comment by line47** [comment]
Just tested locally from the `develop` branch and this appears to have been fixed. 
<img width="573" alt="screen shot 2018-07-09 at 2 59 48 pm" src="https://user-images.githubusercontent.com/1449852/42470533-c2b4cfc2-8388-11e8-814d-9bb03a9bffa5.png">

**Comment by line47** [comment]
I tried these exact steps but not in incognito mode. (I've also got the same system/browser settings) Giving this a test in incognito mode now 👍
