### ISSUE TITLE
Content - Help text - Common First Name Field

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#451]
Current Helptext for "First Name" 
**Don't abbreviate this name**
"Initial only" is for single letter names only, not for the first letter of this full name.
Note: If this first name is a single letter only type that letter and check the "Initial only" checkbox.

Replace with:  
**Enter a valid first name.** 
Please enter your entire first name.  If your first name is a single letter, select the “Initial only” checkbox and type the letter below.

**Comment by line47** [comment]
Am I getting rid of the **note** text for this and last name then?

The note text is "_Note: If this first name is a single letter only type that letter and check the "Initial only" checkbox._"

**Comment by bpdesigns** [comment]
yes
