### ISSUE TITLE
Content - Error text - Common Last Name Field

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#453]
Current error text for "Last Name" 
**Don't abbreviate this name**
"Initial only" is for single letter names only, not for the first letter of this full name.
Note: If this last name is a single letter only type that letter and check the "Initial only" checkbox.

Replace with: 
**Oops, there’s a problem.**
 If your last name is a single letter, please select the “Initial only” checkbox and type the letter.
 100 character limit.

**Comment by line47** [comment]
I don't see the error **Don't abbreviate this name**

I see the following
```
  required: {
        title: 'The last name is required',
        message: 'The last name must be provided.',
        note: ''
      },
      length: {
        title: 'There is a problem with the last name',
        message: [
          'You are only allowed 100 characters.',
          '*and/or*',
          'If the last name is an initial then check the "Initial only" checkbox.'
        ],
        note: ''
      },
      pattern: {
        title: 'There is a problem with the last name',
        message: 'Some of these characters aren\'t allowed.',
        note: 'Only use letters, hyphens (-), periods (.), apostrophes (\'), and spaces.'
      }
```
