### ISSUE TITLE
Content - Error text - Common First Name Field

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#454]
Current error text for "First Name" 
**Don't abbreviate this name**
There is a problem with the first name
You are only allowed 100 characters.
and/or
If the first name is an initial then check the "Initial only" checkbox.ox.

Replace with: 
**Oops, there’s a problem.**
 If your first name is a single letter, please select the “Initial only” checkbox and type the letter.
 100 character limit.

**Comment by line47** [comment]
I don't see the error **Don't abbreviate this name**

I see the following

```
  required: {
        title: 'The first name is required',
        message: 'The first name must be provided.',
        note: ''
      },
      length: {
        title: 'There is a problem with the first name',
        message: [
          'You are only allowed 100 characters.',
          '*and/or*',
          'If the first name is an initial then check the "Initial only" checkbox.'
        ],
        note: ''
      },
      pattern: {
        title: 'There is a problem with the first name',
        message: 'Some of these characters aren\'t allowed.',
        note: 'Only use letters, hyphens (-), periods (.), apostrophes (\'), and spaces.'
      }
```

**Comment by bpdesigns** [comment]
sorry, was copy and pasting some here. **Don't abbreviate this name** is part of the original helptext not error text. 

The "replace with" in my initial note is accurate and should replace all error messages for "first name"

**Comment by line47** [comment]
Thanks!
