### ISSUE TITLE
Hidden Instructions page

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#456]
**What did you do?**

Signed into eApp

**What did you expect to see?**

Show me this page so I can click to agree with the instructions
<img width="1254" alt="screen shot 2018-06-20 at 10 11 52 am" src="https://user-images.githubusercontent.com/15329140/41663880-71677f04-7472-11e8-8779-8e84d8e6ac24.png">

**What did you see instead?**

It took me to the first screen as if I already clicked the "Agree" button on the instructions page

<img width="817" alt="screen shot 2018-06-20 at 10 12 04 am" src="https://user-images.githubusercontent.com/15329140/41663897-7a3b2036-7472-11e8-8a36-c271cb779ba8.png">

**Additional Information**

This happens when the width of screen is narrowed. What it looks like to me is that the instructions screen is hidden on narrow windows.

 - What browser and version are you using?
chrome
 - What operating system?
mac

**Comment by afeld** [comment]
There are a number of bugs like this that boil down to "doesn't work well on narrow screens".

**Comment by bpdesigns** [comment]
agree. @ryanhofdotgov thoughts on this being a high priority ticket? I don't know what happens if you don't see and accept the instructions. Does none of the content save in that case?

**Comment by line47** [comment]
The `.introduction-modal` is being hidden at screen sizes that are smaller than 1000px. 
I'm guessing we want to show this modal to all users correct @ryanhofdotgov @bpdesigns

**Comment by line47** [comment]
Also as @afeld said above there are quite a few small screen issues I've seen as well

**Comment by bpdesigns** [comment]
Yes please show to all users.
