### ISSUE TITLE
DSN phone number text placement overlap issue 

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#457]
**What did you do?**

viewed any screen with a phone number input and selected "Switch to: DSN number"

**What did you expect to see?**

I expected to see the "DSN number" header above the input fields

**What did you see instead?**

text overalp
<img width="994" alt="screen shot 2018-06-20 at 11 15 40 am" src="https://user-images.githubusercontent.com/15329140/41667692-98d7b10e-747b-11e8-9e41-90d8d1df6768.png">

**Additional Information**

This is an issue when the screen width is small

- What browser and version are you using?
 - chome
 - IE 11

- What operating system?
 - Mac
 - Windows

This is related to #224

**Comment by line47** [comment]
This is related to #224
