### ISSUE TITLE
Spacing under close button on accordions 

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#460]
The line under the word "Close" should match the distance to the word as in the type under "person 1" in the example below. 

<img width="731" alt="screen shot 2018-06-20 at 3 53 28 pm" src="https://user-images.githubusercontent.com/15329140/41686087-c90b094a-74b0-11e8-92bd-9541246973b9.png">

**This occurs when** an accordion element it scrolled up and turns into a sticky header. 

**Browser**
Chrome
**System**
Mac

**Comment by ryanhofdotgov** [comment]
This has been overcome by events – "Close" doesn't have a line under it any more.
