### ISSUE TITLE
Remove placeholder text 

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#467]
Remove placeholder text in the cases below. The text does not add to assisting an applicant to the content to enter in the fields and may make them think they have already filled them out if they are skimming the page

**Provide your place of birth**
(If yes)
**City** 
Remove "Please enter your city of birth"

**State or territory** 
Remove "Please enter state or territory within the United States"

**County or province**
Remove "Please enter your county or province of birth"

<img width="600" alt="screen shot 2018-06-25 at 5 59 18 pm" src="https://user-images.githubusercontent.com/15329140/41878042-8ca320a6-78a1-11e8-9aba-a2a165fa30ed.png">

(If no)
**City**
Remove "Please enter your city of birth"
**Country**
Remove "Please enter your country of birth"

<img width="602" alt="screen shot 2018-06-25 at 5 59 14 pm" src="https://user-images.githubusercontent.com/15329140/41878034-8645da5a-78a1-11e8-9ffd-2bb3e1522a89.png">

For all address blocks 
**Street address** (applies when 'inside the United States" and 'outside the United States' buttons are selected)

Remove text pre-filled in the field "Enter street address"

<img width="591" alt="screen shot 2018-06-25 at 5 57 55 pm" src="https://user-images.githubusercontent.com/15329140/41877981-5285a6d2-78a1-11e8-90c0-ebe610bb7811.png">

**Address** (applies when 'APO/FPO/DPO' button is selected)
Remove text pre-filled in the field "Enter address"

<img width="597" alt="screen shot 2018-07-18 at 9 36 20 am" src="https://user-images.githubusercontent.com/15329140/42885109-1acca112-8a6e-11e8-9087-fc08cee91179.png">

**Comment by bpdesigns** [comment]
This should apply for all address blocks not just for "place of birth"

**Comment by line47** [comment]
I think this should apply to all text boxes or text areas. Related to https://github.com/18F/e-QIP-prototype/issues/730
