### ISSUE TITLE
unable to navigate to nested sections

### ISSUE THREAD

**Issue by afeld** [18F/e-QIP-prototype#472]
**What did you do?**

1. Log in
1. Click `Relationships`
1. Click `Marital & relationship status`

**What did you expect to see?**

That section expand.

**What did you see instead?**

* Browser URL turned into `http://localhost:8080/form/identification/javascript:;;`
* Form was blank

**Additional Information**

This is a regression introduced in the past week or so.

**Comment by ryanhofdotgov** [comment]
These issues appear to be related: https://github.com/18F/e-QIP-prototype/issues/455 https://github.com/18F/e-QIP-prototype/issues/447
