### ISSUE TITLE
Previously saved data is not displayed

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#481]
**What did you do?**

Log in, enter my first name in the first section, under a fresh application (no previous data), Log out.

**What did you expect to see?**

See my first name when I sign back in, already pre-populated, loaded from the database.

**What did you see instead?**

Blank field.

**Additional Information**

Using latest Chrome under macOS 10.12.

**Comment by afeld** [comment]
I was able to reproduce on https://eqip-prototype-dev.fr.cloud.gov/ but not locally.

**Comment by afeld** [comment]
Tried with both. The request to `/me/form` is coming back empty (`{}`), but weirdly not when I [`Copy as cURL`](https://developers.google.com/web/updates/2015/05/replay-a-network-request-in-curl).

**Comment by afeld** [comment]
Heh, we had [`FLUSH_STORAGE=1`](https://github.com/18F/e-QIP-prototype/blob/5c7acdb78265ff0d9106ecde99ff69e0d576c01a/conf/manifests/api-dev.yml#L24). _It's a feature._ 😒
