### ISSUE TITLE
Form field validation occurs almost immediately

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#492]
**What did you do?**

Sign in, type in the first name field something invalid (e.g, "R", or "4")

**What did you expect to see?**

No validation until I tab out of field/click on an other form element.

**What did you see instead?**

Validation of the field contents happens almost immediately. 

**Additional Information**

Regression on `develop` branch since `v0.5.4`. Can see correct behavior on https://eqip-prototype.fr.cloud.gov

Using latest Chrome on macOS 10.12.

**Comment by afeld** [comment]
Hmm, I've seen this before as well, but not able to reproduce locally or on https://eqip-prototype-dev.fr.cloud.gov/ as of a50dac8ae7e4a5a929cb3f073a82e53b64de6054. Wondering if there's some certain application state that causes it?

**Comment by afeld** [comment]
@ryanhofdotgov Should we close, or look for it harder?

**Comment by ryanhofdotgov** [comment]
I'll try it locally one more time before closing – thanks.

**Comment by line47** [comment]
I'm not able to reproduce this locally either. I only get error validation when clicking or tabbing out of a field without completing

**Comment by ryanhofdotgov** [comment]
Can't reproduce any more either locally – closing.
