### ISSUE TITLE
Can't browse list of countries

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#493]
**What did you do?**

Tried to type in "Federated States of Micronesia" into a country field.

**What did you expect to see?**

No error. Or if an error, list of approved countries I could browse through – this is the main issue, there is no discoverability of what is the current list of countries the form will accept.

**What did you see instead?**

Validation error, saying "This Country is not on our current list".

**Additional Information**

Using Chrome 67.0.3396.99 on macOS 10.12

@bpdesigns – any design guidance?

**Comment by bpdesigns** [comment]
Can we add "other" to the country list? and update validation error to say: "If you don't see your country in the list, please select "other" and add a comment to clarify your response."

Or

If you don't see your country in the list, select the country that represents the location you are referring to most closely. Add a comment to clarify your response.

**Comment by bpdesigns** [comment]
probably the second option is best.

**Comment by ryanhofdotgov** [comment]
The challenge with having "other" is that it doesn't address the desire to guide applicants to the standardized form of the country. Also, just to be clear, there is never a full list to select from – you have to type something and only see a subset that matches the characters you typed. If you haven't seen the UI recently, give it a spin.

**Comment by bpdesigns** [comment]
Yeah, I see that. Looks good. My comment for "other" was thinking about contingencies if someone wants to enter a country that is not on the list. Is that a concern?

**Comment by ryanhofdotgov** [comment]
I think I'm confused, sorry – what's your recommendation for the use case in the description. Is it a standard drop-down with ~200 countries and "Other"?

**Comment by bpdesigns** [comment]
Sorry for the confusion. Lets keep the list and change the error message to say:

 "If you don't see your country in the list, select the country that most closely represents the location you are referring to. Add a comment to clarify your response."
