### ISSUE TITLE
Clicking "add another email" or "add another phone number" scrolls page to wrong location

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#494]
**What did you do?**

Don't fill out any information in "Information about you" except for first name/last name. Click on Review for that section. Click on "add another email" (or "add another phone number"), when no initial email has been filled out. 

**What did you expect to see?**

The "add another email" button disabled, or no action taken when clicked.

**What did you see instead?**

Form scrolls down to social security number section when clicked.

**Additional Information**

Latest version of Chrome on macOS.

**Comment by bpdesigns** [comment]
This happens when you try to add a phone number in the review screen as well
