### ISSUE TITLE
Misleading error message when no validation service configured

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#497]
**What did you do?**

Using an eApp instance without validation enabled, fill out a US-based address field.

**What did you expect to see?**

Pop-up that validation is disabled or unavailable, warning to proceed with address. Or no validation pop-up at all.

eApp should gracefully handle situation where USPS validation service is not available.

**What did you see instead?**

"Multiple address found" error displayed in pop-up. See screenshot.

<img width="582" alt="screen shot 2018-07-02 at 11 22 12 am" src="https://user-images.githubusercontent.com/37100189/42179968-4dfc4690-7dea-11e8-89bb-a53a27e3f16e.png">

**Additional Information**

Chrome 67.0.3396.99 on macOS 10.12

**Comment by bpdesigns** [comment]
@ryanhofdotgov when would someone see eApp without validation configured?

**Comment by ryanhofdotgov** [comment]
It wouldn't be a normal event, but there are few exceptional cases:
* USPS service could be down
* app could be deployed incorrectly without a USPS token (how to get a token was only recently documented, so I suspect other parties that have been deploying eApp haven't been getting their own token)
* USPS could (mistakenly) flag our USPS token as violating their terms of service unexpectedly

**Comment by bpdesigns** [comment]
Makes sense. Got it.

Do we just give any address entered the green light? 
-The only problem with that could be if/when the validation is up an running again. 

Maybe this need to raise an error message? 
- "Address validation is temporarily disabled. You can complete the rest of the form... something something...
