### ISSUE TITLE
Proposal: Simplify error UI and update to match USWDS 

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#514]
- Simplifying the list displayed to only show the links thus making the list not so long and still keeping the relevant context
- Using the alert styling from the USWDS
- Moving the number of errors title into the error alert itself
- Removing the font-awesome `!` icon in the HTML 

### Current error
<img width="691" alt="screen shot 2018-07-09 at 1 13 12 pm" src="https://user-images.githubusercontent.com/1449852/42465789-0122e810-837b-11e8-88b2-641bc213b80c.png">

### Proposed update
<img width="736" alt="screen shot 2018-07-09 at 1 18 22 pm" src="https://user-images.githubusercontent.com/1449852/42465790-02e82cbe-837b-11e8-8364-2e683ce4fdc8.png">

@bpdesigns what do you think about something like this?

**Comment by bpdesigns** [comment]
I like how you're thinking about this @line47 but there are contextual impacts of this.

Removing Header:
- For items that are generic repeating fields like "United States Telephone Number" and when there are  options to add multiple entries like number of relatives, the header provides needed context. 
<img width="984" alt="screen shot 2018-07-09 at 3 50 28 pm" src="https://user-images.githubusercontent.com/15329140/42473330-5d4fcde4-8392-11e8-8907-8f0901bf9414.png">

Error Styling 
- this happens on individual fields as well as on review pages, so the styling would need to change there. 
-the styling also matches the helptext styling but in a different color. That would also need to change for consistency. 
<img width="570" alt="screen shot 2018-07-09 at 3 51 35 pm" src="https://user-images.githubusercontent.com/15329140/42473327-57e0df10-8392-11e8-9c45-dc58772c539c.png">

Error Icon, 
- this icon shows up to signal in the nav where there are errors in a section as well as on the error message box. So both would need to be changed at once for consistency. 
<img width="396" alt="screen shot 2018-07-09 at 3 50 38 pm" src="https://user-images.githubusercontent.com/15329140/42473318-4d65f3e0-8392-11e8-8c23-cbdd71bc9b05.png">
