### ISSUE TITLE
Don't send internal errors in JSON response

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#526]
eApp transmits internal error details in the body of a JSON response via the `EncodeErrJSON` call. Instead, log the detailed error meta-data, returning only a generic error response. 

See:
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-70253
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-70273
https://www.stigviewer.com/stig/application_security_and_development/2017-12-18/finding/V-70275

**Comment by afeld** [comment]
Especially given that the app is open source, I'd argue that this is security by obscurity.

**Comment by ryanhofdotgov** [comment]
* It's still an official rule we have to comply with or convince a DoD program office to waive off because it's a DoD application – it's way easier to comply with it then get a waiver :)
* It's not limited to DoD – OWASP has similar recommendation:
https://www.owasp.org/index.php/Error_Handling#Generic_error_messages
* I disagree with security by obscurity argument here – speaking very broadly, the application doesn't have a good idea of what the error value is, especially if it is bubbling up from a lower-level SAML, encryption, or system library. A generic error doesn't have to mean just a 500 error, it can be context specific, but just needs to be explicitly returned, instead of potentially sending out paths, user ids, pids. The error returned needs to be at the level of the abstraction provided by the web service API.

**Comment by ryanhofdotgov** [comment]
Here's a good (really bad) example that came back in the JSON response to `/auth/basic`:
<img width="451" alt="screen shot 2018-07-16 at 9 51 54 pm" src="https://user-images.githubusercontent.com/37100189/42797107-7aa830f6-8942-11e8-9b0a-197d511ad048.png">

 `/auth/basic` is getting deep-sixed, but other API calls can leak similarly.
