### ISSUE TITLE
Review errors show  "en.error.required.message" string

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#542]
**What did you do?**

On a partially filled out Introduction section, click the Review sub-section menu.

**What did you expect to see?**

Full list of validation errors, with meaningful error messages.

**What did you see instead?**

For many of the error messages I saw: "Your response is required" followed by "en.error.required.message"

<img width="296" alt="error message" src="https://user-images.githubusercontent.com/37100189/42548417-c3119786-847b-11e8-9dad-a14963942d45.png">

**Additional Information**

Believe this is a regression on the `develop` branch.  Seen with latest Chrome on macOS 10.12 and IE11 on Windows 8.1.

**Comment by line47** [comment]
Looks like I caused this issue with #409 and need to modify this bit of code to not show the `message` when empty. https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/Field/Field.jsx#L228

**Comment by ryanhofdotgov** [comment]
I think the problem is a little bit farther up:
https://github.com/18F/e-QIP-prototype/blob/develop/src/components/Form/Field/Field.jsx#L19

`message()` already does the correct thing for `note`, it needs to do the same thing for `message`. Might need to tweak all the extra spacing, if using empty string for those values still creates new lines in the div (and those lines are undesirable).
