### ISSUE TITLE
Remove asterisks throughout eApp

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#543]
Action: Remove asterisks throughout eApp
Rationale: All items that are not currently marked "optional" or have explanation text saying "provide at least one..." are required. The asterisk is redundant and we do not call out anywhere on the app that "*" = "required". It is just an assumed shorthand. Also, as you proceed through the app fields that are required that are not entered are flagged with an error. 

Note: This supersedes all issues related to asterisks.

**Comment by line47** [comment]
Hey @bpdesigns Can you close the other asterisks issues that are not relevant?
Here is a search of issues - https://github.com/18F/e-QIP-prototype/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+asterisks

**Comment by bpdesigns** [comment]
@line47 Done!

**Comment by line47** [comment]
Awesome! Thanks Ben!
