### ISSUE TITLE
Don't display horizontal scrollbars in the menu

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#550]
**What did you do?**

Expand Relationships section in navigation menu

**What did you expect to see?**

Menu items displayed, no horizontal scrollbar.

**What did you see instead?**

Menu items displayed, with horizontal scrollbar.

**Additional Information**

Believe it is consequence of nav menu rebuild in #482.

Seen under latest Chrome under macOS 10.12, IE11 on Windows 8.1. Window size on Chrome was 1280 x 736.

<img width="640" alt="screen shot 2018-07-13 at 12 07 21 pm" src="https://user-images.githubusercontent.com/37100189/42717773-4bae2e9a-86b8-11e8-8c5d-87c9f302cf8e.png">

**Comment by bpdesigns** [comment]
Looks good on Mac. Confirm this is still an issue on windows

**Comment by ryanhofdotgov** [comment]
Still an issue on macOS Chrome – this might be browser window size dependent. 2 examples:

<img width="400" alt="screen shot 2018-08-06 at 2 04 56 pm" src="https://user-images.githubusercontent.com/37100189/43741009-ca3a2ab2-9981-11e8-8516-3c699f238112.png">
<img width="400" alt="screen shot 2018-08-06 at 2 04 49 pm" src="https://user-images.githubusercontent.com/37100189/43741017-ce0c6e48-9981-11e8-9899-43ca58474c47.png">

**Comment by bpdesigns** [comment]
gotcha

**Comment by line47** [comment]
Should this issue be closed @hursey013 @ryanhofdotgov ?

**Comment by hursey013** [comment]
@line47 yes, looks like it, thanks!
