### ISSUE TITLE
Left navigation menu should always display (if width of screen allows)

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#551]
**What did you do?**

With a medium/large desktop browser window (e.g.,1000 pixels in width), navigate to a vertically long page (e.g., Review page with lots of errors, before the app has been filled out). Scroll to bottom of the page.

**What did you expect to see?**

Navigation menu displayed to left of page content.

**What did you see instead?**

No navigation menu.

![screen shot 2018-07-13 at 4 27 38 pm](https://user-images.githubusercontent.com/37100189/42717972-bf6a2130-86b9-11e8-9319-4e117976c96f.png)

**Additional Information**

Believe it is consequence of nav menu rebuild in #482. 

Latest Chrome (67.0.3396.9) on macOS 10.12.

**Comment by afeld** [comment]
I'm not able to reproduce this...still seeing it?

**Comment by ryanhofdotgov** [comment]
Yeah, still seeing it on https://eqip-prototype-dev.fr.cloud.gov
