### ISSUE TITLE
remove logo from header and intro page

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#571]
Remove the logo from:
- the landing page
<img width="1143" alt="screen shot 2018-07-17 at 12 32 50 pm" src="https://user-images.githubusercontent.com/15329140/42831969-d3f876f4-89bd-11e8-9edd-a75e5c774127.png">

- header at full width
<img width="1143" alt="screen shot 2018-07-17 at 12 33 15 pm" src="https://user-images.githubusercontent.com/15329140/42831986-df76177a-89bd-11e8-8c4b-614d381fff57.png">

- header at narrow width
<img width="406" alt="screen shot 2018-07-17 at 12 33 36 pm" src="https://user-images.githubusercontent.com/15329140/42831997-e35aa4e6-89bd-11e8-8f77-5491baebc5cb.png">

- logout screen
<img width="1161" alt="screen shot 2018-07-17 at 12 45 25 pm" src="https://user-images.githubusercontent.com/15329140/42832528-79b8b922-89bf-11e8-80bc-568d8e0cbc02.png">

**Comment by ryanhofdotgov** [comment]
Just documenting that we are waiting for direction from current partner agency before making any changes to logos and branding.

**Comment by ryanhofdotgov** [comment]
Comment wasn't for you in particular – just documenting so anyone coming on
to the project and picking up tickets won't hop on it.
