### ISSUE TITLE
Residence duration gaps not flagged 

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#574]
**What did you do?**

Checked validation on residence addresses for differing lengths of time and different size gaps.

**What did you expect to see?**

I'd expect all gaps in residences greater than 30 days to flag.

**What did you see instead?**

Gaps between residences larger than 30 days are not flagged if an applicant provides 10 years or more of housing. The gaps between residences larger than 30 days _are_ flagged if the total residences submitted sum to less than 10 years.

**Additional Information**
See photos attached.
We should also check employment timelines. 

 - What browser and version are you using?
Chrome
 - What operating system?
macos

**Comment by michaelccata** [comment]
<img width="759" alt="screen shot 2018-07-17 at 1 02 12 pm" src="https://user-images.githubusercontent.com/4422873/42833554-62103c48-89c2-11e8-8005-843f4d661760.png">
^ is the response that shows gaps if the dates provided sum to less than 10 years of residence history

**Comment by michaelccata** [comment]
<img width="802" alt="screen shot 2018-07-17 at 1 09 44 pm" src="https://user-images.githubusercontent.com/4422873/42833656-b1f68c62-89c2-11e8-94e8-ad785410661f.png">
^ residence gap greater than 30 days is not flagged if the sum total of history submitted is greater than 10 years

**Comment by michaelccata** [comment]
<img width="848" alt="screen shot 2018-07-17 at 1 11 45 pm" src="https://user-images.githubusercontent.com/4422873/42833730-ff40049e-89c2-11e8-8a76-ba8f7f216977.png">
^ residence gap greater than 30 days is flagged if the sum total of history submitted is equal to 10 years

**Comment by ryanhofdotgov** [comment]
Fixed by https://github.com/18F/e-QIP-prototype/pull/734
