### ISSUE TITLE
remove question - marital 

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#579]
**What did you do?**
On the marital section selecting - "Divorced/Dissolved, Widowed, or Annulled" opens a new question 
that re-asks the same thing. see below:
<img width="1247" alt="screen shot 2018-07-17 at 2 08 00 pm" src="https://user-images.githubusercontent.com/15329140/42837212-65aa5484-89cb-11e8-8857-7bdc3a3b50fb.png">

**Additional Information**
remove "provide status" question
NOTE: make sure that if the applicant selects  "Divorced/Dissolved, or Annulled" the question "is this person deceased?" is still asked

**Comment by afeld** [comment]
cc #577

**Comment by bpdesigns** [comment]
This is addressed elsewhere
