### ISSUE TITLE
Resolve high/medium Snyk issues on `specs/package.json`

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#583]
**What did you do?**

Navigate to https://snyk.io/org/eapp/projects

**What did you expect to see?**

No high or medium severity items for `specs/package.json`

**What did you see instead?**

3 high, 1 medium severity items.

**Additional Information**

Can use `depcheck` to find unused packages, I've used this option:
`--specials=bin,webpack,eslint,babel` on the app itself, but perhaps limited use here.

Recommend try getting specs working again (https://github.com/18F/e-QIP-prototype/issues/441) before updating/removing unused packages to resolve Snyk items.

**Comment by afeld** [comment]
https://github.com/nightwatchjs/nightwatch/wiki/Migrating-to-Nightwatch-1.0

**Comment by ryanhofdotgov** [comment]
Dependent on #441
