### ISSUE TITLE
Scan API dependencies for vulnerabilities

### ISSUE THREAD

**Issue by afeld** [18F/e-QIP-prototype#584]
**What did you do?**

Had a vulnerable Golang package dependency that we weren't aware of.

**What did you expect to see?**

A notification saying we need it to be resolved.

**What did you see instead?**

Nada

**Additional Information**

Broken out from other Snyk work in https://github.com/18F/e-QIP-prototype/issues/121#issuecomment-404321786.

https://snyk.io/docs/snyk-for-golang

**Comment by afeld** [comment]
Submitted a help request, since I don't seem to be able to add it.

**Comment by afeld** [comment]
Oh, apparently I didn't read the instructions closely enough:

> Go projects are currently working with CLI only. We'll be bringing Go support to our SCM integration soon (currently slatted for Q4),

**Comment by afeld** [comment]
May need to do that scanning [through CI](https://snyk.io/docs/ci) in the meantime.

**Comment by ryanhofdotgov** [comment]
Mitigated by separate system self-hosted by partner agency
