### ISSUE TITLE
New releases don't invalidate cache?

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#588]
**What did you do?**

Browse to https://eqip-prototype.fr.cloud.gov after a release.

**What did you expect to see?**

eApp navigation menu rendered correctly.

**What did you see instead?**

In Chrome, navigation menu missing UI elements (border, menu divisions, etc.)

<img width="1269" alt="screen shot 2018-07-17 at 5 12 46 pm" src="https://user-images.githubusercontent.com/37100189/42951280-af290762-8b2a-11e8-8706-4f8ae20a7f94.png">

Looked fine in Safari.

**Additional Information**

Reported by @bpdesigns. Believe this is caused by JavaScript or CSS being cached by Chrome from a previous release. Hypothesis is that we need to make sure etags is working or add some release-specific URL to the static resources so a new release won't use cached browser assets from a prior release.

Work-around is to clear browser cache, use incognito browser window, etc.

**Comment by hursey013** [comment]
There are cache-busting plugins for both webpack and gulp, so we could use those to apply a hash or timestamp to the css and js files when they are updated.

**Comment by afeld** [comment]
https://webpack.js.org/guides/caching/
