### ISSUE TITLE
Sub-section/section green/red indicators not consistently displayed

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#612]
**What did you do?**

Skip providing an answer for a yes/no question in the Foreign contacts sub-section:
<img width="400" alt="screen shot 2018-07-27 at 12 00 30 pm" src="https://user-images.githubusercontent.com/37100189/43341899-bec7b6de-9195-11e8-82c9-eb46d62772d5.png">

Click on Review for the section

**What did you expect to see?**

 I would expect some errors being shown for that sub-section ("Foreign contacts") – red dot once you hit Review –  and the section ("Foreign associations") – red exclamation point once you hit review.

**What did you see instead?**

Indicators are absent  or show green-checkmark for sub-section/section, respectively:

<img width="400" alt="screen shot 2018-07-27 at 12 07 01 pm" src="https://user-images.githubusercontent.com/37100189/43341981-0610a06e-9196-11e8-916a-2f9f1c8e4ade.png">

Similar issue when you click on overall Review section:
<img width="400" alt="screen shot 2018-07-27 at 12 07 43 pm" src="https://user-images.githubusercontent.com/37100189/43342045-4138e9ee-9196-11e8-9a23-9def6f5a8e4b.png">

**Additional Information**

Related to the specific type of question (lack of input, rather than bad input).

**Comment by christopherhuii** [comment]
Thinking out loud:

![screen shot 2018-10-17 at 2 40 40 pm](https://user-images.githubusercontent.com/8367504/47117976-c885e180-d21a-11e8-960c-15cae67cc3c9.png)

The image above is a screenshot of the [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) application state. It is of `application.Errors.identification`.

After I logged in, I clicked `Review` in the Navigation menu under `Information about You`. Then I navigated to the Redux DevTools to see which errors were logged. After taking a brief look at the errors, there is an error that looks suspicious to me. I think it's a bug:

```
{
    code: "required",
    valid: false,
    uid: "undefined-59b806fe-00d4-1550-03be-dcacf2b72ce7",
    section: "identification",
    subsection: "physical"
}
```

I'm working on trying down where/how errors are generated. Hopefully this knowledge helps sparks an idea of where and how to solve this issue.

**Comment by christopherhuii** [comment]
1. `docker-compose down -v`
2. `make run`
3. Login and Navigate to `5. Military history` and click `Review`
4. Notice that there will be 3 errors: `Selective service record`, `U.S. military`, `Foreign military`.
5. Open [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en) and click on the `State` tab to view `application.Errors.military`.

The error should resemble:
```
{
    code: "required",
    valid: false,
    uid: "undefined-c0f2068e-c093-4cc3-ce4b-d6ae2dce8812",
    section: "military",
    subsection: "foreign"
}

The error in the Redux store is buggy, but the confusing part is the `<ErrorList />` component has different errors than the errors that are in the Redux store. This means that the errors in the `<ErrorList />` component are different from what errors control the red/green indicator in the Navigation Menu.

**Comment by ryanhofdotgov** [comment]
This is being deferred until a comprehensive plan for addressing foundational validation issues is put in place. This ticket will likely just get resolved as an outflow of that.
