### ISSUE TITLE
Require phone number for someone who can verify unemployment

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#654]
**What did you do?**

Specified a period of unemployment on form. Specified a person who could verify and their address. No phone number was given. Submit to e-QIP.

**What did you expect to see?**

No errors on submission.

**What did you see instead?**

Error requiring that phone number be provided for the person verifying period of unemployment.

**Additional Information**

Specifically was testing unemployment branch, but issue probably affects all types of employment as there is a "I don't know" option available for phone number.

Pages 49, 51 in [Validation Matrix](https://drive.google.com/open?id=1_lIHjuKC2t8hNWOnKJDOAdF7Z7e8ylAI) confirms requirement; i.e., "I don't know" should not be an option.

<img width="400" alt="screen shot 2018-08-06 at 9 50 34 am" src="https://user-images.githubusercontent.com/37100189/43729738-0bd25e96-995e-11e8-9838-5e6b27ff4a2b.png">

**Comment by apburnes** [comment]
@ryanhofdotgov While working through the unemployment section, I noticed it asks about "fired" or "reprimanded" in the past seven years.  Can these be removed for unemployment?

<img width="660" alt="screen shot 2018-09-20 at 11 17 52 am" src="https://user-images.githubusercontent.com/693815/45838612-ff71e180-bcc6-11e8-89ae-350850eb5fd5.png">

**Comment by ryanhofdotgov** [comment]
@apburnes Yeah, there's another one too. I just opened one for the ones you describe above:
https://github.com/18F/e-QIP-prototype/issues/841
