### ISSUE TITLE
DSN number layout is broken

### ISSUE THREAD

**Issue by line47** [18F/e-QIP-prototype#661]
**What did you do?**
- Go to a section of the application where phone number is asked for with the option of DSN or international number. 
- Click on DSN number
- You see the broken layout

**What did you expect to see?**
- I expected to see the label for the DSN number

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
- The label to be visible when clicking on DSN number

**What did you see instead?**
- a broken layout where the DSN label was hidden

*Include a high-level description of the feature or error here*

**Additional Information**

![screen shot 2018-08-09 at 9 34 09 am](https://user-images.githubusercontent.com/1449852/43902272-a164a332-9bb7-11e8-8821-e44ade8b0956.png)

**Browser/System**
Browser - Chrome Version 67.0.3396.99
System - Mac 10.12.6
All window sizes

**Comment by afeld** [comment]
What browser(s) and screen size?

**Comment by line47** [comment]
Updated my original issue with the info @afeld

**Comment by ryanhofdotgov** [comment]
Just fixing the DNS --> DSN typo so it could be found via search more easily.

**Comment by line47** [comment]
This issue already exists #457, closing
