### ISSUE TITLE
Add Go to README dependencies

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#662]
**What did you do?**

Follow the "Initial setup" instructions found in the repo's README .
Run the command `mkdir -p $GOPATH/src/github.com/18F`

**What did you expect to see?**

The terminal successfully create a new directory

**What did you see instead?**

`GOPATH` is not set

*Include a high-level description of the feature or error here*

Since we are relying on Go in our installation instructions and not everyone may have it installed and/or have the paths exported correctly, we should list along with the other `Dependencies` in the "Initial setup" portion of the README.

**Additional Information**

 - What browser and version are you using?
 - What operating system?
Mac OS

**Comment by afeld** [comment]
Since the Go builds happen in a container, we can probably take out that step entirely. Sound good @ryanhofdotgov?
