### ISSUE TITLE
flush command does not delete all data

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#682]
**What did you do?**

`flush test01` after shelling into api container.

**What did you expect to see?**

No errors in log

**What did you see instead?**

```
db_1   | ERROR:  update or delete on table "texts" violates foreign key constraint "signatures_name_id_fkey" on table "signatures"
db_1   | DETAIL:  Key (id)=(399) is still referenced from table "signatures".
db_1   | STATEMENT:  DELETE FROM "texts" AS "text" WHERE "text"."id" = 399
```

**Additional Information**

Be sure to sign documents and release when trying to reproduce.

**Comment by afeld** [comment]
Another way: `docker-compose down db`.
