### ISSUE TITLE
Document browser testing priorities

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#688]
Something like:
For really basic changes, Chrome only is fine. For basic changes, Chrome and IE11. Officially for desktop we support latest Chrome, Firefox, Safari, Edge and IE11, but don't recommend doing that until we are making major changes. On mobile, latest mobile Safari and mobile Chrome,

**Comment by afeld** [comment]
Also the intended browser support. cc #594
