### ISSUE TITLE
build out SF-85

### ISSUE THREAD

**Issue by afeld** [18F/e-QIP-prototype#695]
This is a placeholder issue - just wanted to quickly note down how I would go about building a different background check form (the SF-85 or SF-85P). Rather than forking the project, I would have separate file trees in this repository: one for each form.

The good news is: much of the code under `src/` should be reusable. Things that are especially specific to the SF-86 right now:

* `src/components/Section/`
* `src/config/navigation.js`

Where there are slight differences in the questions (say, `Full name` vs. `First` `Middle` `Last`), I would add new components under `src/components/Form/`, with their matching translations under `src/config/locales/en`, validations under `src/validators/`, etc.

You'd then need to be able to run/build one form vs. another, via an environment variable or whatever.

I don't know enough about the API to know what it would take to change there.

**Comment by afeld** [comment]
* [ ] Document all the paths above in [frontend.md](https://github.com/18F/e-QIP-prototype/blob/develop/docs/frontend.md)

**Comment by ryanhofdotgov** [comment]
Addressing via a different set of issues
