### ISSUE TITLE
Archival PDF doesn't print all the sections

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#701]
**What did you do?**

Save archival PDF after submitting.

**What did you expect to see?**

All the sections, fully expanded.

**What did you see instead?**

Just the very briefest summary for people the applicant knows, their relatives, employment, school, etc.

**Additional Information**

A painful, quasi-workaround is to go into each section with expandable content, open each entry for relative, workplace, school, etc. and print the section page or review page.

**Comment by afeld** [comment]
Did you happen to notice anything that's missing, specifically?

**Comment by afeld** [comment]
Also, I found this cumbersome to test...

**Comment by ryanhofdotgov** [comment]
Any place in the form that has a table with rows (e.g., employment records) that you can open/close via the UI is printed in the closed position. Right now, as a work-around I go to each of the Review sections, manually open all the sections, and print-to-PDF each review section page. Then merge the PDFs into one PDF to send to e-QIP test case reviewers.
