### ISSUE TITLE
Accordion title issues

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#712]
**What did you do?**

Created two accordions for "Summary of foreign financial support" on the Foreign national support
in the Foreign Associations section

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*
<img width="733" alt="screen shot 2018-08-20 at 9 55 40 am" src="https://user-images.githubusercontent.com/15329140/44344942-da881580-a45f-11e8-9b1d-a4182cfaedce.png">

the accordion titles were generic "Support 1:Provide details of foreign financial support below"

There should be some title after "Support #:" that indicates what is in the accordion. I recommend that the information show the name of the person supported.

Browser / system

Chrome
Mac

**Comment by bpdesigns** [comment]
Also an issue on "Foreign associations > Foreign business, professional activities, and government contacts > Employment"

See:
<img width="794" alt="screen shot 2018-08-20 at 10 04 03 am" src="https://user-images.githubusercontent.com/15329140/44345123-6bf78780-a460-11e8-8a26-19f68ca4c313.png">

Recommending similar solution to signify their difference with the name of the person associated with the employment.

**Comment by bpdesigns** [comment]
<img width="812" alt="screen shot 2018-08-20 at 10 20 20 am" src="https://user-images.githubusercontent.com/15329140/44345935-b0842280-a462-11e8-824b-f1a3dc788b9b.png">
The above section should show the full country name instead of the first initial

**Comment by line47** [comment]
I did but feel free to work on it if you want to build off of what I started https://github.com/18F/e-QIP-prototype/pull/1013
