### ISSUE TITLE
Normalize case of state abbreviations

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#716]
UI will accept and validate state abbreviations of mixed case; i.e., 'Or' instead of 'OR', 'Ca' instead of 'CA'. Accept mixed case input, but store uppercase version.

**Comment by christopherhuii** [comment]
What is the expected behavior when a user types "california" and clicks outside of the input field? Currently, it stores "california"; not "CA".

**Comment by ryanhofdotgov** [comment]
Yeah, that is not an anticipated result. :/ We only want users to be able to select/input and save the 2-letter state abbreviation (i.e., whatever is in the select list).

**Comment by christopherhuii** [comment]
Conflict fixed. There's a failing snapshot test, but it should be resolved once #1023 is merged
