### ISSUE TITLE
NBIB Reported Defects in XML

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#743]
Current list is here (go to _ISSUES_SUMMARY sheet):
https://docs.google.com/spreadsheets/d/1v7RKEqoJ9HP3jgDXHzkZtIFEtHaxacWoY6NEZS8ff1Q/edit#gid=197757717

**Comment by ryanhofdotgov** [comment]
The Will Fix issues in the spreadsheet have either been resolved or split up into separate GitHub issues. Marked as closed.
