### ISSUE TITLE
Review design of attachments page

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#751]
Need to re-evaluate the attachments page in light of 1.0 goals (and considering that its initial implementation was done in haste without a lot of upfront design/evaluation).

For 1.0:
* No Fax option
* No Other option

For 1.0, all that we want is ability to upload attachments,  download attachments previously uploaded, remove attachments previously uploaded.

**Comment by bpdesigns** [comment]
on it

**Comment by bpdesigns** [comment]
@ryanhofdotgov @line47 some design ideas for attachments for your review

3 options for what you see when you enter the page. I added a new concept here that the agency can either pick specific documents that user must upload (left), or write a comment directing the applicant with details on what the need to upload (center/ right)
![artboard 3 copy 17](https://user-images.githubusercontent.com/15329140/45237374-7d3bf300-b2ac-11e8-99aa-03b9fa3166de.png)

and a fourth idea for this initial upload screen
![artboard 3 copy 13](https://user-images.githubusercontent.com/15329140/45237547-05ba9380-b2ad-11e8-8ce8-9f6452837164.png)

these designs show the attachments page with content already uploaded. The design on the right shows a preview of a multi-page pdf, all show upload, download, preview and remove features. The accordion element with content is gray to indicate that is have been used. The blue color on the accordions indicate that an item has not be clicked on yet. 
![artboard 3 copy 15](https://user-images.githubusercontent.com/15329140/45237562-0f43fb80-b2ad-11e8-831c-c6c16c4bd6eb.png)

**Comment by bpdesigns** [comment]
Designs for attachments flow when there is a reviewer comment
- [Option 1](https://drive.google.com/open?id=1WTo50WqMPafsxbRa-EzcTWH3pgqoqYjE) 
- [Option 2](https://drive.google.com/open?id=15HsdZaG6Yi7RwsCx6SH4WuMbDDO9_NJv)

**Comment by bpdesigns** [comment]
@line47 see above

**Comment by ryanhofdotgov** [comment]
@bpdesigns So for the scenario today, where there is no agency requirements, you want it to look like the [center/right screenshots](https://github.com/18F/e-QIP-prototype/issues/751#issuecomment-419532435)? What does it look like when you expand the file attachment entry? 

One awkwardness with that design is that how you upload the 2nd file is differently than the 1st file. (Upload button in upper left vs add file in lower right)

**Comment by bpdesigns** [comment]
Sorry for the confusion. These were meant to be items for review. Below is my first design choice, but this requires that agencies are able to identify files that applicants need to attach. 
[attachments-091118 -v1.pdf](https://github.com/18F/e-QIP-prototype/files/2371868/attachments-091118.-v1.pdf)

With this being what you see if there was a review comment on a rejected application
- [option 1 ](https://drive.google.com/file/d/1WTo50WqMPafsxbRa-EzcTWH3pgqoqYjE/view)

**Comment by bpdesigns** [comment]
This is the second option. With or without the "Agency Comments" piece on the top with the ability for an agency to give a comment on what to attach)
![attachments-091118 -v2](https://user-images.githubusercontent.com/15329140/45375131-1a0ad300-b5c2-11e8-8dbf-c8dc089da032.png)

**Comment by ryanhofdotgov** [comment]
Thanks! Marking task as closed.

**Comment by line47** [comment]
I feel like breaking the accordion up into more than one clickable area would cause problems and would suggest going with something like a list with action buttons out to the right.

**Comment by bpdesigns** [comment]
I feel like @line47 makes a good point. Here's two alternatives where the action on click on the accordion just opens the table and reveals the other action.

**Option 1**
<img width="1011" alt="screen shot 2018-09-12 at 9 12 41 am" src="https://user-images.githubusercontent.com/15329140/45436282-6caac480-b680-11e8-9c80-7679be38788f.png">

 my only concern is that it might be a little busy when there are multiple items (see second image)
<img width="1004" alt="screen shot 2018-09-12 at 9 12 20 am" src="https://user-images.githubusercontent.com/15329140/45436206-3a996280-b680-11e8-8fb9-99dcdd258369.png">

**Option 2** My preferred solution
<img width="1241" alt="screen shot 2018-09-12 at 9 13 28 am" src="https://user-images.githubusercontent.com/15329140/45436320-8815cf80-b680-11e8-97c9-0c5aeb6235d2.png">

The only thing - which I don't think is a big deal - Is that it requires someone to open the accordion item to edit or preview. I think its probably unlikely there would be more than few items in the list.

**Comment by ryanhofdotgov** [comment]
Sorry for closing this ticket, it was in the Done column of the last sprint, so just closed it out with a bunch of other oes. If you are still working it, would you move it to the new sprint project?

**Comment by bpdesigns** [comment]
Its good to close. Lets go with option 2 in what I just shared. just wanted to capture the versions in case that doesn't test well.
