### ISSUE TITLE
Offense locations must not collect street address

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#755]
Offense locations must not collect street addresses, only City/County/ZipCode/State if US, City/Country if outside the US. 

Ditto for offense court locations, offense law enforcement agency.

See original SF-86 form, validation matrix, XSD. Currently worked around in e-QIP XML generation by forcing address layout in template.

Remove work-around in XML templates, template helper functions`locationOverideLayout` when UI fix is in place.

**Comment by el-mapache** [comment]
@ryanhofdotgov Do we still want to perform USPS address validation (can we?) with just the city/country/state/zip?

**Comment by ryanhofdotgov** [comment]
No USPS validation required/desired, but the front-end "native" US state/zip code validation should still get triggered.

**Comment by el-mapache** [comment]
@ryanhofdotgov gotcha, those are still validating as normal. Thanks!
