### ISSUE TITLE
Reconcile telephone online fields with paper form/e-QIP

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#761]
eApp uses the same telephone form field set for all telephone entry across the form:

<img width="300" alt="screen shot 2018-09-06 at 8 26 53 am" src="https://user-images.githubusercontent.com/37100189/45167760-aaa27700-b1ae-11e8-9e0a-124cefc868ce.png">

This is sort of consistent with the paradigm for the applicant's contact info on the paper form (and e-QIP):

<img width="300" alt="screen shot 2018-09-06 at 8 25 09 am" src="https://user-images.githubusercontent.com/37100189/45167822-cdcd2680-b1ae-11e8-8981-862132646197.png">

However, elsewhere on the paper form (and e-QIP) there is a different paradigm:
<img width="300" alt="screen shot 2018-09-06 at 8 25 20 am" src="https://user-images.githubusercontent.com/37100189/45167855-e3425080-b1ae-11e8-800c-db8ea60fb2ab.png">

There is also a mismatch on the eApp form with respect to quantity; e.g. you can only have one home phone number for the applicant in e-QIP, not multiple. You can only have one evening phone, not multiple (for other places).

**Comment by bpdesigns** [comment]
found this in note on phone block types in TT's folder. might help this issue https://docs.google.com/document/d/1z_NyDrfreDUDQ1zaJkpvLAgbuAFTjakDb0jsYUbYeOk/edit?usp=sharing
