### ISSUE TITLE
Rearrange questions on Employment page

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#762]
3 percent of all errors in one monthly army study was confusing employer with supervisor. I'm recommending this new question order so that similar questions for employer/supervisor are back to back to try and reduce this error 

- Select your employment activity
- Provide the name of your employer
- Provide the name of your supervisor
- Provide the rank/position title of your supervisor
- Provide dates of employment
- Select the employment status for this position
- Provide the most recent position title (change **the** to **your**)
- Provide the address of employment
- Is/was your physical work address different than your employer's address?
- [possible branch questions may follow this]
- Provide the physical work location of your supervisor
- Provide your employment telephone number
- Provide the email address of your supervisor
- Provide the telephone number for this supervisor

**Comment by bpdesigns** [comment]
@michaelccata referencing our slack communication earlier today

**Comment by bpdesigns** [comment]
@line47 recommending this content change for employment section

**Comment by bpdesigns** [comment]
I'm not sure grouping in that way would work. My read on the problem was maybe people read the word "supervisor" in the field as they are scanning and confused it with employment. My thought was to put the fields for employer and supervisor right after each other with the thinking if someone just filled out an "employer" field they would not think the next field for "supervisor" is asking for the exact same content. 

I also wonder @ryanhofdotgov  if its possible to do some kind of validation rule where the content written for the employer field can't match the content in the supervisor field.

A third idea would be to show first and last name fields and them combine those fields into one when submitting to eqip. The thinking would be the first and last fields would not allow the applicant to gloss over the question or confuse it with the employer field

**Comment by ryanhofdotgov** [comment]
Yeah, higher-level validation is not something that is currently fleshed out a whole lot, but it's definitely possible.
