### ISSUE TITLE
Can't disable attachments section

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#787]
Partner agency team says that `ATTACHMENTS_ENABLED=` config option doesn't actually disable the attachment section any more. 

Expected behavior is that the Attachments page doesn't show up in the navigation menu and clicking the next button in Psychological section brings you to the Review page.

**Comment by hursey013** [comment]
I wonder if this is also related to the `SESSION_TIMEOUT` var not being respected?

**Comment by ryanhofdotgov** [comment]
No, it looks like when the recent major refactor of the Navigation menu was done, the ability to hide subsection wasn't re-implemented? Here is some of the original logic from v0.5.3:
https://github.com/18F/e-QIP-prototype/blob/ece4f554f3caca43f1eab2128e3f8114f6972902/src/components/Navigation/Navigation.jsx#L147

I haven't found corresponding logic in the current version of the code yet.

I think this is consistent with some other problems I've seen where the last sub-section of the Psychological section is only supposed to be visible if you answer No to all the previous sub-section's main question.
