### ISSUE TITLE
Improve state/zip code check

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#793]
In #791 and #631, an internal state/zip code validation was added since USPS validation can be ignored by the user or be unavailable for whatever reason, and e-QIP will not accept applications if an address has a zip code that doesn't match the state.

The current implementation is inefficient as it's all done in the front end and at times can feel a bit sluggish to the user when invoked. See #791 and #631 for discussion on alternative implementations.

**Comment by michaelccata** [comment]
The zip code validation *incorrectly* triggers and flags as an error when selecting `Choose a previous address` and auto-populating the data. 

The data is correct and will only green check when clicking around the form. It also conducts another address validation at that point.

**Comment by michaelccata** [comment]
So! This get's really annoying when the USPS lookup is working really well. 😬 😂
