### ISSUE TITLE
Navigation sub-section hiding is not working as intended

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#795]
It looks like the recent Navigation menu refactor created a regression in the ability to hide subsections of the menu.

This is affecting attachments (https://github.com/18F/e-QIP-prototype/issues/787), and I also think the Existing Conditions sub-section in the Psychological section, possibly others.

Audit the code, looking for `hiddenFunc`, `hidden` usage in menu, compare with code in v0.5.3, particularly logic in that release's `src/components/Navigation/Navigation.jsx`

**Comment by hursey013** [comment]
Fixed with https://github.com/18F/e-QIP-prototype/pull/1334
