### ISSUE TITLE
Update Marriage buttons 

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#810]
For the question - "Provide your current marital/relationship status with regard to civil marriage, legally recognized civil union, or legally recognized domestic partnership."

### sf86 divides the answer options into these checkboxes
<img width="947" alt="screen shot 2018-09-17 at 5 12 30 pm" src="https://user-images.githubusercontent.com/15329140/45654175-914fd380-baa8-11e8-85cf-eb03e76c13c7.png">

- Never entered into a civil marriage, legally recognized civil union, or legally recognized domestic partnership
- Currently in a civil marriage, legally recognized domestic partnership or legally recognized civil union
- Separated
- Annulled
- Divorced/dissolved
- Widowed

### eApp divides the answer options into 
<img width="735" alt="screen shot 2018-09-17 at 6 30 30 pm" src="https://user-images.githubusercontent.com/15329140/45654186-a0368600-baa8-11e8-9930-24fe7e7962ac.png">

- Never entered into a civil marriage, legally recognized civil union, or legally recognized domestic partnership
- Currently in a civil marriage
- Currently in a legally recognized domestic partnership or legally recognized civil union
- Separated
- Annulled
- Divorced/dissolved
- Widowed
 
### Proposed further splitting "in a relationship" answer to be 3 options
- Currently in a civil marriage
- Currently in a legally recognized domestic partnership
- Currently in a legally recognized civil union

I know this adds another button to the list but I think it will make it clearer for people who are in a civil union or domestic partnership. and noticing how the SF-86 splits these out in 17.1 I think this keeps to what the spirit of the form  (see below) 

<img width="735" alt="screen shot 2018-09-17 at 6 30 30 pm" src="https://user-images.githubusercontent.com/15329140/45654186-a0368600-baa8-11e8-9930-24fe7e7962ac.png">

**Comment by bpdesigns** [comment]
@ryanhofdotgov for your 👀

**Comment by bpdesigns** [comment]
What I think this means for the eQIP archival copy is that we need to merge the eapp data from the  proposed buttons - "Currently in a civil marriage / Currently in a legally recognized domestic partnership / Currently in a legally recognized civil union"-  into one that matches the sf86 pdf - so: "Currently in a civil marriage, legally recognized domestic partnership or legally recognized civil union"

**Comment by ryanhofdotgov** [comment]
Where we currently are at is that NBIB is reviewing policy to see if it is OK for us to split it up at all in the existing eApp presentation (i.e., is splitting up civil marriage OK? do we have to make any changes to be compliant?). 

I agree that the current split is odd. Either put them all on one button like the top half of that SF-86 section (like NBIB has initially suggested), or split them all up, kind of like the bottom half of that section, as you've suggested.

**Comment by ryanhofdotgov** [comment]
Policy team came back and said make it just like e-QIP: https://github.com/18F/e-QIP-prototype/issues/918
