### ISSUE TITLE
USPHS Commissioned Corps is truncated on button label

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#819]
This is in employment history section:

<img width="673" alt="screen shot 2018-09-18 at 8 39 02 am" src="https://user-images.githubusercontent.com/37100189/45699116-54bebf00-bb1e-11e8-8672-77bd209f5129.png">

**Comment by line47** [comment]
Is this when printing or in a certain browser I'm not able to reproduce in Chrome @ryanhofdotgov

**Comment by ryanhofdotgov** [comment]
Sorry, this is when printing to PDF in macOS using latest Chrome, similar to #820.
