### ISSUE TITLE
Truncated text in alcohol abuse/illegal drugs section

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#820]
See attached hand-generated eApp archival PDF, pages 123 and 137. Use PDF to identify section pages that need to be updated. Screenshots also below.

[test2a-archival-5546.pdf](https://github.com/18F/e-QIP-prototype/files/2393486/test2a-archival-5546.pdf)
<img width="300" alt="screen shot 2018-09-18 at 8 52 08 am" src="https://user-images.githubusercontent.com/37100189/45699960-3659c300-bb20-11e8-9651-5916f2246be4.png">
<img width="300" alt="screen shot 2018-09-18 at 8 51 54 am" src="https://user-images.githubusercontent.com/37100189/45699961-3659c300-bb20-11e8-80e7-d6e6c5aa80b7.png">

**Comment by line47** [comment]
Do we have to show these items in the small square buttons on print? It would be much easier to render them a bit more suited for print

**Comment by ryanhofdotgov** [comment]
For right now, we would prefer an expeditious approach that ensures the text fits in the button both on screen and when printed to PDF without changing the basic form design. 

I haven't verified that on screen it looks the same as PDF though. The PDF was generated via macOS print to PDF function in Chrome.

**Comment by bpdesigns** [comment]
What if the border is on the outside of the box? The issue I see with filling it in black - even though it makes it stand out clear - is that it will be a lot of ink if someone is printing it out

**Comment by line47** [comment]
We could def add a border to the outside but we would lose the rounded corners as that is not supported for `outline` like it is `border`
![screen shot 2018-09-19 at 8 54 42 am](https://user-images.githubusercontent.com/1449852/45754365-805aab80-bbe9-11e8-836f-768d3562c8ff.png)

**Comment by bpdesigns** [comment]
Thats what I would go with.

**Comment by ryanhofdotgov** [comment]
Sounds like a good solution - thanks, I'll check out the PR. I really hope no one is printing these. A "blown out" case is 500+ pages if you print out each of the 10 sections' review page. :)

**Comment by line47** [comment]
ooof 🤕
