### ISSUE TITLE
Update how "Relative type" is displayed

### ISSUE THREAD

**Issue by bpdesigns** [18F/e-QIP-prototype#823]
### Relationships > Relatives
**"Add each relative applicable to you, regardless if they are living or deceased."**

_Current_ 
<img width="640" alt="screen shot 2018-09-18 at 2 07 56 pm" src="https://user-images.githubusercontent.com/15329140/45708145-ad0db500-bb4e-11e8-854e-701a0c49c964.png">

_Update_ 
Create an initial radio button list for:
- Parent
- Sibling (Brother, Sister)
- Child

_From here reveal the options in each category as a second list (see below)_

**Parent**
- Mother
- Father
- Father-in-law
- Mother-in-law
- Stepmother
- Stepfather
- Foster parent
- Guardian

**Sibling (brother, sister)**
- Brother
- Sister
- Stepbrother
- Stepsister
- Half-brother
- Half-sister

**Child**
- Child
- Stepchild
- Adopted/Foster Child
(note in eqip Adopted/Foster Child and Child are considered one option)

**Comment by bpdesigns** [comment]
@line47 here's the idea I mentioned earlier

**Comment by line47** [comment]
Update: We should pull mother and father out and make them required then provide additional relatives after.

**Comment by ryanhofdotgov** [comment]
Also note that mother-in-law, father-in-law are required if applicant is married/civil union/etc.
