### ISSUE TITLE
Test cases have phantom validation errors

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#824]
**What did you do?**

Load up `api/testdata/complete-scenarios/test1.json` into an flushed/empty account with `load-scenario` command-line tool. Go to overall review section and validate. 

Same for test cases 2 and 3.

**What did you expect to see?**

No validation errors.

**What did you see instead?**

Validation errors in multiple sections. When you drill down to find the errors, there is nothing specifically flagged.

**Additional Information**

e-QIP does not flag any validation errors when submitted, so likely a false positive in eApp logic.

Completed ticket corrects and verifies that the following test cases do not have any validation errors when loaded:
- [x] test1.json
- [x] test2.json
- [x] test3.json
- [x] test4.json
- [x] test5.json
- [x] test6.json

**Comment by ryanhofdotgov** [comment]
@apburnes Just as a heads up, most of the errors seem to be the same phantom table errors we've had for a few weeks at least, but I'm also noticing false zip code errors now (e.g., zip code flagged as bad when it is definitely good). I'm going to publish some docs on my load tools today so everyone can easily take a look for themselves.

**Comment by hursey013** [comment]
Using https://github.com/18F/e-QIP-prototype/commit/a326d1a1c0b824de50bc89b5ca9f6970dc156055 and wiping the db before each test case, here are the results I've gotten:

- Test 1: Successful review
- Test 2: Phantom error, `Financial record > Delinquent payments`
- Test 3: Successful review
- Test 4: Successful review
- Test 5: Phantom error, `Relationships > Marital, Cohabitants, Relatives` and `Investigative and criminal history > Offenses`
- Test 6: Successful review
