### ISSUE TITLE
Fails to ask all required questions for relatives

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#848]
eApp fails to ask all the required questions for relatives that are not a U.S. Citizen, but have a U.S. address and are not deceased. See highlighted screenshot and father-in-law in `test7.json`.

<img width="500" alt="screen shot 2018-09-23 at 10 11 27 pm" src="https://user-images.githubusercontent.com/37100189/45938408-7e447400-bf7e-11e8-8431-dd9148066def.png">

eApp does not ask:
* first contact
* last contact
* methods of contact
* frequency of contact

**Comment by apburnes** [comment]
@ryanhofdotgov the user needs to input their relatives __Provide your relative's country(ies) of citizenship__ and __Is your relative deceased? (No)__ before the circled fields are visible. Maybe there is a missing input in the test to properly display the additional questions? Reconfigure logic to show the fields when __Provide your relative's place of birth__ and __Is your relative deceased?__ are selected?

**Comment by ryanhofdotgov** [comment]
For test case 7, IIRC, FIL has like 3 different non-U.S. citizens and is marked as alive. So I think something isn't correctly responding to that input. 

I'm guessing the questions didn't show up when NBIB originally input the data (and don't show up now when we re-load from JSON file).
