### ISSUE TITLE
If state doesn't exist in zip code dictionary, fail validation

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#851]
**What did you do?**

Entered DQ as a state abbreviation.

**What did you expect to see?**

Zip code validation error.

**What did you see instead?**

No zip code validation error.

**Additional Information**

There are some funky state abbreviations in our state drop down list, DQ is just one of them:
```
DQ jarvis island
HQ howland island
FQ Baker island
JQ Johnston Atoll
KQ ￼ Kingman Reef
MQ Midway Atoll
BQ Navassa Island
LQ Palmyra Atoll
WQ Wake island
```

These US possessions are mostly uninhabited or consist of an air strip, etc. The e-QIP XML schema has lots of different rules about when these should be included and when they don't, that eApp doesn't take into account.

However, in the short term, we can make sure zip code fields don't validate if someone pulls one of these options from the drop-down. In doing that, I think we probably solve 99% of larger issue, ensuring they aren't used in form locations they shouldn't be.

Identified by NBIB's test case #&#xfeff;7

**Comment by apburnes** [comment]
Do we want any additional error info when one of these are selected? Or just stick to the default state zip code error?
