### ISSUE TITLE
Manual Test in IE 11

### ISSUE THREAD

**Issue by michaelccata** [18F/e-QIP-prototype#869]
**What did you do?**

Create a real-world, manual, full case in IE 11. 

**What did you expect to see?**

*Describe the desired behavior and what would deem this issue, bug, or feature
complete.*

**What did you see instead?**

*Include a high-level description of the feature or error here*

**Additional Information**

*Include any images, steps to recreate, notes, emojis, or anything else that
seems pertinent.*

 - What browser and version are you using?  IE 11
 - What operating system?  Mac

**Comment by ryanhofdotgov** [comment]
@michaelccata I cleared the data from your account on dev.

Also: while you are splitting up the form, it would be good to go through one complete end to end form submission with IE11; i.e., verify that there aren't any IE UI defects preventing an SF-86 submission.

**Comment by michaelccata** [comment]
Thanks! I'll dig in soon. I'll do an end-to-end in addition to deeper probing on the first five sections.

**Comment by michaelccata** [comment]
Checking in w/ this test. I did sections 1-5. 

Noticed https://github.com/18F/e-QIP-prototype/issues/457 using the GSA VPN provided IE (version unknown) but was unable to reproduce in another VPN environment with another version of IE (version unknown).
<img width="736" alt="screen shot 2018-10-05 at 11 41 52 am" src="https://user-images.githubusercontent.com/4422873/46550500-49e88600-c8a3-11e8-980b-c6af8087cfd5.png">
<img width="558" alt="screen shot 2018-10-05 at 11 41 07 am" src="https://user-images.githubusercontent.com/4422873/46550501-49e88600-c8a3-11e8-81ac-2b1df6d0f487.png">

Also noticed that the .svg for the save icon wasn't coming up in the GSA VPN. 
<img width="208" alt="screen shot 2018-10-05 at 11 37 27 am" src="https://user-images.githubusercontent.com/4422873/46550783-093d3c80-c8a4-11e8-8f41-e01583f1ee90.png">

The fonts were also different (not looking good) in the GSA VPN.  I'd put this issue and the two above at lower priorities.

A low-to-medium issue was the automatic false-positive trigger of the zip code in Section 2 - Job History. It looks like the zip code is marked false if you select a previous address (despite that address was already validated before.) 
<img width="646" alt="screen shot 2018-10-05 at 12 10 52 pm" src="https://user-images.githubusercontent.com/4422873/46551061-bf088b00-c8a4-11e8-8fdd-1ee26e19371a.png">

**Comment by michaelccata** [comment]
Was able to complete the whole form and validate all information. Was not able to officially submit but I had no validation issues that would have prevented me from hitting "submit." 

<img width="629" alt="screen shot 2018-10-05 at 1 30 57 pm" src="https://user-images.githubusercontent.com/4422873/46551200-20c8f500-c8a5-11e8-8bb7-6ad2c932fde7.png">
