### ISSUE TITLE
Collect secondary addresses

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#924]
In certain parts of the SF-86, if an APO/FPO address is indicated or an non-US address is indicated, a secondary address is solicited from the applicant. You can find these instances by searching the SF-86 PDF for "If you have indicated an" and looking at the conditional `(a)` and `(b)` options:

<img width="500" alt="screen shot 2018-10-03 at 8 53 26 am" src="https://user-images.githubusercontent.com/37100189/46422819-f7b03500-c6e9-11e8-889c-e3bca9414fe3.png">

Verify that omitting these secondary addresses was not an approved policy decision, and if not, implement them.

Edit:
Scope of this ticket is to just collect and persist the secondary addresses. Follow-on work to properly encode them into e-QIP XML is in https://github.com/18F/e-QIP-prototype/issues/1027

**Comment by hursey013** [comment]
@ryanhofdotgov Should we wait on confirmation before beginning this one?

**Comment by ryanhofdotgov** [comment]
@hursey013 Yeah, before we can start on this, we need policy sign off. I'll work on that, and then put this back in To Do once we have it.

**Comment by ryanhofdotgov** [comment]
@hursey013 Heard an initial take from policy team – we should go ahead and implement this, following the guidance on the PDF form (screenshot above)

1) If applicant enters an APO address, *require* collection of a physical address (see fields in screenshot and in `PhysicalLocation` element in applicant XSD).

2) If applicant enters a foreign address, show an optional field set to collect an APO address, first by asking the question "Did you have an APO/FPO address at this location?".

This secondary collection workflow appears at the following 6 locations in the form:
* Applicant residence address
* Employment address (including if employment is active duty, etc.)
* Applicant's current spouse residence address
* Address of person who can verify unemployment/self-employment
* Address of person who can verify residence
* Supervisor's address

These locations where identified by searching for "If you have indicated an APO" in the SF-86 PDF and cross-checking with the instances of `PhysicalLocation` in the applicant XSD.

**Comment by ryanhofdotgov** [comment]
Upon closer inspection and in testing with e-QIP, employment address has a slight different secondary address workflow from all the others. Going to separate that out into https://github.com/18F/e-QIP-prototype/issues/1050

**Comment by el-mapache** [comment]
@ryanhofdotgov Do we also need phone numbers for these associated addresses?

If the user enters an APO address, is a phone number part of the physical location they are specifying? What about if the user enters a foreign address, do they need a phone number for the APO location (if they had one)?

From the layout of the form, it looks as though we only need to provide a phone number in the second case?

I'm having a bit of additional confusion because the eApp form currently doesn't ask for a phone number at all for some of the residence questions, including the Applicant residence address.

**Comment by ryanhofdotgov** [comment]
@el-mapache So a better screenshot for this issue is this one, from page 7 of the SF-86. The employment location, ended up being a similar but different beast, so I split that off into #1050 

For the ones of this type, no associated phone number with the address is solicited, just an address. In the screenshot below I've circled the residence verifier address set:

<img width="400" alt="screen shot 2018-10-26 at 8 35 16 am" src="https://user-images.githubusercontent.com/37100189/47576828-4b352d80-d8fa-11e8-9093-fb61acb10b65.png">

**Comment by ryanhofdotgov** [comment]
With #924 split off into #1107, #1108, and #1109, PR #1087 closes this.
