### ISSUE TITLE
Attachments section is not present in the side nav

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#961]
**What did you do?**

I was trying to navigate back to the attachment section after navigating to another section of the form.

**What did you expect to see?**

I expected to see a subsection for "Attachments" under the main section "Review and submit"

**What did you see instead?**

I was only able to navigate to the attachments section again by going to the "Review" subsection of "Psychological and emotional health" and clicking the "Next attachments" button

**Additional Information**

Tested on Mac 10.14 using Chrome

**Comment by ryanhofdotgov** [comment]
@joshmfranklin Right now Attachments option is disabled by default until we can get https://github.com/18F/e-QIP-prototype/issues/397 resolved. You can enabled it locally if you like through this [setting](https://github.com/18F/e-QIP-prototype/blob/develop/docs/CONFIGURATION.md#attachments_enabled)

**Comment by joshmfranklin** [comment]
@ryanhofdotgov thanks!
