### ISSUE TITLE
Additional names used "from date" is validating against wrong DOB

### ISSUE THREAD

**Issue by joshmfranklin** [18F/e-QIP-prototype#962]
**What did you do?**

Add a relative with a DOB, I used 04/13/1960, then give them an additional name used with a date range.

**What did you expect to see?**

I expected to be able to add a "From date" for the additional name on or before the relatives DOB.

**What did you see instead?**

I was only able to add a "From date" for the additional name on or before **MY** DOB

**Additional Information**

Tested using Mac 10.14 using Chrome

**Comment by ryanhofdotgov** [comment]
This may be resolved by one of the recent date audits that @line47 did or the one still waiting a PR review/merge.

**Comment by line47** [comment]
I think this is fixed in my PR @joshmfranklin can you pull down the `sw-date-val-complex` branch to take a look?
https://github.com/18F/e-QIP-prototype/pull/1058

**Comment by line47** [comment]
I verified this is still an issue and assigned to myself to fix
