### ISSUE TITLE
USPS address validation modal looks bad

### ISSUE THREAD

**Issue by el-mapache** [18F/e-QIP-prototype#969]
**What did you do?**

Validated an address

*Including steps for recreating it, if applicable.*

* Set up a USPS API account as detailed in the docs
* Anywhere that the user needs to supply a complete address, do so, and blur the form

**What did you expect to see?**

I expect to see a centered modal with pleasing styling

**What did you see instead?**

A modal jammed up at the top of the page

**Additional Information**

Tested on Chrome, but given the placement of the modal I would suspect it looks bad in other browsers too

![screen shot 2018-10-10 at 3 23 49 pm](https://user-images.githubusercontent.com/1421848/46769389-7be15a00-cca0-11e8-84fc-3b9368149e73.png)

**Comment by joshmfranklin** [comment]
@el-mapache Ill take a look and drop in some updated design ASAP.

**Comment by joshmfranklin** [comment]
@el-mapache if you could point me in the directions for how to get the USPS API to work locally, I think I can fix this up pretty quick.

**Comment by ryanhofdotgov** [comment]
@joshmfranklin 
https://github.com/18F/e-QIP-prototype/blob/develop/docs/usps.md

**Comment by joshmfranklin** [comment]
@ryanhofdotgov is this issue closed?

**Comment by ryanhofdotgov** [comment]
Yup – thanks.
