### ISSUE TITLE
Logo missing from top header when condensed

### ISSUE THREAD

**Issue by hursey013** [18F/e-QIP-prototype#970]
**What did you do?**

With the desktop view, as you begin scrolling down the page, the top header collapses like this:

<img width="504" alt="screen shot 2018-10-11 at 8 22 43 am" src="https://user-images.githubusercontent.com/1178494/46803929-50f21700-cd2f-11e8-9826-4cdabd6e5fae.png">

**What did you expect to see?**

It could be by design, but there is a blank area to the left of the page title that looks like there should be a logo and "SF86" - perhaps similar to the style of the mobile menu:

<img width="341" alt="screen shot 2018-10-11 at 8 22 54 am" src="https://user-images.githubusercontent.com/1178494/46803971-741cc680-cd2f-11e8-903e-989cc18b61f7.png">

**Comment by ryanhofdotgov** [comment]
A related ticket is https://github.com/18F/e-QIP-prototype/issues/571
