### ISSUE TITLE
Residence item errors when the "from" date is equal to applicant's birthday

### ISSUE THREAD

**Issue by christopherhuii** [18F/e-QIP-prototype#976]
**What did you do?**

1. Add birthday
2. Add an address where you have lives
3. Set start of residence to the same date as the birthday

**What did you expect to see?**

No Errors

**What did you see instead?**

Error that the `from` date should be after your date of birth.

**Additional Information**

`from` date should be able to be equal to the user's birthday.
I suspect the solution should be to go into `ResidenceItem.jsx` and find the corresponding `<DateRange />` component and add a `minDateEqualTo` prop to make it true.

**Comment by ryanhofdotgov** [comment]
This is probably resolved by the work @line47  is doing for #773

**Comment by christopherhuii** [comment]
@ryanhofdotgov Ah I see. Thanks
