### ISSUE TITLE
Improve visual appearance of save() error message

### ISSUE THREAD

**Issue by ryanhofdotgov** [18F/e-QIP-prototype#986]
https://github.com/18F/e-QIP-prototype/pull/978 was implemented rapidly in order to meet a deployment deadline. 

Revisit the task and implement an improved, more visually consistent mechanism to display that an error in saving the form has occurred.

**Comment by joshmfranklin** [comment]
@ryanhofdotgov happy to take a look at this. Is there a way to trigger the error locally so that I can see the current styling?

**Comment by ryanhofdotgov** [comment]
One way is to shutdown all the containers after signing in, with the browser still open to eApp, and then click save.

**Comment by joshmfranklin** [comment]
OK so I have a couple options and some questions about errors on save()

Option 1 - Alert banner with save action

**Comment by joshmfranklin** [comment]
Ok here are some options for improvements to the save error alert along with some questions. 

Option 1 - Banner with save action
Upon save error we could show a global alert banner under the main nav with an action to try saving again. This however would not block the UI and would allow the user to make more additions to the form that may not save. 

![error on save](https://user-images.githubusercontent.com/4196834/47171921-0a289200-d2d8-11e8-9b3b-b3a62e644266.png)

Option 1 - Modal with save action
Upon save error we could show a UI blocking modal with an action to try saving again. This solves the problem of allowing the user to enter more data that potentially wouldn't save.

![error on save modal](https://user-images.githubusercontent.com/4196834/47171980-2af0e780-d2d8-11e8-864e-3996479fed90.png)

Question: Right now when I see the save error message and click OK it sends me back to the login page. Is this the intended behavior or will the action in production actually try to save again?

**Comment by ryanhofdotgov** [comment]
Per Chris:
- time it was last saved
- if this error persists "please call..."

**Comment by joshmfranklin** [comment]
- I've added the "time since last saved" line to the error modal.
- The message that is displayed to the user when the form fails to submit is very generic... "There was a problem submitting your SF-86. Please contact support for additional information." I think we should include some sort of email or phone number in the modal that would point toward someone for support. Please let me know what the best phone number or email address to use for this purpose. 

![error on save modal](https://user-images.githubusercontent.com/4196834/47658056-b126ec80-db68-11e8-966b-610cbb301b2f.png)

**Comment by ryanhofdotgov** [comment]
I would have a placeholder email address/phone number in the design, and then when we go to implement it, that will get externalized separate in the locale. There are a few other places on the site where it would be useful to reference.

**Comment by ryanhofdotgov** [comment]
LGTM – deferring implementation to #1106
